### PR TITLE
prevent naming mistake

### PR DESCRIPTION
**Pull request by tonytonyjan**
These method is borrowed from `rails new`
ref: https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/app_generator.rb#L297

### CODE REVIEW

**Comment by rohit** [comment]
Firstly, the build is passing the one incomplete run is because of a timeout issues as I understand it.

Regarding the PR, the call to `valid_name?(opts)` looks a bit awkward to me. I mean the method name it self. Maybe something along the lines of `ensure_safe_gem_name(opts[:name], opts[:constant_array])`. I'm against passing the whole `opts` object too so I think passing just the `name` and `constant_array` should do?

Don't make any changes unless one of the maintainers confirm/deny my suggestion which is based purely on taste. :grin:

**Comment by BM5k** [comment]
bump?

**Comment by indirect** [comment]
@bm5k want to address the issues mentioned?

**Comment by BM5k** [comment]
@indirect do you have an opinion on @rohit’s suggestion?

**Comment by indirect** [comment]
yeah, it sounds good to me.

**Comment by TimMoore** [comment]
These changes were merged from #3424

**Pull request closed without merging**
