### PR TITLE
Check that `ruby_scope` is concatenated to globally configured install paths

### PR DESCRIPTION
**Pull request by smlance**
Confirms that https://github.com/bundler/bundler/issues/3552 is implemented in 2-0-dev.

### CODE REVIEW

**Comment by smlance** [comment]
The Travis build looks good, since the only failing specs are those that are failing in 2-0-dev. We'll wait to merge this until the RuboCop changes are merged.

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r+

**Comment by indirect** [comment]
Looks like this is in the Homu queue behind the other PR: http://homu.io/q/bundler/bundler

I'll try updating the travis config to run on the `auto` branch.

**Comment by segiddins** [comment]
@indirect I've update the config on your other PR

**Pull request merged**
