### PR TITLE
Retry gem downloads

### PR DESCRIPTION
**Pull request by jkeiser**
Fixes https://github.com/bundler/bundler/issues/4846

### CODE REVIEW

**Comment by segiddins** [comment]
@indirect r?

**Comment by indirect** [comment]
Not sure 100% of failures will be retried with that exception list, but I'm happy to start here.

@homu r+

**Comment by jkeiser** [comment]
@indirect two things:

1. We are getting bit by this a *lot* in our CI and this patch seems fairly safe (to me anyway :) ). Is there any possibility we can get this patch into a released bundler in the near future?
2. Where would you like to see the retry at? I'm happy to make a new patch with it up further in the stack. This is going to be seen very intermittently, so it's very possible that people will never report it--I'd rather we just get it fully robust in one swoop while we have the energy.

**Comment by jkeiser** [comment]
@indirect regarding #2, here is what I considered the relevant stack (taken from #4846):

```
Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/multipart-post-1.2.0.gem)
/opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:308:in `rescue in fetch_path'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:281:in `fetch_path'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:324:in `cache_update_path'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:188:in `download'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:615:in `download_gem'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:410:in `fetch_gem'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:116:in `install'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/installer/gem_installer.rb:57:in `install'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/installer/gem_installer.rb:15:in `install_from_spec'
```

**Comment by jkeiser** [comment]
I tried to put the retry as close to the boundary with `rubygems` as possible to have the maximum chance of catching retries.

**Comment by chrismo** [comment]
looks like it went out with 1.13.0.rc.2 on the 21st - https://github.com/bundler/bundler/commit/ce8249416fbb6570cc0a01500aca2f01195840d3

**Comment by jkeiser** [comment]
@chrismo hooray! Thanks!

**Pull request merged**
