### PR TITLE
[DSL] Infer ruby from .ruby-version

### PR DESCRIPTION
**Pull request by segiddins**
See https://github.com/bundler/bundler/pull/3441 for discussion.
Closes https://github.com/bundler/bundler-features/issues/79.

### CODE REVIEW

**Comment by indirect** [comment]
```
spec/other/platform_spec.rb:127:47: C: Style/SpaceInsideBlockBraces: Space between { and | detected.
      bundled_app(".ruby-version").open("w") { |f| f.write "2.2.3\n" }
```

**Comment by segiddins** [comment]
@indirect r+?

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
All of the failing specs are for `bundle inject` -- are they failing upstream as well?

**Comment by segiddins** [comment]
@indirect ?

**Comment by indirect** [comment]
@homu retry

**Comment by segiddins** [comment]
Should be fixed now

**Comment by indirect** [comment]
@homu retry

**Comment by indirect** [comment]
@segiddins ?

**Comment by colszowka** [comment]
Regarding what @indirect wrote on #3441, I'd like to suggest to not do this automatically, but maybe have a shorthand to the File.read pattern, by simply checking if the argument given to 'ruby' is a file and reading that instead? Alternatively, we could have a special-meaning `ruby :ruby_version` flag that reads in the .ruby-version file when called?

**Comment by segiddins** [comment]
Hahaha  I'd pushed my fix to the wrong branch

@homu r=indirect

**Pull request merged**
