### PR TITLE
Run Rubocop before specs

### PR DESCRIPTION
**Pull request by TimMoore**
This fails faster on style issues.

### CODE REVIEW

**Comment by indirect** [comment]
:+1: @homu +r

**Comment by indirect** [comment]
lol oops @homu r+

**Comment by segiddins** [comment]
@TimMoore I don't believe this will actually make it fail fast, since we're calling `safe_task` ?

**Comment by indirect** [comment]
Yeah, I think that's true.

**Comment by indirect** [comment]
How did this ever fail when rubocop failed, anyway? We weren't even checking for it on line 269.

**Comment by indirect** [comment]
@homu r+

**Comment by TimMoore** [comment]
Good catch, thanks @indirect & @segiddins.

**Pull request merged**
