### PR TITLE
[Outdated] Support running when gems are not yet installed

### LINKED ISSUE #5553: Outdated command fails if dependencies aren't installed
**Steps to reproduce:**

Run `bundle outdated` in a project where dependencies are not installed.

**Expected result:**

A report of which gems are out of date.

**Actual result:**

```
Could not find missing-gem in any of the sources
```

**`bundler env` output:**

    ## Environment
    
    ```
    Bundler   1.14.6
    Rubygems  2.4.5.1
    Ruby      2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin14]
    Git       2.8.1
    Platform  x86_64-darwin-14
    ```
    ```
    
    ## Gemfile
    
    ### Gemfile
    
    ```ruby
    source 'https://rubygems.org'
    
    gem 'timecop'
    ```
    
    ### Gemfile.lock
    
    ```
    GEM
      remote: https://rubygems.org/
      specs:
        timecop (0.8.1)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      timecop
    
    BUNDLED WITH
       1.14.6
    ```

### PR DESCRIPTION
**Pull request by segiddins**
Closes #5553

### CODE REVIEW

**Comment by segiddins** [comment]
@indirect @colby-swandale r?

**Comment by indirect** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
@bundlerbot retry

**Comment by colby-swandale** [comment]
nice! 🎉

**Pull request merged**
