### PR TITLE
Avoid RubyGems psych warning breaking the tests

### PR DESCRIPTION
**Pull request by segiddins**
This, along with https://github.com/rubygems/rubygems/pull/2034, should get tests passing again 🙌

### CODE REVIEW

**Comment by duckinator** [comment]
Talked to @segiddins and they said the failures are unrelated. So in that case, this looks good to me, but I don't have permission to merge it so I'm not sure that matters lol

**Comment by olleolleolle** [comment]
@bundlerbot r+

**Comment by walf443** [comment]
#6084 was merged. @segiddins Can you try to rebase?

**Comment by segiddins** [comment]
@bundlerbot retry

**Pull request merged**
