### PR TITLE
[2.0] Don't persist install options

### PR DESCRIPTION
**Pull request by asymmetric**
Implements bundler/bundler-features#26.

Some specs are failing, but wanted to get  some early feedback.

* What do you think about resetting the `BUNDLE_WITH/WITHOUT` ENV variables after each spec?
* If that's OK, should setting `ENV` be the preferred method in most specs, compared to `bundle config`, `config`?

### CODE REVIEW

**Comment by segiddins** [comment]
How does this differ from https://github.com/bundler/bundler/commit/3d76c8fefb4eed7a082719e693396b7cdb0d58b0 ?

**Comment by asymmetric** [comment]
@segiddins AFAICS, the actual implementation (i.e. removing flags, moving logic) is not in that commit, nor in the `2-0-dev` branch.

**Comment by segiddins** [comment]
OK, @smlance will need to review this then :)

**Comment by asymmetric** [comment]
@homu thanks, I'll take a look as soon as I come back from the holidays (~2 weeks).

**Comment by smlance** [comment]
@asymmetric: I've been using parts of your code to tackle this and have already removed the cache and path flags. I'm currently reworking the way `bundle config` parses the with and without flags. See https://github.com/bundler/bundler/pull/3827, https://github.com/bundler/bundler/pull/3937, and https://github.com/bundler/bundler/pull/3939.

**Comment by asymmetric** [comment]
@smlance Glad to have been of help (although attribution would have been even nicer :cry:)

I guess this PR can be closed then.

**Comment by smlance** [comment]
https://github.com/bundler/bundler/pull/3939 uses the deletions you made in `cli/install.rb` and the line you added to `cli/config.rb`. If there's some way I can give more credit (@segiddins?), let me know. Thanks for the contributions!

**Comment by segiddins** [comment]
@smlance the proper way to give attribution is to use someone's git commits.

**Comment by indirect** [comment]
To expand on that, there are a few ways you can give attribution:

 - you can directly use the actual git commits via `git cherry-pick <SHA1>` (usually then adding your own commits later if needed)
 - you can use the author information from their commit when you commit what is mostly their change via `git commit -C <SHA1>` (if their commit didn't quite work as is)
 - worst case, you can explicitly acknowledge inspiration/code in the commit message

In this case, I think you could likely use some combination of cherry-picking commits and writing your own commits to get the same result, but it's hard to be sure without trying it myself.

**Pull request closed without merging**
