### PR TITLE
[Git] Fix checking for equality when a version includes a -

### LINKED ISSUE #4385: Prerelease gems with `-` cause `bundle show` to fail
```
$ cat Gemfile
source "https://rubygems.org"
gem "rack-timeout", "0.4.0-beta.1", github: "heroku/rack-timeout"

$ bundle install
Fetching git://github.com/heroku/rack-timeout.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Using bundler 1.12.0.rc
Using rack-timeout 0.4.0.pre.beta.1 from git://github.com/heroku/rack-timeout.git (at master@e6d7211)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./.bundle.

$ bundle show
The git source git://github.com/heroku/rack-timeout.git is not yet checked out. Please run `bundle install` before trying to start your application

$ bundle exec echo what
what

$ bundle show
The git source git://github.com/heroku/rack-timeout.git is not yet checked out. Please run `bundle install` before trying to start your application
```

First, it should never be possible to have `install` succeed and then have `show` fail. It should be doubly-impossible to have `install` and `exec` both succeed and still have `show` fail. Lastly, Bundler says it's using `rack-timeout 0.4.0.pre.beta.1`. That's not a version that exists, because [the gemspec for rack-timeout](https://github.com/heroku/rack-timeout/blob/master/rack-timeout.gemspec#L5) has the version set to `0.4.0-beta.1`.

???

### PR DESCRIPTION
**Pull request by segiddins**
Closes #4385.

### CODE REVIEW

**Comment by segiddins** [comment]
@indirect r?

**Comment by indirect** [comment]
IMO, if the Gemfile (and the gem's gemspec) say that the gem version is `1.0.0-beta.1`, then `bundle show` should also print the version `1.0.0-beta.1`. Why are we accepting a version number and installing it, but then printing a different version number?

**Comment by segiddins** [comment]
Because that's how RubyGems interprets that version string as a `Gem::Version` object

**Comment by segiddins** [comment]
@indirect ping

**Comment by segiddins** [comment]
Ping

**Comment by segiddins** [comment]
I'm going to merge this soon unless anyone objects

**Comment by RochesterinNYC** [comment]
LGTM.

**Comment by segiddins** [comment]
@homu r+

**Comment by deivid-rodriguez** [comment]
Note that in the semver protocol, these are the [only possible prerelease specifications](https://semver.org/#spec-item-9). So this surprising behavior (your lock file or `bundle show` showing a different version string from the one you have declared) happens by default if you follow semver.

It seems to me that the only possible solution would be to break backwards compatibility in `rubygems` and start using "semver prereleases", since currently for `rubygems` any version string containing non-numeric characters [is a pre-release](https://github.com/rubygems/rubygems/blob/9054079ce8a1ad05dd206a3562339b74712c7fc6/lib/rubygems/version.rb#L289-L295).

**Pull request merged**
