### PR TITLE
Make `bundler` and `bundle` executables have the same functionality

### LINKED ISSUE #4725: `bundler` and `bundle` executables should be the same functionally
The `bundler` executable (https://github.com/bundler/bundler/blob/master/exe/bundler) should functionally be the same as the `bundle` executable (https://github.com/bundler/bundler/blob/master/exe/bundle).

Ideally, this would be done in a way that doesn't involve duplication of code and doesn't require updating code in two places when a change is made to the `bundle` executable.

### PR DESCRIPTION
**Pull request by b-ggs**
Closes #4725

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
@segiddins @indirect quick sanity check, do we have existing test coverage for the `bundler` executable? Can't seem to find any from a preliminary search of the specs.

**Comment by segiddins** [comment]
Maybe not? We should add a quick test that just does `bundler --version` or something?

**Comment by b-ggs** [comment]
@segiddins @RochesterinNYC Added a spec for `bundler --version`!

**Comment by b-ggs** [comment]
I've force-pushed this branch several times, all resulting in an errored check from Travis, which I highly doubt was caused by the code I've added. Are we currently experiencing some weird issues with Travis at the moment?

**Comment by segiddins** [comment]
@b-ggs do the specs pass locally for you?

**Comment by RochesterinNYC** [comment]
Looks like flakey behavior on Travis's part. Restarted the build.

**Comment by segiddins** [comment]
@b-ggs this should pass if you rebase it

**Comment by b-ggs** [comment]
@segiddins Gotcha. Rebased from `master`. Tests are running now. And yeah, it was passing for me locally.

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
