### PR TITLE
Fix Lint/UnusedMethodArgument

### PR DESCRIPTION
**Pull request by Koronen**
* ~~Remove non-referenced explicit block arguments in favor of depending on the   implicit block provided to every method.~~
* Remove unused method `Spec::Builders#build_dep`.

### CODE REVIEW

**Comment by segiddins** [comment]
I don't like this, I far prefer explicit block arguments.

**Comment by segiddins** [comment]
This is failing on CI

**Comment by segiddins** [comment]
@indirect iirc you dislike this?

**Comment by indirect** [comment]
I prefer explicit &block to make it clear that the method takes a block, and I prefer not prefixing variables with underscores. Maybe those are cases where we can improve the code, or maybe they are cases where it's pointless to enumerate the method arguments.

**Comment by Koronen** [comment]
If we don't agree with the rule, maybe we should instead disable the rule in `.rubocop.yml` and remove it from `.rubocop_todo.yml`?

**Comment by segiddins** [comment]
@Koronen yup

**Comment by Koronen** [comment]
Closing in favor of #3956.

**Pull request closed without merging**
