### PR TITLE
Add a basic bundle lock manual [ci skip]

### PR DESCRIPTION
**Pull request by JuanitoFatas**
This Pull Request adds a skelton of `bundle lock` man page.

### CODE REVIEW

**Comment by segiddins** [comment]
:+1:

**Comment by deivid-rodriguez** [comment]
What's the difference with `bundle check`?

**Comment by indirect** [comment]
@deivid-rodriguez check throws an error if resolving the bundle would require downloading gem information, lock downloads the information and resolves the bundle.

**Comment by deivid-rodriguez** [comment]
@indirect Thanks

**Pull request merged**
