### PR TITLE
Call IO.popen instead of backticks

### PR DESCRIPTION
**Pull request by nobu**
IO.popen with the command in an array doesn't need command line
quotes, and is safer.

Thanks so much for the contribution!
To make reviewing this PR a bit easier, please fill out answers to the following questions.

### What was the end-user problem that led to this PR?

Back-ticks with command line quoting is dangerous.

### What was your diagnosis of the problem?

Back-ticks is not for complex purpose.

### What is your fix for the problem, implemented in this PR?

Use `IO.popen` and redirection option instead.

### Why did you choose this fix out of the possible options?

`IO.popen` and options of `spawn` have been introduced for such purpose.

### CODE REVIEW

**Comment by olleolleolle** [comment]
@nobu Thanks for this change!

The CI build fails on a single style check: seems like `%i`-literals (` %i[child out]`) need to be lists of symbols instead (`[:child, :out]`).

**Comment by colby-swandale** [comment]
I've created #6039 which sets Rubocop to target ruby version 2.3 which runs the rubocop parser correctly for this PR.  If you can please wait for that to be merged.

**Comment by indirect** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
@bundlerbot retry

**Pull request merged**
