### PR TITLE
[man] fix typo on bundle-binstubs

### PR DESCRIPTION
**Pull request by samueloph**
Typo found while i was packaging 1.16.1 for Debian

### CODE REVIEW

**Comment by colby-swandale** [comment]
Thanks! @bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot retry

**Comment by olleolleolle** [comment]
@bundlerbot retry

**Comment by olleolleolle** [comment]
One fewer failed builds. 

Just one, about "that directory already exists" in an unrelated-to-this-PR test.

https://travis-ci.org/bundler/bundler/jobs/324098026#L835

**Comment by colby-swandale** [comment]
@olleolleolle please wait for a fix before retrying again

**Comment by olleolleolle** [comment]
@colby-swandale Apologies, my mistake. I believed a fix had been got in there.

**Comment by segiddins** [comment]
Has anyone been able to repro the issue locally?

**Comment by colby-swandale** [comment]
@segiddins i've been running the full test suit as close to the travis env i can get all week without any successful reproduction 😢

**Comment by segiddins** [comment]
@bundlerbot retry

**Pull request merged**
