### PR TITLE
Fix Style/TrailingComma

### PR DESCRIPTION
**Pull request by esasse**

### CODE REVIEW

**Comment by segiddins** [comment]
IIRC we might need to disable this one for 1.8.7 compatibility? let's see what CI says

**Comment by maxjacobson** [comment]
If so, rubocop can require the absence of a trailing comma https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/trailing_comma.rb#L24

**Comment by esasse** [comment]
You were right @segiddins. What do you want me to do? Just disable this one or add the check to require absence of trailing comma as @maxjacobson suggests? I vote for Max idea.

**Comment by segiddins** [comment]
I'll handle it, thanks for the PR though!

**Pull request closed without merging**
