### PR TITLE
Update to Molinillo 0.6.0

### PR DESCRIPTION
**Pull request by segiddins**
### What was the end-user problem that led to this PR?

The problem was Molinillo 0.5.x was so old :P

### What was your diagnosis of the problem?

My diagnosis was we needed to _fix every single known bug_, while also improving performance.

### What is your fix for the problem, implemented in this PR?

My fix is to behold the awesomeness of https://github.com/CocoaPods/Molinillo/releases/0.6.0, and introduce it to Bundler.

### CODE REVIEW

**Comment by andremedeiros** [comment]
Always love when "speed up" is part of the changelog! :+1:

**Comment by indirect** [comment]
woo :tada:

**Comment by greysteil** [comment]
So psyched for this!

**Comment by segiddins** [comment]
@bundlerbot r+

**Pull request merged**
