### PR TITLE
Wrap sudo access prompts in a mutex

### LINKED ISSUE #3910: Parallel jobs break system gems installation
When bundler is configured for using parallel jobs, the installation of system gems (which request sudo permissions) fails.

Specifically, on `bundle install` execution, several password prompts show up at the same time (as many as the parallel jobs configured), and even if the correct password is inserted, it will be rejected as wrong.

The workaround is to either override the parallel jobs parameter to 1, or to disable this feature from the configuration at all.

The bundler version is 1.10.6.

### PR DESCRIPTION
**Pull request by agis-**
Fixes #3910.

### CODE REVIEW

**Comment by indirect** [comment]
Thanks!

**Comment by segiddins** [comment]
@homu r+

**Comment by agis-** [comment]
@segiddins I've updated the patch to work on Ruby 1.8 also, so I guess you could cancel https://travis-ci.org/bundler/bundler/builds/76799207.

Sorry for the inconvenience! :)

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
