### PR TITLE
Fix exec_spec on ruby-head

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
Doesn't fix it. Looks like ruby-head somehow broke the specs the are in the default directory, as their `files` array is missing things compared to 2.4.1, which causes `require` not to activate the relevant gem when running `-ropenssl`

**Comment by segiddins** [comment]
i.e. `ruby -ropenssl -e 'puts Gem.loaded_specs["openssl"]'` used to yield an activated gem spec, on trunk it gives `nil`

**Comment by hsbt** [comment]
@segiddins I confirmed this regression. It caused by https://github.com/ruby/ruby/commit/5bca8051afc39c790e332fde3e4b653bbb41472a#diff-d5bb5873f6302f1ec09a2beeb04f5dee

I'm going to fix it on ruby-core.

**Comment by hsbt** [comment]
Fmm, gem installer of ruby core for default gems purged `Gem::Specification#files` and related entries same as https://github.com/rubygems/rubygems/commit/a1a5ab55cb1501cbfeee29131a56cfa2e763174f

I wonder why rubygems could not handle default gems that have no files entry. 

I continue to investigate it.

**Comment by segiddins** [comment]
Default specs are different, RubyGems doesn't re-write the default specifications that ruby serializes

**Comment by hsbt** [comment]
I reverted https://github.com/ruby/ruby/commit/83ea4017476333c0e0a44c9940cf4ff56f766279#diff-39ab32c5aeb56c9f5ae17f073ce31023

rubygems have specialized finder for default gems. https://github.com/rubygems/rubygems/blame/2.6/lib/rubygems.rb#L1219

After https://github.com/ruby/ruby/commit/cd8f9904427e6db858a4dcc1dabff60a76cad445, default gems have file entries same as ruby/ruby repository's one. Could you try it?

If It still have some issue, I will revert more commits.

**Comment by segiddins** [comment]
I restarted the ruby-head job on this PR. Thank you for helping us figure this out!

**Comment by segiddins** [comment]
Still failing

**Comment by hsbt** [comment]
>ruby 2.5.0dev (2017-04-18 trunk 58397) [x86_64-linux]

ruby-head onTravis has a lag time of latest build :(

**Comment by segiddins** [comment]
Using -04-20 `gem install` seemed to break https://travis-ci.org/bundler/bundler/jobs/222384129

**Comment by segiddins** [comment]
I can confirm that fixes the issue, thank you _so_ much @hsbt !

**Comment by segiddins** [comment]
@bundlerbot r+

**Pull request merged**
