### PR TITLE
Add output to bundle info to show the dependent gems

### LINKED ISSUE #6800: Add output to `bundle show <gemname>` to expose what other gems depend on <gemname>
@olivierlacan wrote a great article [here](https://olivierlacan.com/posts/why-wont-bundle-update/) in which he describes new functionality added to the `bundle-stats` gem, allowing you to understand why Bundler is telling you thing like this:

```
Bundler attempted to update nokogiri but its version stayed the same
```

The command behaves as follows:

```
$ bundle-stats versions nokogiri
bundle-stats for nokogiri

depended upon by (34):
+------------------------------|-------------------+
| Name                         | Required Version  |
+------------------------------|-------------------+
| capybara-screenshot          | >= 1.3.3          |
| capybara                     | >= 1.3.3          |
| loofah                       | >= 1.5.9          |
| rails-html-sanitizer         | >= 1.5.9          |
| coffee-rails                 | >= 1.6            |
| devise                       | >= 1.6            |
| formtastic                   | >= 1.6            |
| google-rails                 | >= 1.6            |
| haml-rails                   | >= 1.6            |
| prawn_rails                  | >= 1.6            |
| rails                        | >= 1.6            |
| rails-controller-testing     | >= 1.6            |
| rails-dom-testing            | >= 1.6            |
| xpath                        | ~> 1.3            |
| inline_svg                   | ~> 1.6            |
| chromedriver-helper          | ~> 1.6            |
| approvals                    | ~> 1.6            |
| html2haml                    | ~> 1.6.0          |
+------------------------------|-------------------+
```

There's a postscript at the end of the article that mentions a move to include this functionality in Bundler itself which would be great. I didn't see any issue/PR on this so far so I'm opening this one. Has any progress been made on this? I'd be happy to take a stab at it if I can find the time.

### PR DESCRIPTION
**Pull request by ankitkataria**
### What was the end-user problem that led to this PR?

Fixes #6800 
- adds functionality to show the dependent gems

### What is your fix for the problem, implemented in this PR?

- Replicated the functionality from `bundler-stats` gem using jmmastey/bundler-stats#1 as a reference as mentioned in the issue

### CODE REVIEW

**Comment by ankitkataria** [comment]
@segiddins Thanks for your comment! I've tweaked the current test a little. I added `rake` to the gemfile. Now when I do, `bundle info rake` It shows `rails`, pointing that `rails` has `rake` as a dependency. Let me know if anymore tests are required. :smile:

**Comment by ankitkataria** [comment]
The PR adds the following functionality to `info` command:
```
$ bundle info rspec-rails
  * rspec-rails (3.8.1)
    Summary: RSpec for Rails
    Homepage: https://github.com/rspec/rspec-rails
    Path: /Users/colby/.gem/ruby/2.5.1/gems/rspec-rails-3.8.1
        Dependents:
            foo (>= 1.0)
            bar (~> 2.0)
```

**Comment by ankitkataria** [comment]
Hey @segiddins! Is there anything left to be done here?

**Comment by colby-swandale** [comment]
Can you please add a test for multiple dependents, when there are no dependents

**Comment by colby-swandale** [comment]
Can you please also fix the alignment issue:

```
 Path: /Users/colby/.gem/ruby/2.5.1/gems/rspec-rails-3.8.1
        Dependents:
            foo (>= 1.0)
            bar (~> 2.0)
```

**Comment by deivid-rodriguez** [comment]
Closing in favor of https://github.com/bundler/bundler/pull/7314, which has apparently updated this PR, addressed some issues, and kept attribution for the initial work.

**Pull request closed without merging**
