### PR TITLE
Random test order

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This is a follow-up to the work started by @colby-swandale in #7103.

### What was the end-user problem that led to this PR?

The problem was that our specs do not run in random order, so the tests might be depending on state set by other tests to pass.

### What was your diagnosis of the problem?

My diagnosis was that we should enable random test ordering.

### What is your fix for the problem, implemented in this PR?

My fix is to randomize the specs and fix the resulting failures.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
This seems to be passing, but I'll run CI a couple more times to make sure it's reasonably stable.

**Comment by deivid-rodriguez** [comment]
I restarted CI one more time. If this passes, that would be the 3rd time in a row, plus the one by our bot, that would be 4 greens, which seems enough to me for getting this in.

So... let's see.

**Comment by deivid-rodriguez** [comment]
And yet another flaky surfaced... :sweat_smile:

**Comment by deivid-rodriguez** [comment]
Unless CI fails, this is good for a review now.

I also included changes to fix `bin/rspec --bisect` so we can easily fix flakies in the future. With the previous setup, it would just hang.

**Comment by deivid-rodriguez** [comment]
No reviews, but this should be good to go. Please tag me if you see any flakies :+1:.

@bundlerbot r+

**Comment by indirect** [comment]
omg amazing working bisect this is the best <3

**Comment by deivid-rodriguez** [comment]
First master build after this was merged failed, so I already need it :rofl:

**Pull request merged**
