### PR TITLE
Squash before merging for bors

### PR DESCRIPTION
**Pull request by fatkodima**
@hsbt 

https://bors.tech/documentation/

#7413

### CODE REVIEW

**Comment by hsbt** [comment]
I don't think we need to change it. 

@deivid-rodriguez Do you have any opinion?

**Comment by fatkodima** [comment]
Personally, I prefer to see all code changes for feature implementation in one place in one commit instead of spread across a wall of meaningless commits. It is then very hard to track and debug when and why something changes.

**Comment by hsbt** [comment]
> I prefer to see all code changes for feature implementation in one place in one commit

IMO, I don't think so.

**Comment by fatkodima** [comment]
How about this trash?

Screen Shot 2019-11-01 at 23 33 01

Screen Shot 2019-11-01 at 23 31 19

Screen Shot 2019-11-01 at 23 30 22

And 100500 similar commits without context.

**Comment by hsbt** [comment]
I have no feelings about that. 

And your comment is not respectable for the developer team of bundler.

**Pull request closed without merging**
