### PR TITLE
try using the new setup on travis

### PR DESCRIPTION
**Pull request by joshk**
- Super WIP
- Mostly testing if Travis will blend
- Watch this space

### CODE REVIEW

**Comment by indirect** [comment]
RVM is missing?

```
/home/travis/build.sh: line 282: /user/db: No such file or directory
0.01s$ rvm use 2.2 --install --binary --fuzzy
/home/travis/build.sh: line 41: rvm: command not found
```

**Comment by joshk** [comment]
Yeah, looks like the image isn't ready yet sorry. I'll update the PR when it is.

**Comment by indirect** [comment]
No problem. Thanks for your help with this! :grinning:

**Comment by segiddins** [comment]
@joshk it looks like the only change here is adding `sudo: 9000`, so I'm wondering why the diff is so large?

**Comment by joshk** [comment]
All I can say is that we are working on some secret sauce, and that is the switch for now, a temp switch.
Watch this space.

**Comment by segiddins** [comment]
That's fine, just wondering if there were actually any other changes :)

**Comment by segiddins** [comment]
I think we can close this now, thanks @joshk !

**Pull request closed without merging**
