### PR TITLE
Improve readability of outdated

### PR DESCRIPTION
**Pull request by tlynam**
Haven't fixed tests since wanted buy-in.

Before:

```
Outdated gems included in the bundle:
  * active_model_serializers (newest 0.9.5, installed 0.8.3, requested ~> 0.8.0) in group "default"
  * activerecord-import (newest 0.13.0, installed 0.10.0) in group "default"
  * addressable (newest 2.4.0, installed 2.3.5, requested = 2.3.5) in group "default"
  * airbrake (newest 5.2.3, installed 5.1.0) in group "default"
  * bootstrap-sass (newest 3.3.6, installed 3.3.5.1) in group "default"
  * capistrano (newest 3.5.0, installed 3.4.0, requested ~> 3.4) in group "development"
  * capistrano-rails (newest 1.1.6, installed 1.1.3, requested ~> 1.1.1) in group "development"
```

After:

```
--pretty
Outdated gems included in the bundle:
Gem Name                New        Installed  Requested  Groups
airbrake                5.3.0      5.0.3                 default
better_errors           2.1.1      1.0.1      ~> 1.0.1   development
bootstrap-sass          3.3.6      3.3.0.1    ~> 3.3.0.1 default
factory_girl_rails      4.7.0      4.4.1                 test, development

--pretty --verbose
Outdated gems included in the bundle:
Gem Name                New        Installed  Requested  Groups            Load Path
airbrake                5.3.0      5.0.3                 default           /Users/todd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/specifications/airbrake-5.3.0.gemspec
better_errors           2.1.1      1.0.1      ~> 1.0.1   development       /Users/todd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/specifications/better_errors-2.1.1.gemspec
bootstrap-sass          3.3.6      3.3.0.1    ~> 3.3.0.1 default           /Users/todd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/specifications/bootstrap-sass-3.3.6.gemspec
factory_girl            4.7.0      4.4.0                                   /Users/todd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/specifications/factory_girl-4.7.0.gemspec
factory_girl_rails      4.7.0      4.4.1                 test, development /Users/todd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/specifications/factory_girl_rails-4.7.0.gemspec
```

### CODE REVIEW

**Comment by segiddins** [comment]
I like this! Would it maybe make sense to justify all the different parts of the line as well?

**Comment by hmistry** [comment]
I think so. Something like below is what I'd like to see if possible. Removing all the repetitive labeling, removes clutter and makes it easier to read. 

```
Outdated gems included in the bundle:
  * Gem Name                   New      Installed   Requested    Group
  * active_model_serializers   0.9.5    0.8.3       ~> 0.8.0     "default"
  * activerecord-import        0.13.0   0.10.0                   "default"
  * addressable                2.4.0    2.3.5       = 2.3.5      "default"
  * airbrake                   5.2.3    5.1.0                    "default"
  * bootstrap-sass             3.3.6    3.3.5.1                  "default"
  * capistrano                 3.4.1    3.4.0       ~> 3.4       "development"
  * capistrano-rails           1.1.6    1.1.3       ~> 1.1.1     "development"
```

**Comment by segiddins** [comment]
Only issue with that is that it will break any automated parsing of the `--outdated` output, right?

**Comment by RochesterinNYC** [comment]
Well, maybe we should be encouraging people to use `bundle outdated --parseable` for automated parsing? Though, we'd have to decide whether that output would stay the same or get formatted the same as here.

**Comment by hmistry** [comment]
because it's not CSV formatted? It's possible. We can add the comma's in to help with that but it will require a little mod to their script. Alternatively, it could be a `--outdated-prettyformat` option.

**Comment by segiddins** [comment]
No, not that its not CSV, but rather because that header line has the same format as an outdated gem line

**Comment by RochesterinNYC** [comment]
If we make it an alternative option/something that needs to be specified via flags, I don't think it'll see much use. 

Ideally, it'd be nice to shore up and focus `bundle outdated` on producing pleasing human-readable output while ensuring `bundle outdated --parseable` maintains an automatically parseable format might be a good resolution. However, after looking around Github at some repos, I think the original output (ex. `* active_model_serializers (newest 0.9.5, installed 0.8.3, requested ~> 0.8.0) in group "default"`) might be as far as we might consider changing the output to. Even then, it seems that we might be breaking some people's usages/parsing of `bundle outdated`. 

Alternatively, this could be a PR/change to Bundler 2.0? In which case, breaking the interface/format is acceptable?

**Comment by hmistry** [comment]
@segiddins Ah! I see. It's an easy thing to fix either do all caps or wrap them in parentheses or ... depends if we decide to go this route.

@RochesterinNYC Agree, breaking changes like this is better done in major version upgrades. My thoughts on the flag option is it's ok to have low usage in the beginning as it will take time for awareness and adoption/user change. What's more important is to hear their feedback and see rate of adoption, though for a command utility it's harder than it is for a website.

**Comment by phiggins** [comment]
Is there any reason to keep the sorting based on the group, rather than the gem name?

When I use `bundle outdated`, I typically scan the output to see if a gem or set of gems is listed, and the list being sorted by group is not the most helpful way it could be. I'd suggest sorting the list based on the name of the gem.

**Comment by RochesterinNYC** [comment]
Grouping by Gemfile groups, then by sub-dependencies (dependencies of the explicitly named dependencies in the Gemfile), is more logical than having an alphabetical list of gems as it can get confusing which type of gem dependency you're looking at. Additionally, from what I've seen in terms of `bundle outdated` usage, many users choose to be more stringent about updates for certain groups (ex. `production` rather than `testing`).

**Comment by phiggins** [comment]
I can only speak for myself, but I find the current output very confusing. The only times I've ever used `bundle outdated` was to find out if a gem or set of gems had newer versions available, and the current output is not useful for that.

I felt obligated to add my two cents because I put @tlynam up to this in the first place. I'll respect whatever decisions are made by the project maintainers and I promise I won't belabor the point.

**Comment by tlynam** [comment]
Could we support both use cases?  What do you think if there were a --grouped option as a type of sorting?  Do you think it could be confusing to read a list if there were several group combinations?  Looking through our gemfile we have
`test, development, staging`
`test, development`
`test`
`development`
If it were pre-grouped, I think there could be a high chance someone would still need to play with the output if they were trying to isolate certain environments.

**Comment by indirect** [comment]
To be honest, I'm also confused by the way outdated prints an undifferentiated list that isn't in alphabetical order. I think might make sense if it did it in a hierarchical way, maybe like this:

```
Outdated gems in the default group:
  rack-obama (newest 0.1.1, installed 0.1.0, requested 0.1.0)
    rack (newest 1.6.3, installed 1.2.1, requested ~> 1.2.0)
```

But given the way that it prints now, I think alphabetizing the list would actually make a lot of sense. I also like the tabular output, and I think adding a `--parseable` output to outdated that prints in some easily computer-parsable format like TSV or CSV make a lot of sense.

To be fully backwards-compatible, we could alphabetize the current output, add `--parseable` with TSV output, and plan to change the regular output to something tabular in 2.0. How does everyone feel about that?

**Comment by phiggins** [comment]
> To be fully backwards-compatible, we could alphabetize the current output, add --parseable with TSV output, and plan to change the regular output to something tabular in 2.0. How does everyone feel about that?

Sounds good to me. :+1:

**Comment by hmistry** [comment]
I agree with that.

**Comment by booch** [comment]
We could keep the current output format if `STDOUT` is a pipe, and print the pretty output if we're running it interactively, or if `--pretty` is specified.

**Comment by tlynam** [comment]
What do you think of this?  This alphabetizes the current default.  We already have a `parseable` option so I added `pretty`.  It uses offsets and works with `verbose`.

```
--pretty
Outdated gems included in the bundle:
Gem Name                New        Installed  Requested  Groups
airbrake                5.3.0      5.0.3                 default
better_errors           2.1.1      1.0.1      ~> 1.0.1   development
bootstrap-sass          3.3.6      3.3.0.1    ~> 3.3.0.1 default
factory_girl_rails      4.7.0      4.4.1                 test, development

--pretty --verbose
Outdated gems included in the bundle:
Gem Name                New        Installed  Requested  Groups            Load Path
airbrake                5.3.0      5.0.3                 default           /Users/todd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/specifications/airbrake-5.3.0.gemspec
better_errors           2.1.1      1.0.1      ~> 1.0.1   development       /Users/todd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/specifications/better_errors-2.1.1.gemspec
bootstrap-sass          3.3.6      3.3.0.1    ~> 3.3.0.1 default           /Users/todd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/specifications/bootstrap-sass-3.3.6.gemspec
factory_girl            4.7.0      4.4.0                                   /Users/todd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/specifications/factory_girl-4.7.0.gemspec
factory_girl_rails      4.7.0      4.4.1                 test, development /Users/todd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/specifications/factory_girl_rails-4.7.0.gemspec
```

**Comment by hmistry** [comment]
Nice! I really like that. 👍 

Check with @segiddins if he wishes to differentiate the title row for easy parsing as he raised a concern earlier about the title row being similar to a table row.

**Comment by phiggins** [comment]
This looks awesome @tlynam!

**Comment by chrismo** [comment]
Welp. @tlynam - we just approved a PR to add grouping to this command (#4841) and left this one behind. :| I'm sure it was unintentional, lots of PRs and Issues and only so much time. 

That said, your proposed changes still seem relevant if you'd like to rebase this.

**Comment by tlynam** [comment]
Thanks @chrismo, I'll work on improving this :)

**Comment by tlynam** [comment]
I rewrote this, please let me know how it can be improved, thanks! :)

**Comment by chrismo** [comment]
thx @tlynam. if someone else can get to it before me, cool - imma having a very busy week that doesn't include any time for bundler :/ 

feel free to ping me or us on this PR if we neglect you too long, I don't mind the reminders :)

**Comment by tlynam** [comment]
Thanks @chrismo, I completely understand :)

**Comment by tlynam** [comment]
Howdy @chrismo, I got some help separating the logic.  Please let me know how else it can be improved!  What do you think of making this the default output when running `outdated`?

**Comment by hmistry** [comment]
Here's `npm outdated` output. It looked really nice and simple to me but now that I see this thread, ours may not be as simple... posted it for inspiration purposes whether its today or in the future.

screen shot 2016-12-14 at 11 03 54 am

**Comment by tlynam** [comment]
Thanks @hmistry, that looks great!

Here's what it could look like.  Should we try to merge this before adding color or just go with color?
image

**Comment by hmistry** [comment]
@tlynam That looks really nice. I'd make one change to it and that is, change the red to the normal text color so the installed version is not emphasized visually. I believe the highest focus of output should be the New version so having it green is good and then followed by Requested so the lighter blue is a good choice as it's not as strong as the green. Let everything else be normal text color so the user is not visually distracted with too many colorful bits of information.

However to your question, I recommend getting this merged first without color so you there's consensus on this. Then after the merge, add the color... baby steps. 😃

**Comment by segiddins** [comment]
This is failing rubocop

**Comment by tlynam** [comment]
Thanks, the rubocop issues are fixed.  Can we make this the `oudated` default as it's a lot easier to read?

**Comment by segiddins** [comment]
@chrismo this PR is still assigned to you -- is there anything else you needed done before reviewing it?

**Comment by colby-swandale** [comment]
ping @chrismo

**Comment by deivid-rodriguez** [comment]
I plan to rebase and get this PR ready to merge next. Something I wonder is whether we actually need the `--pretty` option. I mean, we already have the `--parseable` option, and I think that's the only mode where we should respect an output contract. Since this formatting is arguably better than the current one, can we change the output formatting instead?

**Comment by indirect** [comment]
I agree 🙂

**Comment by deivid-rodriguez** [comment]
I rebased this PR, fixed several issues, tweaked a few things, and implemented the mentioned change of changing the default output except for the `--parseable` option.

The following is an example using the current version of this PR:

#### bundle outdated --parseable (output unchanged)

```
apparition (newest 0.4.0, installed 0.3.0, requested = 0.3.0)
aws-partitions (newest 1.220.0, installed 1.217.0)
capistrano (newest 3.11.2, installed 3.11.1)
carrierwave (newest 2.0.2, installed 2.0.1, requested ~> 2.0)
dependabot-bundler (newest 0.113.7, installed 0.112.35)
dependabot-cargo (newest 0.113.7, installed 0.112.35)
dependabot-common (newest 0.113.7, installed 0.112.35)
dependabot-composer (newest 0.113.7, installed 0.112.35)
dependabot-dep (newest 0.113.7, installed 0.112.35)
dependabot-docker (newest 0.113.7, installed 0.112.35)
dependabot-elm (newest 0.113.7, installed 0.112.35)
dependabot-git_submodules (newest 0.113.7, installed 0.112.35)
dependabot-github_actions (newest 0.113.7, installed 0.112.35)
dependabot-go_modules (newest 0.113.7, installed 0.112.35)
dependabot-gradle (newest 0.113.7, installed 0.112.35)
dependabot-hex (newest 0.113.7, installed 0.112.35)
dependabot-maven (newest 0.113.7, installed 0.112.35)
dependabot-npm_and_yarn (newest 0.113.7, installed 0.112.35)
dependabot-nuget (newest 0.113.7, installed 0.112.35)
dependabot-omnibus (newest 0.113.7, installed 0.112.35, requested = 0.112.35)
dependabot-python (newest 0.113.7, installed 0.112.35)
dependabot-terraform (newest 0.113.7, installed 0.112.35)
erubi (newest 1.9.0, installed 1.8.0)
excon (newest 0.67.0, installed 0.66.0)
factory_bot (newest 5.1.0, installed 5.0.2)
factory_bot_rails (newest 5.1.0, installed 5.0.2, requested ~> 5.0)
faraday (newest 0.16.2, installed 0.15.4)
http-accept (newest 2.1.1, installed 1.7.0)
loofah (newest 2.3.0, installed 2.2.3)
minitest (newest 5.12.2, installed 5.11.3)
nio4r (newest 2.5.2, installed 2.5.1)
rake (newest 13.0.0, installed 12.3.3)
rubocop (newest 0.75.0, installed 0.72.0, requested = 0.72.0)
rubocop-rspec (newest 1.36.0, installed 1.35.0, requested ~> 1.35)
rubyzip (newest 2.0.0, installed 1.2.4, requested ~> 1.2)
simple_form (newest 5.0.0, installed 4.1.0, requested ~> 4.1)
tilt (newest 2.0.10, installed 2.0.9)
tzinfo (newest 2.0.0, installed 1.2.5)
uglifier (newest 4.2.0, installed 4.1.20, requested ~> 4.1)
webmock (newest 3.7.6, installed 3.7.5, requested ~> 3.7)
```

#### bundle outdated (new table format)

```
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.....

Gem                        Locked    Latest   Requested   Groups
apparition                 0.3.0     0.4.0    = 0.3.0     test
aws-partitions             1.217.0   1.220.0
capistrano                 3.11.1    3.11.2
carrierwave                2.0.1     2.0.2    ~> 2.0      default
dependabot-bundler         0.112.35  0.113.7
dependabot-cargo           0.112.35  0.113.7
dependabot-common          0.112.35  0.113.7
dependabot-composer        0.112.35  0.113.7
dependabot-dep             0.112.35  0.113.7
dependabot-docker          0.112.35  0.113.7
dependabot-elm             0.112.35  0.113.7
dependabot-git_submodules  0.112.35  0.113.7
dependabot-github_actions  0.112.35  0.113.7
dependabot-go_modules      0.112.35  0.113.7
dependabot-gradle          0.112.35  0.113.7
dependabot-hex             0.112.35  0.113.7
dependabot-maven           0.112.35  0.113.7
dependabot-npm_and_yarn    0.112.35  0.113.7
dependabot-nuget           0.112.35  0.113.7
dependabot-omnibus         0.112.35  0.113.7  = 0.112.35  development
dependabot-python          0.112.35  0.113.7
dependabot-terraform       0.112.35  0.113.7
erubi                      1.8.0     1.9.0
excon                      0.66.0    0.67.0
factory_bot                5.0.2     5.1.0
factory_bot_rails          5.0.2     5.1.0    ~> 5.0      tools
faraday                    0.15.4    0.16.2
http-accept                1.7.0     2.1.1
loofah                     2.2.3     2.3.0
minitest                   5.11.3    5.12.2
nio4r                      2.5.1     2.5.2
rake                       12.3.3    13.0.0
rubocop                    0.72.0    0.75.0   = 0.72.0    tools
rubocop-rspec              1.35.0    1.36.0   ~> 1.35     tools
rubyzip                    1.2.4     2.0.0    ~> 1.2      default
simple_form                4.1.0     5.0.0    ~> 4.1      default
tilt                       2.0.9     2.0.10
tzinfo                     1.2.5     2.0.0
uglifier                   4.1.20    4.2.0    ~> 4.1      default
webmock                    3.7.5     3.7.6    ~> 3.7      test
```

**Comment by indirect** [comment]
I like it, especially for gems that are grouped together, like dependabot or aws 👍🏻

**Comment by deivid-rodriguez** [comment]
I'm thinking using "Current" for the table header is probably better than "Locked"?

**Comment by hmistry** [comment]
@deivid-rodriguez The output looks great! "Current" is better than "Locked". Looking forward to seeing this in bundler. 🙂

**Comment by deivid-rodriguez** [comment]
I'll merge this in tomorrow if there's no further feedback.

**Comment by deivid-rodriguez** [comment]
@bundlerbot r+

**Pull request merged**
