### PR TITLE
No longer use gemcutter. Update to rubygems.org

### PR DESCRIPTION
**Pull request by dsisnero**

### CODE REVIEW

**Comment by segiddins** [comment]
You also need to update the tests: https://travis-ci.org/bundler/bundler/jobs/50557995#L2108

**Comment by indirect** [comment]
also, the `:gemcutter` symbol maps to `rubygems.org` already.

**Comment by TimMoore** [comment]
Unfortunately, `:gemcutter` maps to `http://rubygems.org` and not `https` (and gives a deprecation warning).

I think we should make this change and fix the tests.

**Comment by indirect** [comment]
:+1:

**Comment by TimMoore** [comment]
er... it isn't obvious from how GitHub formats this, but I fixed the test in the merge commit

**Pull request merged**
