### PR TITLE
Fix Rubocop offenses

### PR DESCRIPTION
**Pull request by esasse**

### CODE REVIEW

**Comment by esasse** [comment]
@indirect I've squashed that commit like you asked.

**Comment by indirect** [comment]
After merging all your other fixes, I think this either needs to be rebased or just --auto-correct'ed again. Thanks for all your work on this!

**Comment by esasse** [comment]
I think you should be able to merge now. I haven't used rebased that much, so I hope I'm doing it right. :smile:

**Comment by indirect** [comment]
:+1:

**Pull request merged**
