### PR TITLE
Add a setting for disable_exec_load

### PR DESCRIPTION
**Pull request by segiddins**
See #4852

### CODE REVIEW

**Comment by indirect** [comment]
Hmmm I was actually thinking of a flag on `exec`, like `exec --no-load`. This is good too, though. Document this setting in `man/bundle_config` and I think this is good!

**Comment by segiddins** [comment]
I personally prefer settings to flags for things that are rarely needed

**Comment by indirect** [comment]
I was thinking of the flag for the use case where one particular command only works with load disabled, but you don't want to lose the performance improvements generally. But shipping a setting seems fine for now, you can do a one-off using env.

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
