### PR TITLE
Add OpenSSL::OPENSSL_VERSION to `bundle env`

### PR DESCRIPTION
**Pull request by chrismo**

### CODE REVIEW

**Comment by segiddins** [comment]
OpenSSL need not be installed

**Comment by chrismo** [comment]
True. Git and RVM aren't requirements - I thought adding this might help for troubleshooting common https cases.

**Comment by segiddins** [comment]
My point was more that we need to handle the `OpenSSL` module not being defined.

**Comment by chrismo** [comment]
Ah, I misunderstood - makes sense.

**Comment by indirect** [comment]
@chrismo @segiddins could one of you patch this up so we can merge it? I think this would be really valuable for debugging purposes.

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
Sorry @chrismo, I didn't see you'd rebased this

**Comment by chrismo** [comment]
no worries, you've been busy :)

**Pull request merged**
