### PR TITLE
Fixed missing constant with rubygems integration

### LINKED ISSUE #5000: V1.13.1 breaks passenger compile-agent
After installing 1.3.1 I'm no longer able to compile-agent with passenger (5.0.30), if I revert back to 12.5.0 it compiles just fine.

[root@callisto]# passenger-config compile-agent
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API (NameError)
Did you mean?  Bundler::Plugin::API
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:41:in `contains_requirable_file?'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:67:in `each'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:67:in `find'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:67:in `require'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1328:in `block in add_self_to_load_path'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1327:in `map'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1327:in `add_self_to_load_path'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1240:in `activate'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1271:in `block in activate_dependencies'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1257:in `each'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1257:in `activate_dependencies'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1239:in `activate'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/passenger-config:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

### PR DESCRIPTION
**Pull request by hsbt**
Fixes #5000.

I got uninitialized constant error with bundler-1.13.1 on travis. see https://travis-ci.org/ruby/rake/jobs/159734476

It's reproduce my local box with ruby/rake testing. I simply fixed this error.

Thank you.

### CODE REVIEW

**Comment by hsbt** [comment]
failing result https://travis-ci.org/bundler/bundler/jobs/159755964 seems not related this change. Can you retry it?

**Comment by indirect** [comment]
Restarted the failing build.

**Comment by hsbt** [comment]
@indirect ❤️

**Comment by segiddins** [comment]
Is there any way to add a test? What's the constant being referenced?

**Comment by hsbt** [comment]
> Is there any way to add a test?

It's hard way to add test. Because bundler has no test with `rubygems_ext.rb` standalone.

> What's the constant being referenced?

It's `Bundler::Plugin::API::Source`.

**Comment by aycabta** [comment]
The reason of this problem is `autoload` for the namespaces at [`Bundler::Plugin`](https://github.com/bundler/bundler/blob/c71f43fbcb9ee25bc4466137cc29545cda1375e2/lib/bundler/plugin.rb#L5-L9) and [a deeper than `Bundler::Plugin`](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=path%3Alib%2Fbundler%2Fplugin+autoload&type=Code). In this case, I think that those `autoload` should be removed and use `require` like this Pull Request because the same error will occur when we newly add `require` for other modules that are `autoloaded`-ed.

I sent [workaround Pull Request with explanation](https://github.com/bundler/bundler/pull/4973) before this, but it's bad. Because it doesn't resolve the problem of `autoload`. I think this (#4981) Pull Request is still workaround a littile, but better than mine.

Why does [Bundler use `autoload` a lot](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=autoload&type=Code)? Is there a problem when `autoload` are removed?

**Comment by segiddins** [comment]
Why isn't the autoload working here, @asutoshpalai ?

**Comment by hsbt** [comment]
I added workaround to ruby/rake :(

https://github.com/ruby/rake/pull/161/commits/2d7668d00f2aea67e813e7279717b2db40301cdb

**Comment by indirect** [comment]
@hsbt I am very worried we will accidentally break this again without a test. do you have any ideas how we can test this?

@aycabta is it possible to fix this by removing autoload from `lib/bundler/plugin/api.rb` and using `require 'bundler/plugin/api/source'` instead?

**Comment by hsbt** [comment]
@indirect @segiddins I understood your concerns. I try to code minimum reproduction case.

**Comment by aycabta** [comment]
Sorry for rough presentation... this problem is difficult to solid discussion.

```ruby
require 'bundler/gem_tasks'
require 'rdoc'

task default: nil
```

This `Rakefile` with Bundler 1.13.1 can occur the error. The `require 'rdoc'` must be `require 'rdoc'`. If `require 'json'` instead of it is used, `Rakefile` will success. I don't understand why.

**Comment by aycabta** [comment]
@indirect Yes, it is. I made sure of it. But I think that it may be still workaround, because I don't understand what is real problem.

**Comment by aycabta** [comment]
I created [a branch that uses `require` instead of `autoload`](https://github.com/aycabta/bundler/tree/use-require-instead-of-autoload-for-plugin-api). This [has a commit](https://github.com/aycabta/bundler/commit/4c32972d9bd35971f2f55c7ec96fa6d0a1f1a372). You can use this to test:

```
git clone git@github.com:aycabta/bundler.git bundler_test_branch && cd bundler_test_branch
mkdir 4981 && cd 4981
printf "require 'bundler/gem_tasks'\nrequire 'rdoc'\n\ntask default: nil\n" > Rakefile
printf "Gem::Specification.new do |s|\n  s.name = 'test'\nend\n" > test.gemspec
git checkout v1.13.1
rake -I../lib --trace # fail <========
git checkout use-require-instead-of-autoload-for-plugin-api
rake -I../lib --trace # success < ========

**Comment by segiddins** [comment]
@asutoshpalai ping?

**Comment by asutoshpalai** [comment]
I have been trying to reproduce this locally for some time with no success.

But from what I can infer (and I believe is known to everyone in the discussion) from the proposed fixes, I can say that autoloading `Plugin::API::Source` is failing because there is a cycle in the function calls.

When [`rubygems_ext.rb#Gem::full_gem_path`](https://github.com/bundler/bundler/blob/03633e15bfb4763ab7015f4abe6ca4ec1938d759/lib/bundler/rubygems_ext.rb#L45) is being called for first time, it is trying to load `bundler/plugin/api/source.rb`. This file, in turn, tries to [`require uri`](https://github.com/bundler/bundler/blob/03633e15bfb4763ab7015f4abe6ca4ec1938d759/lib/bundler/plugin/api/source.rb#L2) which somehow leads to `rubygems_ext.rb#Gem::full_gem_path` being called again. And this is the cause of the crash. (This inference is from this PR and #4973)

As for the fixes, I think we should go with aycabta/bundler@4c32972d .

But it's elusive reproduction (and lack of test case) makes me think that the problem is a bit deeper and may recur.

**Comment by aycabta** [comment]
I tentatively created Pull Request with https://github.com/aycabta/bundler/commit/4c32972d: https://github.com/bundler/bundler/pull/5010.

**Comment by aycabta** [comment]
@asutoshpalai said:

> As for the fixes, I think we should go with aycabta/bundler@4c32972.

and I created https://github.com/bundler/bundler/pull/5010 with aycabta/bundler@4c32972. For the last time, it was merged.

I think this problem is not clearly solved. #5010 is just workaround. But this problem will not presumably occur again because [`rubygems_ext.rb#Gem::full_gem_path`](https://github.com/bundler/bundler/blob/03633e15bfb4763ab7015f4abe6ca4ec1938d759/lib/bundler/rubygems_ext.rb#L45) what is the cause of a cycle in the function calls uses only `Bundler::Plugin::API::Source`. #5010 solves it.

**Comment by hsbt** [comment]
I will confirm reproduction of this issue after bundler-1.13.3 release contained https://github.com/bundler/bundler/pull/5010

**Comment by hsbt** [comment]
I confirmed to fix this with bundler-1.13.3. ref. https://github.com/ruby/rake/pull/168

**Comment by lynnco** [comment]
@hsbt bundler-1.13.3 was a [single change](https://github.com/bundler/bundler/compare/v1.13.2...v1.13.3) release to deal with some rubygems.org server issues. #5010 (and the rest of the planned 1.13.3 changes) is going to go out in bundler-1.13.4

Although if your issue is fixed, then that's great

**Comment by hsbt** [comment]
@lynnco Thanks your information. Maybe my issue was solved by Travis environment. I reopen or submit new issue when I got same error.

**Pull request closed without merging**
