### PR TITLE
Support :mri_25 platform and its variations

### PR DESCRIPTION
**Pull request by amatsuda**
The next ruby version is decided to be 2.5 🎉  https://github.com/ruby/ruby/commit/1a47fcadd675601c5b9c4e69d49def28fc3b61af

I'm not requesting you the bundler team to rush for a new release for this, but I guess it's not too early to have this definition in master.

### CODE REVIEW

**Comment by segiddins** [comment]
@bundlerbot r+

Beat me to it! We should come up with a more dynamic way of doing this eventually, though.

**Comment by segiddins** [comment]
We also need to update `CurrentRuby` to include 2.5 as a known patch version

**Comment by segiddins** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
@bundlerbot retry

**Comment by segiddins** [comment]
@bundlerbot retry 

ugh this is getting annoying, sorry for the spam

**Comment by amatsuda** [comment]
@segiddins Thank you!

**Pull request merged**
