### PR TITLE
Simplified Gemfile template

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Comment by indirect** [comment]
@segiddins can you chime in on the frozen string comment? Since Gemfiles are ultimately processed by `instance_eval`, I'm pretty sure we don't actually need the comment, right?

**Comment by segiddins** [comment]
@indirect I'd rather have the comment, I'm pretty sure it is taken into account, and will help people when migrating to ruby 3 or using the frozen string literal ruby opts

**Comment by KrauseFx** [comment]
So should I close this PR? 
I wonder if we can delete the `# A sample Gemfile` still?

**Comment by indirect** [comment]
I am fine with deleting `# A sample Gemfile`. I'm also pretty sure that `instance_eval` does not respect magic comment strings. If someone can figure that out one way or another, we'll know whether we need it in the template.

**Comment by segiddins** [comment]
@indirect i verified yesterday that eval does indeed respect the magic string comment

**Comment by indirect** [comment]
Closing this for now, but if you still want to delete the sample gemfile line feel free to update this PR and let us know.

**Comment by KrauseFx** [comment]
@indirect awesome, thanks: https://github.com/bundler/bundler/pull/4880

**Pull request closed without merging**
