### PR TITLE
Add alias `Bundler::SpecSet#size` for `Bundler::SpecSet#length`

### LINKED ISSUE #4368: Rubygems 2.6.2 Calls undefined method `size` on `Bundler::SpecSet`
I have some code that does `Gem::Specification.find_by_name(@gem_name_for_base_dir)`. When I run this with rubygems 2.6.2, some code internal to rubygems calls `#size` on a `Bundler::SpecSet` object, resulting in 

```
NoMethodError: undefined method `size' for #<Bundler::SpecSet:0x007f879baa2d08>
 /Users/ddeleo/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:310:in `to_specs'
 /Users/ddeleo/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:330:in `to_spec'
 /Users/ddeleo/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1028:in `find_by_name'
```

(I've trimmed the rest of the stack trace as I think it's not relevant to you).

I noticed that `Bundler::SpecSet` does define `#length`, and aliasing this method as size seems to resolve my issue.

### PR DESCRIPTION
**Pull request by RochesterinNYC**
- Closes #4368

### CODE REVIEW

**Comment by segiddins** [comment]
Please add a spec?

**Comment by RochesterinNYC** [comment]
Hm, doesn't seem like we have a unit spec for `Bundler::SpecSet`? Guess I'll take a look at adding one.

**Comment by segiddins** [comment]
`undefined method `length' for class `Bundler::SpecSet'`

**Comment by RochesterinNYC** [comment]
Yeah I'll have to take a deeper look at this later tonight. Got any context on why there's no unit spec?

**Comment by segiddins** [comment]
just move the alias after the `def_delegator` lines

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu retry

**Comment by danielsdeleo** [comment]
Thank you! :100:

**Comment by PierreR** [comment]
@homu The fix didn't land on `1.12.5`. Will it be included in a stable release soon ?

**Comment by segiddins** [comment]
This is in the 1.13 release candidates

**Comment by PierreR** [comment]
@segiddins well sure, but as long as it is a RC it won't ship in `nix/nixos` ... I actually need to use `librarian-puppet` from nix but it won't work because of this issue.

**Pull request merged**
