### PR TITLE
Dependency review

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was that we were using some outdated test dependencies.

### What was your diagnosis of the problem?

My diagnosis was that we can upgrade them, since the comments justifying them being pinned are no longer relevant.

### What is your fix for the problem, implemented in this PR?

My fix is to unpin the dependencies, and remove the comments no longer applying.

### Why did you choose this fix out of the possible options?

I chose this fix because it was the only fix I could think of.

### CODE REVIEW

**Comment by segiddins** [comment]
I think we should be able to use rack 2 now?

**Comment by deivid-rodriguez** [comment]
According to the comment I left in there, the version of the `artifice` gem we're using does not support it...

**Comment by segiddins** [comment]
Ah sorry I didn’t see that

@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
Thanks for reviewing @segiddins!

**Pull request merged**
