### PR TITLE
Eval Gemfiles one fewer time when running `bundle install`

### PR DESCRIPTION
**Pull request by segiddins**
This is just a straight port of https://github.com/bundler/bundler/pull/4952 to master from `2-0-dev`.
Unfortunately, the Gemfile is still eval'ed twice when plugins are enabled.

### CODE REVIEW

**Comment by indirect** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
@jules2689 this might also help perf, but I'm not sure

**Comment by jules2689** [comment]
Hrm, I can't actually run master right now due to https://github.com/bundler/bundler/pull/5701#issuecomment-308926849

**Comment by jules2689** [comment]
Including a fix for the issue I noted above, I got 375-389ms on master and 369-381ms using Shopify's core application for `require 'bundler/setup'`, so there is definitely about 6-10ms of savings here. I'd just like to also note that this number used to be basically a full second - this is great :D

**Comment by segiddins** [comment]
@bundlerbot retry

**Pull request merged**
