### PR TITLE
Distinguish Gemfile syntax and evaluation errors

### LINKED ISSUE #3783: Gemfile friendly error should allow ruby requirement exceptions
The new friendly Gemfile error handler mistakenly treats exceptions raised from the Ruby version checker as if they are syntax errors or something similar:

```
[!] There was an error parsing `Gemfile`: ruby_version must match the :engine_version for MRI. Bundler cannot continue.
 #  from /home/travis/build/bundler/bundler/tmp/bundled_app/Gemfile:2
 #  -------------------------------------------
 #  source "file:///home/travis/build/bundler/bundler/tmp/gems/remote1"
 >  ruby "1.8.7", :engine => 'ruby', :engine_version => '1.2.4'
 #  
 #  -------------------------------------------
```

This happens during the spec named "raises an error if engine version doesn't match ruby version for MRI", among others.

Instead, we should simply treat the exception as a normal friendly error, and print the message out in red and exit non-zero.

### PR DESCRIPTION
**Pull request by agis-**
Fixes #3783.

### CODE REVIEW

**Comment by indirect** [comment]
This would probably be easier as `GemfileParseError` and `GemfileEvalError`, that way you wouldn't have to check on strings all over the place. :)

**Comment by agis-** [comment]
Sounds better indeed (I just wasn't sure we want to introduce more
exception classes). I will update this tomorrow :)

**Comment by agis-** [comment]
@indirect You mean something like:

```ruby
class GemfileEvalError < GemfileError; end
class GemfileParseError < GemfileError; end
```

and then in `RubyDsl#ruby`:

```ruby
raise GemfileEvalError, "There was an error evaluating etc. etc."
```

And then update the other places in `RubyDsl#ruby` accordingly?

**Comment by indirect** [comment]
You could probably even only add GemfileEvalError < GemfileError, and then use it when needed.

**Comment by agis-** [comment]
@indirect updated :)

**Comment by segiddins** [comment]
:+1:

**Comment by indirect** [comment]
thanks! @homu r+

**Pull request merged**
