### PR TITLE
Fix Style/AlignParameters

### PR DESCRIPTION
**Pull request by esasse**

### CODE REVIEW

**Comment by indirect** [comment]
I really dislike this change :( Can we make rubocop enforce a single indent instead?

**Comment by esasse** [comment]
"Yes, we can!"
And it's done! :smile:

**Comment by indirect** [comment]
Seems less bad to me. :) Thanks! @homu r+

**Comment by esasse** [comment]
Same git checkout issue here as in #3889. Any ideas?

**Pull request merged**
