### PR TITLE
Fix sorting of mixed DependencyLists with RubyGems >= 2.23

### LINKED ISSUE #3762: Bundler 1.10.1 breaks Rails 2.3.x plugin-loading
I appreciate that this might not be a bug in Bundler per se, but it's exasperating for those of us who still maintain Rails 2 apps, so I thought I'd report it and see if there's any advice on a workaround.

It seems that Rails 2 calls `Gem::DependencyList#dependency_order` while locating gems that host a plugin. This method does not appear to be deprecated, or at least the [stdlib docs](http://ruby-doc.org/stdlib-2.1.6/libdoc/rubygems/rdoc/Gem/DependencyList.html#method-i-dependency_order) for Ruby 2.1.6 don't mention it. However, it results in an exception (see backtrace below).

Any advice on how to overcome this would be greatly appreciated; I'd hate to be locked into using an older Bundler version. If there's a more modern, supported way to sort specs in dependency order, then I'll be happy to monkey-patch that into my app.

```
    $ bundle exec script/console
    Loading development environment (Rails 2.3.18)
    /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/dependency_list.rb:214:in `sort': comparison of Bundler::StubSpecification with Gem::Specification failed (ArgumentError)
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/dependency_list.rb:214:in `tsort_each_child'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tsort.rb:411:in `call'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/dependency_list.rb:210:in `each'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/dependency_list.rb:210:in `tsort_each_node'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tsort.rb:345:in `call'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tsort.rb:280:in `strongly_connected_components'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tsort.rb:255:in `strongly_connected_components'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/dependency_list.rb:75:in `dependency_order'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-2.3.18/lib/rails/plugin/locator.rb:94:in `plugins'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-2.3.18/lib/rails/plugin/loader.rb:109:in `block in locate_plugins'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-2.3.18/lib/rails/plugin/loader.rb:108:in `map'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-2.3.18/lib/rails/plugin/loader.rb:108:in `locate_plugins'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-2.3.18/lib/rails/plugin/loader.rb:32:in `all_plugins'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-2.3.18/lib/rails/plugin/loader.rb:22:in `plugins'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-2.3.18/lib/rails/plugin/loader.rb:53:in `add_plugin_load_paths'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-2.3.18/lib/initializer.rb:294:in `add_plugin_load_paths'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-2.3.18/lib/initializer.rb:136:in `process'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-2.3.18/lib/initializer.rb:113:in `run'
    	from /Users/tony/Code/rails23-bundler-bug/config/environment.rb:100:in `<top (required)>'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/irb/init.rb:286:in `require'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/irb/init.rb:286:in `block in load_modules'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/irb/init.rb:284:in `each'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/irb/init.rb:284:in `load_modules'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/irb/init.rb:20:in `setup'
    	from /Users/tony/.rbenv/versions/2.1.6/lib/ruby/2.1.0/irb.rb:380:in `start'
    	from /Users/tony/.rbenv/versions/2.1.6/bin/irb:11:in `<main>'
```

### PR DESCRIPTION
**Pull request by tony-spataro-rs**
Closes #3762

### CODE REVIEW

**Comment by indirect** [comment]
Thanks for the pull request! We actually want to do this on the 1-10-stable branch, so that we can release it in the next 1.10.x bugfix release. I added the patch and the test in this commit: 3f4f6286c56765e8c4968631643106cfd534b789.

**Comment by indirect** [comment]
Annnnd now that I've read your pull request, it's much better than my patch. I'll cherry-pick this onto the `1-10-stable` branch. :)

**Comment by tony-spataro-rs** [comment]
:+1: Thanks once again for being prompt and responsive! I'm glad I could contribute to the 2nd most vital piece of Ruby software in existence (beyond RubyGems itself..)

**Comment by indirect** [comment]
Cherry-picked as e5d936e7c6265f8f8dcdd7fcc4b93aeb013acbd1. Thanks again!

**Pull request closed without merging**
