### PR TITLE
Refactor path/environment preserver, make it always preserve the PATH

### LINKED ISSUE #4251: bundle exec's "with_original_env" doesn't preserve PATH
I'm looking for a way to restore the original environment PATH inside a ruby script executed with `bundle exec <script>`. I understand `Bundler.with_original_env` ( and `Bundler.with_clean_env`)  should provide this functionality.

It seems to me though that the **PATH is not correctly preserved when running `bundle exec`**, because `lib/bundler.rb` is loaded *twice* during such an execution (once when running the `bundle` binary, and once when executing the script with `Kernel.exec('<script>')` in `cli/exec.rb`).
Therefore `Bundler.ORIGINAL_ENV` is overwritten twice, and can't be restored to the original value.

To illustrate I've added a spec about this here (which fails): https://github.com/njam/bundler/commit/8871e4166375ee9a679b5f74f099ee88a4c3d1b8

I think the only way to pass along the original environment to the sub process is by setting yet another environment variable. Maybe bundler should store the environment serialized in `BUNDLE_ORIGINAL_ENV`, and then load it from there if present?

Is this interpretation correct, or am I using the code wrong?

### PR DESCRIPTION
**Pull request by njam**
Closes #4251

@segiddins @indirect @RochesterinNYC wdyt?

### CODE REVIEW

**Comment by njam** [comment]
I changed the backup environment variable prefix from `_ORIGINAL_` to `BUNDLE_ORIG_`, as I thought it's good to have a common prefix for all those variables. If you think there's any downside of such a change I will change it back!

**Comment by segiddins** [comment]
Can you look into the failures?

**Comment by njam** [comment]
It's quite difficult to understand how the environment is modified throughout the tests :)
But I think it's good now.

Wdyt? And is it okay to change the backup variable to `BUNDLE_ORIG_*`?

**Comment by segiddins** [comment]
:+1: looks good to me!

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
