### PR TITLE
[Definition] Print a helpful warning when a dependency is unused on a…

### PR DESCRIPTION
**Pull request by segiddins**
…ny platform

Should help address the confusion caused by https://github.com/bundler/bundler/issues/5001

### CODE REVIEW

**Comment by indirect** [comment]
This is a good warning! That said, I'm not sure how this fixes the bug described in #5001. In that ticket, the Gemfile no longer contains a `platform` declaration at all, and the gem is still ignored. Seems like a different problem.

**Comment by segiddins** [comment]
That's not fixable without completely re-writing large parts of definition.

**Comment by indirect** [comment]
Assuming that is true, it still doesn't change the fact that this is solving a different problem than the one reported in #5001, does it?

**Comment by segiddins** [comment]
No, but it might help address the confusion by printing a warning in that case (saying that something out of the ordinary is taking place)

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
