### PR TITLE
Fixes #3813 : --standalone generates incorrect paths for native extensions

### LINKED ISSUE #3813: --standalone generates incorrect paths for native extensions
After `bundle install --standalone` `setup.rb` contains:
```
…
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/puma-2.11.3/tmp/test/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/puma-2.11.3"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/puma-2.11.3/lib"
```
Expecting it to be `#{path}/../#{ruby_engine}/#{ruby_version}/extensions/x86_64-linux/2.2.0/puma-2.11.3`

```
Environment

    Bundler   1.10.5
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
    GEM_HOME  /home/alerticus/.rvm/gems/ruby-2.2.1
    GEM_PATH  /home/alerticus/.rvm/gems/ruby-2.2.1:/home/alerticus/.rvm/gems/ruby-2.2.1@global
    RVM       1.26.11 (latest)
    Git       1.9.1
    rubygems-bundler (1.4.4)

Bundler settings

    gem.coc
      Set for the current user (/home/alerticus/.bundle/config): "false"
    gem.mit
      Set for the current user (/home/alerticus/.bundle/config): "true"
    gem.test
      Set for the current user (/home/alerticus/.bundle/config): "rspec"
    path
      Set for your local app (/tmp/test/.bundle/config): "bundle"
    disable_shared_gems
      Set for your local app (/tmp/test/.bundle/config): "1"

Gemfile

    source 'https://rubygems.org'

    gem 'puma'

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        puma (2.11.3)
          rack (>= 1.1, < 2.0)
        rack (1.6.4)

    PLATFORMS
      ruby

    DEPENDENCIES
      puma

    BUNDLED WITH
       1.10.5
```

### PR DESCRIPTION
**Pull request by AlexanderPavlenko**
https://github.com/bundler/bundler/issues/3813

### CODE REVIEW

**Comment by esasse** [comment]
Thanks @AlexanderPavlenko. Can you write a spec for it?

**Comment by AlexanderPavlenko** [comment]
@esasse done

**Comment by indirect** [comment]
Thanks!

**Comment by indirect** [comment]
@homu r+

**Comment by indirect** [comment]
@AlexanderPavlenko it seems like this change only passes on the very newest version of RubyGems. Can you adjust your fix to work with older versions of RubyGems as well? Thanks!

**Comment by indirect** [comment]
I since only RubyGems 2.4+ has an extensions directory, I disabled this spec on older versions in a5fb3671252eb20c0e83d6fc25a1386daaf6ffbf. Merged now. Thanks for the fix!

**Pull request merged**
