### PR TITLE
Removed compatibility hack for old rubies.

### PR DESCRIPTION
**Pull request by hsbt**
### What was the end-user problem that led to this PR?

Nothing.

### What is your fix for the problem, implemented in this PR?

Bundler will never use them in version 2.

### CODE REVIEW

**Comment by hsbt** [comment]
I wonder why we still test with Ruby 1.8

https://travis-ci.org/bundler/bundler/jobs/347596545

**Comment by deivid-rodriguez** [comment]
I think @segiddins left it there to make backporting to 1.x branches easier for the time being. Not sure though.

**Comment by segiddins** [comment]
Yes, it is to make it possible to be confident back porting to 1.x will not break things

**Comment by indirect** [comment]
Since the 1.x series has been branched off of master for a while now, I think it makes sense to stop testing master against old rubies, and make that compatibility part of the backport work if/when backports are made. 👍

**Comment by segiddins** [comment]
> make that compatibility part of the backport work if/when backports are made

At the very least, I'd like to keep them until 2.0 final is released (and we dont even have a prerelease out yet). Since we still need to support 1.16.x as the latest stable version

**Comment by hsbt** [comment]
This is no rush. I wait a release day of 2.0.

**Comment by deivid-rodriguez** [comment]
I don't really see the point of keeping 1.8 compatibility on master... I can see backports needing a bit of extra work if it's dropped but the alternative is "extra work by default".

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
