### PR TITLE
[DSL] Set ruby version when using the gemspec method

### PR DESCRIPTION
**Pull request by segiddins**
- [x] Specs

\c @indirect

### CODE REVIEW

**Comment by indirect** [comment]
@segiddins this is good, does it need a rebase for the tests to pass?

**Comment by segiddins** [comment]
This breaks new tests, so I need to fix those.

**Comment by segiddins** [comment]
@indirect remind me, is this something we still want for 2.0?

**Comment by indirect** [comment]
Yeah, I think this is good!

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r=indirect

**Pull request merged**
