### PR TITLE
removed string dup in lockfile_parser.rb for bundler 2.0

### PR DESCRIPTION
**Pull request by gavrieltal**
a task recommended by a TODO comment for the upgrade to Bundler 2.0

### CODE REVIEW

**Comment by segiddins** [comment]
Thanks!

**Comment by gavrieltal** [comment]
Out of curiosity, when do changes like this get merged into the master branch (so it is visible on github)?

**Comment by segiddins** [comment]
As soon as someone merges it :)

**Comment by segiddins** [comment]
@bundlerbot r+

**Pull request merged**
