### PR TITLE
lock: make {add,remove}-platform default to the local platform

### PR DESCRIPTION
**Pull request by sschuberth**
We need to use "lazy_default" instead of "default" as otherwise thor does
not properly return the default value for array types. Guard against the
options being "nil" by wrapping them in "Array()".

### CODE REVIEW

**Comment by segiddins** [comment]
I don't think we want a default at all here

**Comment by sschuberth** [comment]
Mind elaborating why not?

**Comment by segiddins** [comment]
Because the user should be specifying exactly which platforms should be removed -- defaulting to the local platform seems arbitrary and confusing to me

**Comment by sschuberth** [comment]
> which platforms should be removed

You explicitly say "removed" only. Does that mean you're fine with defaulting to the local platform for *adding* platforms?

> defaulting to the local platform seems arbitrary

I really don't see how that's arbitrary. It's not that we're rolling the dice. If it's in question which platform to use, using the local one seems quite natural to me.

**Comment by segiddins** [comment]
I'd rather not have defaults for either

**Comment by sschuberth** [comment]
Ok, well, then I' close this.

**Pull request closed without merging**
