### PR TITLE
Fix Style/WordArray

### PR DESCRIPTION
**Pull request by esasse**

### CODE REVIEW

**Comment by indirect** [comment]
Can we use %w[word array] instead?

**Comment by esasse** [comment]
Done. 
And maybe we can enforce %w[], do you want me to do it?

**Comment by indirect** [comment]
@esasse yeah, that would be great.

**Comment by esasse** [comment]
Looks like it's not possible to enforce it. But I'll keep looking and send another PR if needed, ok?

**Comment by indirect** [comment]
Sounds good.

**Comment by indirect** [comment]
@homu r+

**Comment by esasse** [comment]
Looks like a GitHub error during build, I'm restarting it.

**Comment by esasse** [comment]
git checkout error again, I'm not sure what to do. Any ideas?

**Pull request merged**
