### PR TITLE
Fix typo in man page.

### PR DESCRIPTION
**Pull request by smlx**

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
@indirect what's up with that?

**Comment by indirect** [comment]
@segiddins I set github to require travis to pass, and now github returns a 422 when bundlerbot tries to fast forward. 😬  I guess I'll just remove the travis requirement?

**Comment by indirect** [comment]
@bundlerbot retry

**Comment by indirect** [comment]
great, I don't know how to get out of this failure state >_>

**Comment by segiddins** [comment]
Yeah, shouldn't need it since we use bundlerbot

**Pull request merged**
