### PR TITLE
[Installer] Don't eval gemfile twice

### LINKED ISSUE #3096: Gemfile is evaluated twice when a lockfile exists
```Ruby
#Gemfile
puts "WUT"
```

no Gemfile.lock -> WUT
with Gemfile.lock -> WUTWUT

tracked it down to this guy: https://github.com/bundler/bundler/blob/master/lib/bundler/installer.rb#L63-L71

I guess it should reuse the definition from https://github.com/bundler/bundler/blob/master/lib/bundler/cli/install.rb#L77-L78

not only `bundle install` also bundle exec ruby -e 1 evaluates the Gemfile twice, so basically every bundle run could save a few miliseconds

### PR DESCRIPTION
**Pull request by segiddins**
Closes #3096 

\c @indirect

### CODE REVIEW

**Comment by segiddins** [comment]
I don't know how to make this work, it turns out `.dup`ing a SourceList doesn't do what we need, and because there's hidden mutable state in `Source` and we need a matching source because `@dependencies` maintains references to sources and :sob:

**Comment by segiddins** [comment]
Can anyone think of any possible avenues to make this work?

**Comment by indirect** [comment]
I have previously spent days fighting this and eventually given up. I think we need less hidden mutable state for it to be possible?

**Comment by segiddins** [comment]
@indirect well... yes. But a rewrite of how source / index / definition work isn't really feasible given time constraints right now

**Comment by colby-swandale** [comment]
Im happy to work on this @segiddins if you're on other things.

**Comment by segiddins** [comment]
@colby-swandale up to you -- it might just be frustrating though, so I can't wholeheartedly suggest it :/

**Comment by segiddins** [comment]
Done in 2.0

**Comment by lynnco** [comment]
Closed via https://github.com/bundler/bundler/pull/4952

**Pull request closed without merging**
