### PR TITLE
Fix typos detected by github.com/client9/misspell

### PR DESCRIPTION
**Pull request by seratch**
### What was the end-user problem that led to this PR?

Fixing typos is sometimes very hard. It's not so easy to visually review them. Recently, I discovered a very useful tool for it, [misspell](https://github.com/client9/misspell). 

This pull request fixes minor typos detected by [misspell](https://github.com/client9/misspell). 

I've ignored the past changelogs and false positives. If you would like me to work on other files as well, let me know. 

#### before

```
$ misspell .
bundler.gemspec:38:32: "automatiek" is a misspelling of "automate"
Rakefile:324:11: "automatiek" is a misspelling of "automate"
Rakefile:326:2: "Automatiek" is a misspelling of "Automate"
Rakefile:333:2: "Automatiek" is a misspelling of "Automate"
Rakefile:340:2: "Automatiek" is a misspelling of "Automate"
Rakefile:347:2: "Automatiek" is a misspelling of "Automate"
Rakefile:365:42: "automatiek" is a misspelling of "automate"
Rakefile:366:42: "automatiek" is a misspelling of "automate"
Rakefile:367:37: "automatiek" is a misspelling of "automate"
Rakefile:368:53: "automatiek" is a misspelling of "automate"
doc/development/RELEASING.md:58:5: "reposity" is a misspelling of "repository"
lib/bundler/vendor/thor/lib/thor/base.rb:116:70: "responsable" is a misspelling of "responsible"
lib/bundler/vendor/thor/lib/thor/util.rb:30:64: "responsable" is a misspelling of "responsible"
spec/runtime/setup_spec.rb:884:15: "succesfully" is a misspelling of "successfully"
spec/support/artifice/vcr_cassettes/realworld/api.rubygems.org/gems/bundler-1.12.3.gem/GET/response:193:467: "nkwo" is a misspelling of "know"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/gems/bundler-1.12.3.gem/GET/response:193:467: "nkwo" is a misspelling of "know"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/gems/diff-lcs-1.3.gem/GET/response:132:127: "Tje" is a misspelling of "The"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/gems/rack-2.0.1.gem/GET/response:572:234: "adn" is a misspelling of "and"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/gems/rack-2.0.1.gem/GET/response:831:39: "NTO" is a misspelling of "NOT"
spec/support/artifice/vcr_cassettes/realworld/api.rubygems.org/specs.4.8.gz/GET/response:4371:940: "ADN" is a misspelling of "AND"
spec/support/artifice/vcr_cassettes/realworld/api.rubygems.org/specs.4.8.gz/GET/response:6338:370: "WIH" is a misspelling of "WITH"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/specs.4.8.gz/GET/response:1790:150: "WIH" is a misspelling of "WITH"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/specs.4.8.gz/GET/response:2017:85: "TJE" is a misspelling of "THE"
```

#### after

```
$ misspell .
Rakefile:324:11: "automatiek" is a misspelling of "automate"
Rakefile:326:2: "Automatiek" is a misspelling of "Automate"
Rakefile:333:2: "Automatiek" is a misspelling of "Automate"
Rakefile:340:2: "Automatiek" is a misspelling of "Automate"
Rakefile:347:2: "Automatiek" is a misspelling of "Automate"
Rakefile:365:42: "automatiek" is a misspelling of "automate"
Rakefile:366:42: "automatiek" is a misspelling of "automate"
Rakefile:367:37: "automatiek" is a misspelling of "automate"
Rakefile:368:53: "automatiek" is a misspelling of "automate"
bundler.gemspec:38:32: "automatiek" is a misspelling of "automate"
spec/support/artifice/vcr_cassettes/realworld/api.rubygems.org/gems/bundler-1.12.3.gem/GET/response:193:467: "nkwo" is a misspelling of "know"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/gems/diff-lcs-1.3.gem/GET/response:132:127: "Tje" is a misspelling of "The"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/gems/bundler-1.12.3.gem/GET/response:193:467: "nkwo" is a misspelling of "know"
spec/support/artifice/vcr_cassettes/realworld/api.rubygems.org/specs.4.8.gz/GET/response:4371:940: "ADN" is a misspelling of "AND"
spec/support/artifice/vcr_cassettes/realworld/api.rubygems.org/specs.4.8.gz/GET/response:6338:370: "WIH" is a misspelling of "WITH"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/gems/rack-2.0.1.gem/GET/response:572:234: "adn" is a misspelling of "and"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/gems/rack-2.0.1.gem/GET/response:831:39: "NTO" is a misspelling of "NOT"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/specs.4.8.gz/GET/response:1790:150: "WIH" is a misspelling of "WITH"
spec/support/artifice/vcr_cassettes/realworld/rubygems.org/specs.4.8.gz/GET/response:2017:85: "TJE" is a misspelling of "THE"
spec/support/artifice/vcr_cassettes/realworld/index.rubygems.org/versions/GET/response:10887:60: "ect" is a misspelling of "etc"
```

### Why did you choose this fix out of the possible options?

Read the first part.

### CODE REVIEW

**Comment by colby-swandale** [comment]
Thank you so much! 🎉 

@bundlerbot r+

**Comment by hsbt** [comment]
files under the `lib/bundler/vendor/thor` is vendored code. Please submit this fixes to https://github.com/erikhuda/thor too.

**Comment by seratch** [comment]
@hsbt will do!

**Comment by seratch** [comment]
@hsbt You've already fixed them last year 👍 https://github.com/erikhuda/thor/commit/16a075eec394318f32aa5b944dc72f4a29f060ec

**Pull request merged**
