### PR TITLE
Integrate Code of Covenant 1.1.0 changes

### PR DESCRIPTION
**Pull request by strand**
See also: http://contributor-covenant.org/version/1/1/0/code_of_conduct.md

### CODE REVIEW

**Comment by indirect** [comment]
:+1: thanks

**Comment by TimMoore** [comment]
As a general procedural point, I think it would be good if we could @-mention @bundler/core for changes to the CoC to make sure everyone has a chance to understand and approve of the changes, since we are committed to abide by and enforce it. I just want to make sure that everyone is aware, since it's easy to miss stuff that happens quickly in all of the activity on the project.

For the record, I'm +1 on this particular change. :smile:

**Comment by indirect** [comment]
@TimMoore thanks, that's a really good point! I saw this as explicitly stating something that we had already agreed on in @bundler/core, but you're right, and I will make sure to check in the future. :)

**Comment by andremedeiros** [comment]
:+1 @TimMoore.

And :+1: on the change.

**Comment by segiddins** [comment]
I'm :+1: on both counts.

**Pull request merged**
