### PR TITLE
Test against Ruby 2.6 and RubyGems 3

### PR DESCRIPTION
**Pull request by segiddins**
### What was the end-user problem that led to this PR?

The problem was we weren't testing our compatibility with the latest and greatest.

### CODE REVIEW

**Comment by segiddins** [comment]
Looks like we can no longer use forwardable (it's now a gem), and a spec needs to be updated for bundler being a default gem

**Comment by segiddins** [comment]
That last commit doesn’t work, we need to avoid using the shell so we don’t need to shellescape the directory

**Comment by deivid-rodriguez** [comment]
Maybe we can use a manifest file like in rubygems.

**Comment by colby-swandale** [comment]
i would prefer avoiding that

**Comment by colby-swandale** [comment]
I've ended up just copying the what the `Shellwords.escape` method does into the gemspec

**Comment by segiddins** [comment]
👍

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Pull request merged**
