### PR TITLE
[CompactIndexClient] Synchronize access to the list of fetched endpoints

### LINKED ISSUE #5142: Unsynchronized, concurrent modification of Set instance
- What did you do?

  I ran the command `/source/rubinius/rubinius/gems/bin/bundle update` on Rubinius 3.64.

- What did you expect to happen?

  I expected Bundler to update the gems for a new Rails 5.0 application.

- What happened instead?

  Instead, what happened was Bundler failed due to an invalid modification of a Hash structure underlying a Set instance.

Unless Ruby has recently changed the concurrency guarantees of Set, it makes no guarantee of correctness under concurrent, unsynchronized modification.

Error details

    Rubinius::ObjectBoundsExceededError: Tuple::copy_from: index 10 out of bounds for size 9
      core/hash.rb:216:in `insert'
      core/hash.rb:411:in `[]='
      /source/rubinius/rubinius/gems/gems/rubysl-set-2.0.1/lib/rubysl/set/set.rb:229:in `add'
      /source/rubinius/rubinius/gems/gems/rubysl-set-2.0.1/lib/rubysl/set/set.rb:240:in `add?'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:73:in `update_info'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:44:in `dependencies'
      core/proc.rb:20:in `call'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:86:in `compact_index_client'
      core/proc.rb:20:in `call'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/worker.rb:65:in `apply_func'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/worker.rb:60:in `process_queue'
      core/kernel.rb:585:in `loop'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/worker.rb:57:in `process_queue'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/worker.rb:29:in `initialize'
      core/proc.rb:20:in `call'

Environment

  Bundler   1.13.6
  Rubygems  2.6.6
  Ruby      2.3.1p0 (2016-10-31 revision 0) [x86_64-darwin16.0.0]
  GEM_HOME  /Users/brianshirai/.gem/rbx/3.64
  GEM_PATH  /Users/brianshirai/.gem/rbx/3.64:/source/rubinius/rubinius/gems
  Git       2.5.3

      Bundler settings

  gem.test
    Set for the current user (/Users/brianshirai/.bundle/config): "false"
  gem.mit
    Set for the current user (/Users/brianshirai/.bundle/config): "false"
  gem.coc
    Set for the current user (/Users/brianshirai/.bundle/config): "true"
  build.eventmachine
    Set for the current user (/Users/brianshirai/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"

### PR DESCRIPTION
**Pull request by segiddins**
Should fix #5142.

### CODE REVIEW

**Comment by segiddins** [comment]
@indirect r?

**Comment by indirect** [comment]
both a mutex and 1 worker? shouldn't either one or the other make it work?

**Comment by segiddins** [comment]
It needs to be mutexed for all rubies

**Comment by indirect** [comment]
@bundlerbot r+

**Pull request merged**
