### PR TITLE
4854 gemnotfound error

### PR DESCRIPTION
**Pull request by diegosteiner**
Fixes broken test

Wanting to help out, I was on the outlook for something easy to fix in bundler. I stumbled upon this issue #4854, which was already tackled by @b-ggs but somehow not merged yet. I went on to check whether I could do something. Here's what I've come up with:

@b-ggs' PR included everything to solve the issue, but introduced the use of `Bundler.app_cache` in the resolver. This works out just fine until you run `bundle plugin install`, which does not seem to require a Gemfile. `Bundler.app_cache` however calls `root`,  which then again tries to find a Gemfile. This obviously fails and raises a `GemfileNotFound` exception. The error message  "Could not locate Gemfile or .bundle/ directory" starts very similar to the one expected in the failing test ("Could not find"). This however, is a completely different error.

The solution is now is to rescue the GemfileNotFound error when it comes up to here.

All credit for solving the issue goes to @b-ggs and his PR here: https://github.com/bundler/bundler/pull/4865

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻 looks perfect, thanks so much!

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
@bundlerbot r

**Comment by segiddins** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
@bundlerbot retry

**Pull request merged**
