### PR TITLE
[YAMLSerializer] Allow loading with CRLF line endings

### LINKED ISSUE #4435: .bundle/config gets written with CRLF line endings on Windows
This is a problem in my case, since `BUNDLE_PATH` will then contain a ^M at the end, so `bundler install` will create a folder with a ^M in it... :smile:

(This is when using `bundler` on Windows 10 with msys2)

I think the only sane approach would be to _always_ write to `.bundle/config` with LF-only line endings. That's the only universal approach that will work everywhere.

This has the downside that people using e.g. Notepad on Windows will not be able to read the file. I think we can live with that; you should be using better editors than Notepad anyway.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #4435.

\c @asutoshpalai

### CODE REVIEW

**Comment by indirect** [comment]
@segiddins red build

**Comment by segiddins** [comment]
@indirect a spurious failure

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu retry

**Comment by segiddins** [comment]
@homu retry

**Comment by segiddins** [comment]
@homu retry

**Comment by segiddins** [comment]
I have no clue why this keeps on happening 😭

**Comment by indirect** [comment]
@homu retry

**Comment by perlun** [comment]
@segiddins - thanks for sorting this one out! 👏

**Pull request merged**
