### PR TITLE
[RuboCop] Update to 0.34.2

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r-

**Comment by esasse** [comment]
Nice! Excluding files instead of disabling the rule, much better. :+1:

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu retry

**Comment by segiddins** [comment]
@homu retry

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
