### PR TITLE
Considerate .gemrc when determine http_proxy.

### PR DESCRIPTION
**Pull request by PG-kura**
Bundler doesn't see http_proxy written in .gemrc. So I have to set environment var corresponding to each host. I think, usually, host specific setting of rubygem is customize and adjust using .gemrc.
This patch consider http_proxy written in .gemrc when determine proxy.

### CODE REVIEW

**Comment by segiddins** [comment]
Could you please add a test for this fix?

**Comment by segiddins** [comment]
Also, anything that calls into the  `Gem` module should probably live in `rubygems_integration.rb`

**Comment by PG-kura** [comment]
I modified code and added test.

**Comment by segiddins** [comment]
Merged via https://github.com/bundler/bundler/issues/3936.

**Comment by PG-kura** [comment]
Thank you!!

**Pull request closed without merging**
