### PR TITLE
Improve and fixed guide style code from outdated cmd

### PR DESCRIPTION
**Pull request by ryanfox1985**
Hi, 

I separate these part from this PR https://github.com/bundler/bundler/pull/5058.

Regards.

### CODE REVIEW

**Comment by chrismo** [comment]
@ryanfox1985 my apologies, I didn't even know about this PR, and it looks like my recent merge stomped on it as well. 

It does seem most of these could stay with a small update on the same sort of method extraction you did that was in the recent merged commit.

I'd love to get @indirect's opinion on these changes. The project already uses rubocop to monitor style issues, and I don't feel like I have the history with the codebase to have a valuable opinion on making these changes. (Part of me doesn't want these changes due to disruption into the git history on the various lines).

**Comment by ryanfox1985** [comment]
@chrismo rebased.

**Comment by segiddins** [comment]
@chrismo r?

**Comment by ryanfox1985** [comment]
xD

**Comment by ryanfox1985** [comment]
@chrismo A part of combine the dependency array and sort one time, I improve calculate filter_options_patch the old version is checking the three variables for each gem.

**Comment by chrismo** [comment]
@bundlerbot r+

**Pull request merged**
