### PR TITLE
[wip] Travis: Switch to Trusty beta build environment

### PR DESCRIPTION
**Pull request by agis-**
**Just a test, don't bother**

See http://docs.travis-ci.com/user/trusty-ci-environment/.

### CODE REVIEW

**Comment by segiddins** [comment]
`Libraries missing for ruby-1.8.7: libruby.so.1.8.` Well, that's impressive!

**Comment by agis-** [comment]
Yep, see https://github.com/travis-ci/travis-ci/issues/4984 for more info.

**Comment by segiddins** [comment]
Closing since travis won't fix the bug.

**Comment by indirect** [comment]
Is there a reason to switch (or not) to Trusty for our > 1.8.7 builds?

**Comment by segiddins** [comment]
@indirect I don't think its worth the work to split the travis config -- its already complicated enough. Let's just make the switch for 2.0

**Pull request closed without merging**
