### PR TITLE
RuboCop 0.36 & Frozen String Literals

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
Those 1.9.3 failures make no sense to me

**Comment by indirect** [comment]
@homu r+

**Comment by indirect** [comment]
@segiddins 1.9.3 can't handle frozen version strings _anywhere_. Looks like this needs deeper changes to maintain compatibility? Or we might have to put it off until 2.0, when we can drop compatibility with Ruby 1.9.3.

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
