### PR TITLE
Fix test failure with new bundler version and default gems of bundler

### PR DESCRIPTION
**Pull request by hsbt**
This pull-request and branch are only investigation for Travis.

### CODE REVIEW

**Comment by indirect** [comment]
@bundlerbot r+

@hsbt thank you!!

**Comment by indirect** [comment]
oh, this PR still says "WIP". Hmm.

@hsbt is this ok to merge now? or is it still WIP?

**Comment by hsbt** [comment]
Ah, Thanks. I'm testing my local environment(It's very slow...)

I will change the title and merge this by myself.

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
