### PR TITLE
Add man page for `bundle gem`

### PR DESCRIPTION
**Pull request by mattbrictson**
This is my first time working with man pages, so please let me know if I missed something obvious here. I tested `bundle help gem` and the man page appeared as expected with the correct format. Is there anything else I can check?

### CODE REVIEW

**Comment by mattbrictson** [comment]
Since this is a doc addition and not a new feature, should I rebase this onto `1-10-stable` instead of `master`? Let me know.

**Comment by indirect** [comment]
I'd be happy to merge this onto 1-10-stable or master.

**Comment by mattbrictson** [comment]
Master is fine :+1:

**Comment by segiddins** [comment]
@homu r+

**Comment by indirect** [comment]
@homu retry

**Comment by indirect** [comment]
ugh spotty failures. merging now. Thanks for the updates!

**Pull request merged**
