### PR TITLE
Bundle Viz : Options without can have multiple values

### PR DESCRIPTION
**Pull request by mobilutz**
I wanted to only have one 'environment' when calling `bundle viz`. There is the options `--without`, but passing two arguments or some other form of array was not possible.

Maybe this is not the best solution. But it works for me.

The format for the option is `--without=development,test`.

### CODE REVIEW

**Comment by indirect** [comment]
Thor autosplits arguments on the colon character `:`, but I am okay with splitting single arguments on comma as well. The tests will need to pass, though.

**Comment by segiddins** [comment]
Install only seems to support `:`, I think that should be sufficient for `viz` as well?

**Comment by mobilutz** [comment]
@segiddins thanks for the hint. I changed the handling inside `viz` to be the same as `install`.
And furthermore I changed the help description a little bit.

What do you think?

**Comment by segiddins** [comment]
👍🏻 just needs a test

**Comment by mobilutz** [comment]
@segiddins I added a very rudimentary test. I don't know how else to test it because the `options` hash is being changed and then passed to a `GraphViz` initializer.

**Comment by segiddins** [comment]
@indirect r?

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
