### PR TITLE
[Setup] Fix multiple non-additive invocations of Bundler.setup with diff...

### PR DESCRIPTION
**Pull request by segiddins**
...erent groups

Closes https://github.com/bundler/bundler/issues/3009.

### CODE REVIEW

**Comment by segiddins** [comment]
@indirect even though I closed this PR, maybe you'd like to take a look?

**Comment by indirect** [comment]
Oh. This looks correct, yeah. Any reason we shouldn't merge this?

**Comment by indirect** [comment]
Oh, I see, this conflicts with the ability to replace the load path with a subsequent call to `setup`. Hmm. :/ We need to preserve the current semantics for backwards compatibility. What's the argument for changing the behaviour to this instead for 2.0?

**Comment by segiddins** [comment]
Could you explain what exactly the current semantics are?

**Comment by indirect** [comment]
To provide some total pseudocode, the current semantics are that `Bundler.setup(*groups)` is equivalent to `$LOAD_PATH = groups.map{|g| g.load_path }.flatten`. Your change makes it so that `Bundler.setup(*groups)` is additive instead of replaces. The reason for the replacing semantics is so that some people (I don't remember who anymore) could use `Bundler.setup` to remove certain groups from the load path.

**Comment by segiddins** [comment]
Are there any special semantics for the default group, perchance?

**Comment by indirect** [comment]
Not that I recall? But I haven't checked the code for them.

**Comment by segiddins** [comment]
Think I might've actually 'fixed' things by making them more consistent (accomplished entirely by deleting code)

**Comment by indirect** [comment]
Huh, amazing. :)

**Pull request merged**
