### PR TITLE
[Realworld] Use VCR for network requests

### LINKED ISSUE #5099: Stub the real world tests with vcr
The [real world tests](https://github.com/bundler/bundler/tree/master/spec/realworld) make need to make requests against external servers in order to pass. This leads to issues such as the tests breaking when a gem releases a new version, among other things. To circumvent this, the tests can be stubbed with [vcr](https://github.com/vcr/vcr).

See [this PR](https://github.com/how-is/how_is/pull/66/files) for an example vcr implementation

This involves:
- [ ] adding vcr to `bundler.gemspec`
- [ ] setting up vcr in `spec_helper.rb`
- [ ] wrapping the real world tests with vcr
- [ ] adding a script to reload the casettes into `rake release`

**! Important !** I need to completely rewrite the expectations of this feature to address https://github.com/bundler/bundler/issues/5099#issuecomment-254646393. Until then, the above details will be inaccurate

### PR DESCRIPTION
**Pull request by segiddins**
Closes #5099

### CODE REVIEW

**Comment by segiddins** [comment]
Re-implemented, should pass now. Let me know if you want me to commit the recorded responses

**Comment by lynnco** [comment]
I'm 👍 on committing the recorded responses

**Comment by segiddins** [comment]
(I'm just worried about bloating the repo history by committing them and needing to amend / re-commit several times thereafter)

**Comment by indirect** [comment]
git-lfs? submodule? I’m okay with checking them in if it means we can stop hitting the internet 😛

**Comment by segiddins** [comment]
Submodules are terrible 😭 especially if someone from outside the org ever makes a PR that depends on changes in it

**Comment by segiddins** [comment]
@indirect lfs doesn't work on directories

**Comment by mvz** [comment]
I've been involved with two projects that used VCR, and in both cases it led to problems down the line. The root cause of this, IMHO, is that the recorded blob is a black box.

**Comment by segiddins** [comment]
I actually rewrote the VCR functionality we need so we store HTTP requests and responses raw

**Comment by indirect** [comment]
@segiddins I think I'm fine with this... how big are the responses?

**Comment by segiddins** [comment]
```
$ du -hs spec/support/artifice/vcr_cassettes
 10M	spec/support/artifice/vcr_cassettes
```

**Comment by colby-swandale** [comment]
Is there any roadblocks from getting this merged? i would love to see Travis builds not timing out ❤️

**Comment by segiddins** [comment]
@colby-swandale I don't think this would change anything on Travis

**Comment by segiddins** [comment]
@indirect any feedback on the size of the cassettes?

**Comment by indirect** [comment]
@segiddins no real idea how to deal with the responses' size, tbh. this seems better than having a suite dependency on working internet and rubygems.org being up to me 😛 if you feel like this is ready to merge, I'm okay with it.

**Comment by segiddins** [comment]
Let me commit the cassettes then

**Comment by segiddins** [comment]
Cassettes added!

**Comment by indirect** [comment]
Argh, I thought I merged this. Sorry @segiddins, can you rebase?

**Comment by segiddins** [comment]
@indirect r?

**Comment by chrismo** [comment]
Haven't looked at any details, but can the cassettes be re-recorded easily? IMO, this is the biggest mistake with VCR use ... possibly the same point @mvz is making.

**Comment by segiddins** [comment]
There's a rake task to re-record

**Comment by indirect** [comment]
@chrismo yeah, the biggest reason we've been looking at this is that a lot of the "realworld" tests are effectively resolver problems that we couldn't figure out how to reproduce with test gems. Since they are effectively resolver tests, we want them to guard against regressions, but we also want to be able to run the suite without talking to rubygems.org, and we want the tests to guard against regressions even if the gems available on rubygems.org stop surfacing those regressions. This is the best compromise I can think of. 👍 

@bundlerbot r+

**Comment by chrismo** [comment]
`'cool' * 3`

**Pull request merged**
