### PR TITLE
Document change in --without behavior

### LINKED ISSUE #4351: Bundle without change in implicit behavior in v1.10.0
Prior to version 1.10.0 if you are installing using the explicit flag `--without` only the arguments provided will be used in the bundle command so if you

```
$ bundle _1.9.10_ install  --without development:test
# ...
Gems in the groups development and test were not installed.
```

Then it will only exclude your `development` and `test` groups, However with 1.10.0 any config in your `.bundle/config` will get merged in. So someone in your team checks in their bundle config that looks like this:

```
$ cat .bundle/config
---
BUNDLE_WITHOUT: unneeded
```

And you run this

```
$ bundle _1.10.0_ install  --without development:test
```

You exclude a group not present in the explicit without flag:

```
Gems in the groups development, test and unneeded were not installed.
```

I checked over the changelog and I haven't  yet figured out exactly where this change in implicit behavior came from (forgive me if I missed it in the changelog). Should we retroactively document this change or is it a bug that should be reverted?

cc/ @hone

### PR DESCRIPTION
**Pull request by schneems**
close #4351

### CODE REVIEW

**Comment by indirect** [comment]
Thanks!

@homu r+

**Comment by segiddins** [comment]
You'll need to remove the `[ci skip]` as every commit must go through CI

**Comment by schneems** [comment]
Done

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
