### PR TITLE
[Exec] Avoid loading the definition before exec-ing

### LINKED ISSUE #2951: Don't parse lockfile for "bundle exec"
I've been looking at ways to reduce the overhead for starting up `bundle exec`.  One thing that caught me by surprise is how much evaluating and parsing goes on.  The first thing the exec command does is validate the ruby version:

https://github.com/bundler/bundler/blob/v1.6.0/lib/bundler/cli/exec.rb#L11

This ends up both eval'ing the Gemfile and parsing the lockfile.  As far as I can tell, the results of parsing the lockfile are summarily discarded, only to be re-parsed when the subcommand actually starts.  The parsing code itself is a fair bit of regex matches, so it's not particularly lightweight.  If it could be bypassed altogether here, that would be a big help.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #2951, #2952.

@indirect it feels like I'm missing something?

### CODE REVIEW

**Comment by segiddins** [comment]
@nirvdrum if this is something that still interests you, would you mind checking this PR out?

**Comment by indirect** [comment]
@segiddins well, this will bundle exec to a non-Ruby command without throwing an exception if the ruby version that ran `bundle exec` is wrong? but I have no idea if that's actually a problem...

**Comment by segiddins** [comment]
It technically will, but I don't think that's really going to be a big problem -- if anything ever spawns a ruby process, bundler.setup will be called anyways.

**Comment by segiddins** [comment]
Given we have no tests that break with this change, I think I'm OK with it?

**Comment by indirect** [comment]
Yeah, my thoughts exactly.

@homu r+

**Comment by nirvdrum** [comment]
Sorry, I was offline for a bit. Thanks for taking over and getting it fixed!

**Pull request merged**
