### PR TITLE
Add 2.1.0.pre.2 changelog entries

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was that the changelog needs to be filled before releasing the next pre.

### What is your fix for the problem, implemented in this PR?

My fix is to fill in the user facing changes that I plan to include.

### CODE REVIEW

**Comment by hsbt** [comment]
@deivid-rodriguez Do you backport this and related PRs into `2-1-stable` branch for releasing 2.1.0.pre.2?

I'm not sure what's release branch for Bundler 2.1.

**Comment by deivid-rodriguez** [comment]
Yes. After I merge this PR, I will backport all PRs milestoned for `2.1.0.pre.2` to `2-1-stable` and release from there. I think there's a rake task to do just that so I will try it out.

**Comment by hsbt** [comment]
Got it! thanks ❤️

**Comment by deivid-rodriguez** [comment]
@bundlerbot r+

**Pull request merged**
