### PR TITLE
Default to packaging all on 2.0

### PR DESCRIPTION
**Pull request by segiddins**
This is going to be the last set of changes to defaults in Bundler 2.

@colby-swandale @indirect are there other changes I should be making here?

### CODE REVIEW

**Comment by indirect** [comment]
@segiddins IMO this option shouldn't even exist in 2.0—it should always package --all, and you shouldn't be able to turn it off. 👍

**Comment by indirect** [comment]
(Code looks good, I am r+)

**Comment by segiddins** [comment]
Let me remove the option in 2.0 then!

**Comment by segiddins** [comment]
> IMO this option shouldn't even exist in 2.0—it should always package --all, and you shouldn't be able to turn it off. 👍

Done!

**Comment by segiddins** [comment]
@bundlerbot r=indirect

**Pull request merged**
