### PR TITLE
Removed jobs with old ruby versions from Travis CI.

### PR DESCRIPTION
**Pull request by hsbt**
I removed the ruby versions under the Ruby 2.2. We need to fix gemspec and other parameters of .travis.yml. But this is the first step of Bundler-2.0.0 reboot.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Oh my god, it's happening!! :tada: :tada: Should we target this to master, and then backport it?

**Comment by deivid-rodriguez** [comment]
Well, there's not much to add to master other than removing the 1.8.7 entry I guess, so separate PR's make more sense since you're branching 2-0-stable off 1-17-stable. Disregard my previous comment, it's ok like this!

**Comment by deivid-rodriguez** [comment]
I have a question though, master supports `2.3.0` and up, is there any reason to keep 2.2?

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
@deivid-rodriguez I removed Ruby 2.2 and picked some jobs from the master branch 👍

**Comment by colby-swandale** [comment]
Because Bundler 2 has not been released yet, we're still accepting PRs for Bundler 1. I'll make a note to merge this change into master when we make the bundler 2 release.

**Comment by colby-swandale** [comment]
Ah, `bundlerbot` won't pass because Rubocop is currently failing. This was because of me, sorry. I will manually merge this PR into `2-0-0` stable

**Comment by hsbt** [comment]
This pull request has been merged at 9ecc86f3c8da39ce224afc3faf2646574ad49327

**Pull request closed without merging**
