### PR TITLE
Add documentation for `bundle package --all-platforms`

### PR DESCRIPTION
**Pull request by moeffju**
Added as per request by @TimMoore. PR for the doc site is forthcoming.

### CODE REVIEW

**Comment by moeffju** [comment]
The `bundler-site` repo does not yet have a source for 1.8. Should I add it to the 1.7 tree, commented-out, like the `--no-install` flag, or start the 1.8 tree (by copying and uncommenting the 1.7 tree)?

**Comment by indirect** [comment]
Go ahead and start the 1.8 tree. Thanks!

**Comment by TimMoore** [comment]
Thanks, @moeffju. Would you be able to make a pull request against the `1-8-stable` branch rather than master?

**Comment by moeffju** [comment]
Sure. Coming right up.

**Comment by moeffju** [comment]
Reopening against `1-8-stable`.

**Pull request closed without merging**
