### PR TITLE
Remove "or available on this machine" from GemNotFound error in --path mode 

### LINKED ISSUE #4854: Remove "or available on this machine" from GemNotFound error in --path mode
As discussed in #4571, it's confusing that bundler says "or available on this machine" when the bundle is installed using `--path` mode. We should stop printing it under those circumstances. While we're at it, it would be cool to add "or in gems cached in vendor/cache" if the cache exists.

### PR DESCRIPTION
**Pull request by b-ggs**
Closes #4854.

@RochesterinNYC @indirect @segiddins

### CODE REVIEW

**Comment by segiddins** [comment]
@homu delegate=RochesterinNYC

**Comment by RochesterinNYC** [comment]
@b-ggs some specs seem to be failing. Looks like `spec/commands/lock_spec.rb:88` was also asserting on "available on this machine"

**Comment by b-ggs** [comment]
I've already tried rebasing from `master`, but still keeps failing on that one spec - which is odd, since I didn't even touch anything related to that spec.

**Comment by b-ggs** [comment]
@RochesterinNYC Could you re-run the specs for this? It might be an issue on Travis' end.

```
Failures:
  1) bundler plugin install shows proper message when gem in not found in the source
     Failure/Error: expect(out).to include("Could not find")
     
       expected "Fetching source index from file:/home/travis/build/bundler/bundler/tmp/gems/remote1/\nCould not locate Gemfile or .bundle/ directory" to include "Could not find"
       Diff:
       @@ -1,2 +1,3 @@
       -Could not find
       +Fetching source index from file:/home/travis/build/bundler/bundler/tmp/gems/remote1/
       +Could not locate Gemfile or .bundle/ directory
```

**Comment by indirect** [comment]
Restarting the tests on Travis...

**Comment by b-ggs** [comment]
For some reason, running `Bundler.app_cache.exist?` breaks something, causing the failure.

**Comment by b-ggs** [comment]
Still looking, but is there any other way to check if cache exists?

**Comment by segiddins** [comment]
@b-ggs it just looks like a different error message is being printed for the one test now, so the expectation can likely just be updated

**Comment by indirect** [comment]
@b-ggs ping?

**Pull request closed without merging**
