### PR TITLE
Generically preserve new attributes in lockfile

### PR DESCRIPTION
**Pull request by segiddins**
WIP, this needs tests

@indirect

### CODE REVIEW

**Comment by segiddins** [comment]
```diff
diff --git a/lib/bundler/definition.rb b/lib/bundler/definition.rb
index 1a78cc4..abd464d 100644
--- a/lib/bundler/definition.rb
+++ b/lib/bundler/definition.rb
@@ -681,6 +681,7 @@ module Bundler
     def lockfiles_equal?(current, proposed, preserve_new_attributes)
       if preserve_new_attributes
         attributes_to_ignore = LockfileParser.attributes_to_ignore(@locked_bundler_version)
+        attribute_to_ignore += LockfileParser.unknown_attributes_in_lockfile(current)
         attributes_to_ignore.each do |attribute_to_ignore|
           pattern = /(\A|\n\n)#{attribute_to_ignore}\n(\s+.*\n)+\n?/m
           current = current.sub(pattern, "\n")
diff --git a/lib/bundler/lockfile_parser.rb b/lib/bundler/lockfile_parser.rb
index 280bcd1..d788869 100644
--- a/lib/bundler/lockfile_parser.rb
+++ b/lib/bundler/lockfile_parser.rb
@@ -32,6 +32,16 @@ module Bundler
       Gem::Version.create("1.12") => [RUBY].freeze,
     }.freeze
 
+    ALL_KNOWN_ATTRIBUTES = ATTRIBUTES_BY_VERSION_INTRODUCED.values.flatten.freeze
+
+    def self.attributes_in_lockfile(lockfile_contents)
+      lockfile_contents.scan(/^(\W[\W ])$/).uniq
+    end
+
+    def self.unknown_attributes_in_lockfile(lockfile_contents)
+      attributes_in_lockfile(lockfile_contents) - ALL_KNOWN_ATTRIBUTES
+    end
+
     def self.attributes_to_ignore(base_version = nil)
       base_version &&= base_version.release
       base_version ||= Gem::Version.create("1.0")
```

I think that will also give us forward compatibility as well?

**Comment by segiddins** [comment]
Wait, how the hell does this pass !?!? Guess it only needs some specs then!

**Comment by segiddins** [comment]
Please review @indirect (still needs more specs though )

**Comment by indirect** [comment]
I think I would probably call them "sections" rather than "attributes"? And name the option `:preserve_unknown_sections`. But this looks like a huge improvement! 🙇

**Comment by segiddins** [comment]
@indirect done

**Comment by segiddins** [comment]
Anything else to do for this?

**Comment by indirect** [comment]
No, this looks good.

@homu r+

**Comment by segiddins** [comment]
I'll ship these in 1.12.0.rc.3 right now

**Pull request merged**
