### PR TITLE
Booleanize the disable_shared_gems option

### PR DESCRIPTION
**Pull request by vassilevsky**
Hi 👻

I thought that the last value in the config looks a bit strange:

```
$ cat .bundle/config
---
BUNDLE_PATH: vendor/bundle
BUNDLE_JOBS: 4
BUNDLE_CLEAN: true
BUNDLE_DISABLE_SHARED_GEMS: '1'
```

So I have booleanized it.

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
Are there any specs around this?

**Comment by vassilevsky** [comment]
I was hoping to look at Travis results when it's done and find out 😂

**Comment by RochesterinNYC** [comment]
Hahah gotcha. Not ideal to use Travis as a dev test suite runner but I do the same thing sometimes. Side effect of incomplete unit test coverage and a load of extensive integration/feature tests really.

**Comment by segiddins** [comment]
Can you please add a test and make sure `disable_shared_gems` is on the list of Boolean keys in `settings.rb`?

**Comment by vassilevsky** [comment]
Wow. I had no idea there is such a list. I have added the option there.

I am lost as to where the tests should be added. What to test?

**Comment by segiddins** [comment]
just grepped the existing specs, so I actually think you're good

@homu r+

**Pull request merged**
