### PR TITLE
Better `--force` to `--redownload` transition

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was. that, while trying to run `bundle install --force` today, I was getting the error `unknown switch --force` error, and I was not sure what was causing it and what I needed to do to fix it. Also, running `bundle install --help` would show `--force` as a supported option, so that would make things even more confusing.

### What was your diagnosis of the problem?

My diagnosis was that:

* A lot of removal/renaming of options in bundler 2 are artificially linked to the `forget_cli_options` switch. To me, those changes even though they are related (stopping rememebering cli options prompted us to actually remove some unnecessary ones), they are independent, so it's not straighforward to find out that it's the `forget_cli_options` setting causing this rename to be in place.

* We should show a helpful deprecation message instead of a hard error, so the transition is easier for users. 

* We should update the commands help to document newer instead of deprecated options.

* The `bundle update` command has an equivalent `--force` option that should be renamed too for sanity.

### What is your fix for the problem, implemented in this PR?

My fix to the above problems is to:

* Always keep the `--force` alias, independently of whether the `forget_cli_options` is set or not.
* Show a deprecation message when `--force` is used in bundler 2, but still keep it working as before.
* Update the commands help to use `--redownload`.
* Make the equivalent changes to the `bundle update`

### Why did you choose this fix out of the possible options?

I chose this fix because it seems like the more user friendly way going forward in my opinion.

### CODE REVIEW

**Comment by indirect** [comment]
hooray! this is perfect, and exactly the kind of thing I am hoping to accomplish with the 2.0 transition. 😄 I am extremely on board with the goals here, and I think this is a great change. thank you! 🙌 

@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
@bundlerbot r=indirect

**Comment by colby-swandale** [comment]
Note that for 1.17.0, the documentation for `--force` cannot be removed. Either both options needs to be specified in the docs or just use `--force` for the time being until the next major release.

**Comment by deivid-rodriguez** [comment]
You're totally right. I think we should document `--redownload`, and say `--force` is an alias?

**Comment by deivid-rodriguez** [comment]
@colby-swandale Thoughts about doing something like [this](https://github.com/bundler/bundler/compare/still_mention_force), and removing the "deprecated" word when backporting it?

**Comment by colby-swandale** [comment]
I like the idea but i would prefer saying that `--redownload` is the alias for 1.X releases.

**Comment by deivid-rodriguez** [comment]
Sounds good to me, let me cook a PR!

**Comment by deivid-rodriguez** [comment]
Actually, after another thought I don't think we should document deprecated options, so it's better if I target the PR directly to `1.17-stable`. Sounds good?

**Comment by colby-swandale** [comment]
sounds great!

**Comment by deivid-rodriguez** [comment]
Here you go! :point_right:  #6734

**Pull request merged**
