### PR TITLE
Improve DEVELOPMENT.md readability

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I was reading `DEVELOPMENT.md` in `nvim` and found it a bit unreadable. So I typed `gqG` and thought I may add a PR in case you are interested. :wink:

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻

**Comment by deivid-rodriguez** [comment]
Mi no entender.

**Comment by segiddins** [comment]
@indirect r+?

**Comment by indirect** [comment]
I don't like hard wrapping text, because I don't think forcing your window width on everyone else is a good solution. My vim is configured to soft wrap markdown, maybe you can configure your own vim to do the same?

**Comment by deivid-rodriguez** [comment]
Yep, that's a good idea for projects that don't follow any line length conventions.

Perhaps you could move [this](https://github.com/bundler/bundler/blob/master/.rubocop_todo.yml#L51-L55) to the `.rubocop.yml` file and set it to `Enabled: false`.

**Pull request closed without merging**
