### PR TITLE
[GemTasks] Add a basic spec that the relevant tasks are installed

### PR DESCRIPTION
**Pull request by segiddins**
\c @indirect

### CODE REVIEW

**Comment by indirect** [comment]
looks like it's failing on 1.8 and 1.9, could you take a look?

**Comment by segiddins** [comment]
It looks like it's failing because the rake command isn't available or something?

**Comment by indirect** [comment]
Hmmmm. Looks like `sys_exec "rake"` is running a system-level rake executable without `GEM_HOME` and things set correctly for rake to load.

**Comment by indirect** [comment]
So it turned out to be that GEM_HOME was set to the testing GEM_HOME, which didn't have rake in it. I fixed the tests by pointing to the test support gems, which include rake, instead.

(This wasn't an error on Ruby 2+ because IIRC those versions of Ruby include Rake in the stdlib, so it was impossible to not have rake installed.)

**Comment by indirect** [comment]
51db7efb0db6a077a5e3b9222ff74d1aabf9f169 is the commit that fixed the tests for me locally on 1.8 and 1.9.

**Pull request merged**
