### PR TITLE
Fix rubygems 2.2 compatibility

### PR DESCRIPTION
**Pull request by voxik**
This is follow up of #3234

### CODE REVIEW

**Comment by indirect** [comment]
@voxik I'm happy to merge this as soon as Rubygems fixes rubygems/rubygems#784, but we can only allow these changes to happen in versions of Rubygems that have fixed that bug.

This patch needs to either: 1) work around the rubygems issue by not activating unless the rubygems issue is already fixed or 2) fix the rubygems issue via monkeypatching for the exact versions of 2.2 that are broken. Is either one of those feasible for you?

**Comment by steakknife** [comment]
Submitted https://github.com/rubygems/rubygems/pull/1137 to unblock this.  Credit to @voxik

**Comment by indirect** [comment]
ping @steakknife @voxik can either of you rebase this and check the rubygems version for a compatible one before applying the fix?

**Comment by steakknife** [comment]
@indirect @voxik Can you guys confirm that a patch is even needed?  Latest RubyGems@master reverted conflicting native/Ruby loading behavior.

**Pull request closed without merging**
