### PR TITLE
Improve quality specs

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

I'm not really sure of the exact context when I made these changes, but I recall I was getting some invalid encoding errors somehow, and they turned out to be an estraneous `’` quote in one of the documentation files.
 
### What was your diagnosis of the problem?

My diagnosis was that we should not include this character anywhere, but instead use regular quotes.

### What is your fix for the problem, implemented in this PR?

My fix is to add a quality spec for this, and while I was at it, I added some improvements to quality specs in general.

### CODE REVIEW

**Comment by simi** [comment]
Hmm, I have never seen quality specs before. Is that "poor man's rubocop alternative"? Do we really still need it since there's rubocop check done on CI?

**Comment by deivid-rodriguez** [comment]
It's similar but not the same. Quality specs are used for tasks that are outside of rubocop's scope, mainly because they are quality checks that apply to all (or most) files in the projects, not only to files containing ruby code.

**Comment by deivid-rodriguez** [comment]
I fixed this PR since it had failed to detect a lot of those non-standard quotes. Now, I can close this since I can't reproduce the original problem, and maybe this symbol is more common when typing on English keyboards than I thought? I do find the consistency of using always the same symbol for single quotes nice and less distracting.

**Comment by deivid-rodriguez** [comment]
I'll merge this one tomorrow unless anybody has objections.

**Comment by deivid-rodriguez** [comment]
:heart:

@bundlerbot r=hsbt

**Pull request merged**
