### PR TITLE
Rescue Net::HTTPFatalError, too

### LINKED ISSUE #3830: could not bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/lokesh/.rvm/gems/ruby-2.1.1/bin/bundle update`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Net::HTTPFatalError: 503 "Service Unavailable"
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:915:in `connect'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:858:in `start'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/request/http_pool.rb:42:in `setup_connection'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/request/https_pool.rb:6:in `setup_connection'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/request/http_pool.rb:38:in `make_connection'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/request/http_pool.rb:19:in `checkout'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/request.rb:85:in `connection_for'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/request.rb:140:in `perform_request'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/request.rb:109:in `fetch'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:352:in `request'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:237:in `fetch_http'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:273:in `fetch_path'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/rubygems_integration.rb:560:in `fetch_specs'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/rubygems_integration.rb:574:in `block in fetch_all_remote_specs'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/source_list.rb:90:in `block in each'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/source_list.rb:90:in `each'
      /home/lokesh/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/source_list.rb:90:in `each'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/rubygems_integration.rb:572:in `fetch_all_remote_specs'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/fetcher/index.rb:9:in `specs'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/fetcher.rb:102:in `block in specs'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/fetcher.rb:100:in `each'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/fetcher.rb:100:in `specs'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:330:in `block (2 levels) in remote_specs'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:328:in `each'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:328:in `block in remote_specs'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/index.rb:9:in `build'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:324:in `remote_specs'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:81:in `specs'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/definition.rb:209:in `each'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/definition.rb:209:in `block in index'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/index.rb:9:in `build'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/definition.rb:206:in `index'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/definition.rb:200:in `resolve'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/definition.rb:140:in `specs'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/installer.rb:79:in `run'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/installer.rb:18:in `install'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/cli/update.rb:51:in `run'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/cli.rb:187:in `update'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/cli.rb:10:in `start'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/bin/bundle:20:in `block in <top (required)>'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/lokesh/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.5/bin/bundle:18:in `<top (required)>'
      /home/lokesh/.rvm/gems/ruby-2.1.1/bin/bundle:23:in `load'
      /home/lokesh/.rvm/gems/ruby-2.1.1/bin/bundle:23:in `<main>'
      /home/lokesh/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
      /home/lokesh/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.5
    Rubygems  2.4.8
    Ruby      2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]
    GEM_HOME  /home/lokesh/.rvm/gems/ruby-2.1.1
    GEM_PATH  /home/lokesh/.rvm/gems/ruby-2.1.1:/home/lokesh/.rvm/gems/ruby-2.1.1@global
    RVM       1.26.11 (latest)
    Git       1.9.1
    rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

### PR DESCRIPTION
**Pull request by indirect**
fixes #3830

### CODE REVIEW

**Comment by indirect** [comment]
@segiddins r?

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@indirect rubocop failures: https://travis-ci.org/bundler/bundler/jobs/73735197#L237

**Comment by indirect** [comment]
Gahhhhhhhhhh

**Comment by indirect** [comment]
@homu r+

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
