### PR TITLE
Fix ignore messages

### LINKED ISSUE #3600: Fix (& document) ignore_message config
Right now the ignore_message config isn't documented in the `config` manpage, and it also causes empty post-install messages to be printed out for every gem that isn't actively ignored. We should fix that for 1.10 :)

/cc @pducks32

### PR DESCRIPTION
**Pull request by pducks32**
Fixes #3600 part 2

### CODE REVIEW

**Comment by segiddins** [comment]
This needs specs!

**Comment by indirect** [comment]
I like this change! Being able to disable all messages is useful. However, I'm not sure this actually fixes the problem with ignoring a single gem. When I ignored just one gem, it caused empty install messages to be printed for every other gem in the bundle. That's what I was talking about in #3600.

**Comment by pducks32** [comment]
It does because before `has_post_install_message` evaluated to true when it was `empty?` which is obviously the opposite which meant that the ones that did print were empty.

**Comment by pducks32** [comment]
Is there any way to rerun the tests without having to commit a trivial commit as its rubygems' error.

**Comment by indirect** [comment]
Unfortunately, RubyGems master is actually broken right now. :(

**Pull request merged**
