### PR TITLE
Minor edits as suggested by @rubymorillo

### PR DESCRIPTION
**Pull request by kerrizor**
Minor edits to docs as suggested by @rubymorillo in bundler/bundler#6496.. I don't have write access, so I'm submitting them off my fork.

### CODE REVIEW

**Comment by colby-swandale** [comment]
Awesome! 🎉 

@bundlerbot r+

**Comment by segiddins** [comment]
@colby-swandale you might need to rebase your branch on master

**Comment by colby-swandale** [comment]
Oh, i have screwed up when i tried to rebase this branch 😭

**Comment by colby-swandale** [comment]
I've just taken the commit and incorporated in straight into the branch.

**Comment by colby-swandale** [comment]
sorry again. 🙇

**Pull request closed without merging**
