### PR TITLE
[Settings] Allow temporarily overriding settings in-memory

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by indirect** [comment]
Can you explain the rationale for this?

**Comment by segiddins** [comment]
Sure! We use settings in two ways -- one is user preferences, stored via `bundle config`, and the other is as global internal configuration. When attempting to refactor out `--frozen` for 2.0, I ran into issues getting rid of the auto-saved config for `Bundler.settings[:frozen]` because it's used in places where injecting the configuration value isn't really possible

**Comment by indirect** [comment]
@homu r+

That's a good point about these being two separate things—maybe we will want to make them explicitly different in the future?

**Comment by segiddins** [comment]
Blocked on https://github.com/bundler/bundler/pull/4928

**Comment by segiddins** [comment]
@homu retry

**Pull request merged**
