### PR TITLE
[WIP] New patch level and conservative options documented.

### LINKED ISSUE #4775: Conservative update documentation updates
- [x] lock man page
- [x] outdated man page
- [x] update man page
- [x] _will bundler-site man pages be synced? I presume so**_
- [ ] any other docs/site locations? => http://bundler.io/v1.13/updating_gems.html
- [ ] release notes need to flesh out reason for breaking change on outdated patch level options?
- [ ] blog post?

Task spawned from #4676 

**_I'm not seeing bundle_update page in [v1.13](https://github.com/bundler/bundler-site/tree/master/source/v1.13)_

### PR DESCRIPTION
**Pull request by chrismo**
Fixes #4775.

### CODE REVIEW

**Comment by chrismo** [comment]
force pushed a no-op --amend commit to trigger a new build. Last one failed on a floopy, non-related 1.8.7. test.

**Comment by chrismo** [comment]
...and again...

**Comment by indirect** [comment]
@chrimo fwiw, you can manually re-run only the travis sub-build that failed by clicking through to it and choosing "restart job" in the top right. Sometimes that helps, since it lets you keep successes on other version combinations.

**Comment by chrismo** [comment]
ah! TIL. thx a bunch - that's good to know.

**Comment by chrismo** [comment]
all green - ready for your approves and homu incantation @indirect

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
