### PR TITLE
Fix Style/TrailingUnderscoreVariable

### PR DESCRIPTION
**Pull request by esasse**

### CODE REVIEW

**Comment by asymmetric** [comment]
Honestly not sure why the second form is considered better - I'd argue it's even less clear.

**Comment by esasse** [comment]
I agree, just sent the PR so that we can discuss and decide if we'll use rubocop default or the current style with underscore.

**Comment by segiddins** [comment]
I'm :+1: with this

**Comment by agis-** [comment]
IMHO clearest of both is:

```ruby
out, _foo = sh_with_code("gem install '#{built_gem_path}'#{" --local" if local}")
```

Ruby won't warn for unused variables beginning with `_`.

**Comment by indirect** [comment]
I agree that leaving it out is less understandable than just making it `_`. Let's set the rubocop styles to require just a single `_`, like we do elsewhere when we have unused variables.

**Comment by esasse** [comment]
Ok, so what I did was just move the config to the main rubocop file since this is the setting we want for the project. And I could not find a way to enforce this style.

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
