### PR TITLE
Add ruby 2.7 and rubygems 3.1.2 to CI matrix

### LINKED ISSUE #7585: Add ruby 2.7 to CI matrix
I want to make sure everything is good in ruby 2.7 before the next release.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Closes #7585.

### What was the end-user or developer problem that led to this PR?

As a developer, I want to make sure that bundler works against the latest versions of ruby and rubygems.

### What is your fix for the problem, implemented in this PR?

My fix is to add those to the CI matrix.

### CODE REVIEW

**Comment by simi** [comment]
Should we add `gem install rake` step to https://github.com/rubygems/bundler/blob/master/doc/development/SETUP.md#development-setup as well?

**Comment by deivid-rodriguez** [comment]
I think it's not necessary because many ruby installations come with `rake` preinstalled (it's a bundled gem), and if not the error message is very clear:

```
$ bin/rake spec:deps
We couln't activate rake (>= 0.a). Run `gem install rake:'>= 0.a'`
```

**Comment by deivid-rodriguez** [comment]
Current [issue here](https://github.com/rubygems/bundler/pull/7593/checks?check_run_id=408079806) might be due to [a `parallel_tests` issue](https://github.com/grosser/parallel_tests/issues/705).

**Comment by deivid-rodriguez** [comment]
I think it's going to be intermittent, but I'll double check through a retry.

@bundlerbot retry

**Comment by hsbt** [comment]
I created the version of GitHub Actions to https://github.com/rubygems/rubygems/pull/3397.

**Pull request closed without merging**
