### PR TITLE
Fix bitbucket/gist deprecation warnings

### PR DESCRIPTION
**Pull request by agis-**
Also fix the respective test failures which were around for a while.

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻

**Comment by segiddins** [comment]
@homu r+

**Comment by agis-** [comment]
Hm not sure what's going on with this one.

**Comment by segiddins** [comment]
@homu retry

**Comment by segiddins** [comment]
@homu r+

**Comment by agis-** [comment]
I think @homu doesn't like this :disappointed:

**Comment by segiddins** [comment]
Could you try rebasing?

**Comment by agis-** [comment]
@segiddins done.

**Comment by segiddins** [comment]
@homu r+

**Comment by agis-** [comment]
It seems that now that the tests are green, rubocop runs *after* them and it fails: https://travis-ci.org/bundler/bundler/jobs/88719459.

However I think we should merge this regardless of those failures, since they are irrelevant.

**Pull request merged**
