### PR TITLE
Try out specs against MRI 2.6 + Rubygems 3.0

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was that our Azure build was using outdated versions of ruby and rubygems.

### What was your diagnosis of the problem?

My diagnosis was that we should update them.

### What is your fix for the problem, implemented in this PR?

My fix is to update them. With the latest versions, failures go down to 319.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@deivid-rodriguez 

Probably wait till the weekend. You ok with switching to Actions for Windows?

**Comment by deivid-rodriguez** [comment]
Yes, that was in our plans anyways, so :+1:.

**Comment by deivid-rodriguez** [comment]
I'll get this in for now.

@bundlerbot merge

**Pull request merged**
