### PR TITLE
[Installer] Add option to force installation

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://trello.com/c/baZN0BmP/78-add-bundle-install-force-option.

### CODE REVIEW

**Comment by indirect** [comment]
😮😬 you are a machine!

**Comment by segiddins** [comment]
Maybe this would be cleaner if implemented as a setting?

**Comment by indirect** [comment]
Nah, I'm pretty sure this is effectively "bundle pristine"... actually wait hmm. Can we make this "bundle pristine --download" instead, and have pristine without download just install without downloading? That would close like 3 tickets at once.

**Comment by indirect** [comment]
@segiddins, any comment on the `pristine` challenge? Should I just create a Trello card for that and link to this pull as the starting point?

**Comment by segiddins** [comment]
Just haven't gotten around to it yet. First I need to figure out exactly what the scope is!

-Samuel E. Giddins

On Mar 31, 2015, at 6:08 PM, André Arko <notifications@github.com> wrote:

@segiddins, any comment on the pristine challenge? Should I just create a Trello card for that and link to this pull as the starting point?

**Comment by segiddins** [comment]
@indirect if you wrote up exactly what `bundle pristine` should be, I might be able to make it happen :)

**Comment by indirect** [comment]
The `bundle pristine` command would basically be `bundle exec gem pristine`. That re-installs the gem from the tarball that's kept in $GEM_PATH/cache. Bundler's pristine would also need to do a `git reset --hard HEAD && git clean -fd` for each git gem. I guess the download flag would force gems to be downloaded even if they're already in the local cache.

I am really excited about adding checksum support so we won't need that. :P

**Comment by indirect** [comment]
I give up, this is not the same as pristine. Let's just merge.

**Comment by segiddins** [comment]
@indirect sorry about this not being `pristine` :stuck_out_tongue_closed_eyes:

**Pull request merged**
