### PR TITLE
bundler gem: Support test-unit as a testing framework

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
Sorry. I missed #5255 .

**Comment by mame** [comment]
I believe that this PR is accepted.  See https://github.com/bundler/bundler/pull/7420 and https://github.com/bundler/bundler/issues/7421.

**Comment by hsbt** [comment]
@kou Can you rebase this?

**Comment by kou** [comment]
Sure. I'll do it.

**Comment by kou** [comment]
Done.
Some improvements in https://github.com/bundler/bundler/pull/7420 are also included.

**Comment by hsbt** [comment]
@bundlerbot merge

**Comment by hsbt** [comment]
@bundlerbot retry

**Comment by hsbt** [comment]
@deivid-rodriguez test-unit was shipped with the ruby core installer. So, It's the same situation as minitest. If an issue related to this, I or @kou will fix it.

**Comment by deivid-rodriguez** [comment]
Great! :heart:

**Pull request merged**
