### PR TITLE
Restore the removal of the `--all` flag for `bundle cache` in Bundler 3

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was that I accidentally restored this flag on Bundler 3 in #7249, but the plan still is to remove it.

### What was your diagnosis of the problem?

My diagnosis was that I need to remove it again.

### What is your fix for the problem, implemented in this PR?

My fix is to remove it.

### Why did you choose this fix out of the possible options?

I chose this fix because it's the original plan and makes sense.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
This is a regression of #7249, by the way.

**Comment by deivid-rodriguez** [comment]
@indirect I tagged you because you reviewed the PR that caused the regression (and because your feedback is always great :)), sorry if I'm a bit overwhelming :sweat_smile:.

**Comment by indirect** [comment]
👍🏻

@bundlerbot r+

**Comment by indirect** [comment]
ugh wrong button

@bundlerbot r+

**Pull request merged**
