### PR TITLE
before/after install hooks support

### PR DESCRIPTION
**Pull request by lxsameer**
### Why:
Running a code block at specific moments of bundler activities like dependency installation is a feature which allows users to customize the their environment based on bundler and installed gems.

### What are the new features:
  * `after_install` method added to `Bundler` dsl
  * `before_install` method added to `Bundler` dsl

related to: https://github.com/bundler/bundler-features/issues/118

### CODE REVIEW

**Comment by segiddins** [comment]
I've implemented basically this before and we decided not to merge it

**Comment by lxsameer** [comment]
Why? It's small, handy and harmless

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/pull/3471

**Comment by RochesterinNYC** [comment]
@segiddins is there a past PR/issue that can be referenced?

@lxsameer I'm adding a few questions regarding use cases and why/if this is a necessary feature to the issue that you opened in bundler-features. Let's discuss them there.

**Comment by indirect** [comment]
We have somewhat more notes written up here: https://trello.com/c/LJUJNMGN. RubyGems already has before-install hooks, and we already respect them, so the discussion is around implementing a more flexible hook system that has slightly more protection against things like exceptions inside hooks.

**Comment by lxsameer** [comment]
@indirect This solution is very simple and easy to use specially for end users. Also exception handling can be added to this solution easily. I think the most important point in this solution is simplicity. there is almost no overhead and implementing new hook can be done in no time.

It's an easier solution rather than rubygems hook and suitable for end users for tooling and managing tasks.

**Comment by indirect** [comment]
@lxsameer this gem already automatically generates ctags for gems as they are installed by Bundler, using the RubyGems install hooks that Bundler already supports: https://github.com/tpope/gem-ctags. Do you have any other use-cases for this kind of hook?

**Comment by indirect** [comment]
Ugh, I left this comment on the PR when I meant to leave it on the feature request. Sorry, I'll go over there now...

**Comment by lxsameer** [comment]
@homu done

**Pull request closed without merging**
