### PR TITLE
fix with and without groups

### PR DESCRIPTION
**Pull request by pducks32**
cc @smlance
This is still going to fail but at least with and without groups will be fine. Now they won't be auto remembered and will also override each other. As it turns out they didn't before, they would do it bluntly and not take into account the actual groups.

### CODE REVIEW

**Comment by indirect** [comment]
I'm okay with merging this as progress towards a green build, but I'll hold off until it's ready. :)

**Comment by smlance** [comment]
Update: we'll split this feature into separate PRs, because this change uproots a lot of old Bundler functionality. This PR is a good start, though -- thanks, @pducks32!

**Comment by segiddins** [comment]
Should this be closed at this point?

**Comment by indirect** [comment]
Yeah, I think so.

**Pull request closed without merging**
