### PR TITLE
Setting docker for development

### PR DESCRIPTION
**Pull request by alaxalves**
Thanks so much for the contribution!
To make reviewing this PR a bit easier, please fill out answers to the following questions.

### What was the end-user problem that led to this PR?

The problem was manually installing dependencies for development.

### What was your diagnosis of the problem?

My diagnosis was there was no docker available to make the development easier. So one was needed.

### What is your fix for the problem, implemented in this PR?

My fix was creating a bundler image that run the bundler development evironment

### Why did you choose this fix out of the possible options?

I chose this fix because it is a better solution than Vagrant in this context.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Thanks @alaxalves, and sorry for not replying earlier.

Coincidentially, I'm working on getting bundler tested under docker. Your PR is useful, thanks! For now I'm going to leave it there. After we integrate docker in our CI workflow, I'll see what to do with this PR. :+1:

**Comment by alaxalves** [comment]
> Thanks @alaxalves, and sorry for not replying earlier.
> 
> Coincidentially, I'm working on getting bundler tested under docker. Your PR is useful, thanks! For now I'm going to leave it there. After we integrate docker in our CI workflow, I'll see what to do with this PR.

@deivid-rodriguez Do you think I could contribute somehow to the docker workflow you're implementing?

**Comment by deivid-rodriguez** [comment]
Hei!

I have this WIP branch: https://github.com/bundler/bundler/commits/linux_azure, but it's a bit of a mess, specially because the base images I'm using are some personal images hosted at gitlab currently. We should probably move these images to this repo, or to a `bundler/docker` repo.

Ideally we would use the official docker images for ruby, but they include some special bundler configuration, and they install bundler on them, and we don't really want that for testing bundler.

**Comment by alaxalves** [comment]
@deivid-rodriguez Do you think its a good idea open this as a `WIP:` merge?

**Comment by hsbt** [comment]
@alaxalves We merged bundler repo into [rubygems repo](https://github.com/rubygems/rubygems). If you are still interested in these changes, Can you open the new pull request to [rubygems repo](https://github.com/rubygems/rubygems)? Thanks.

**Pull request closed without merging**
