### PR TITLE
Make version conflict messages better

### PR DESCRIPTION
**Pull request by segiddins**
~~This is a WIP. Need to wait until https://github.com/CocoaPods/Molinillo/pull/99 is merged & released~~

### What was the end-user problem that led to this PR?

The problem was Bundler version messages could be confusing.

Closes https://github.com/bundler/bundler/issues/6642
Closes https://github.com/bundler/bundler/issues/6620

### What was your diagnosis of the problem?

My diagnosis was we barf out a bunch of "conflicts", not all of which are actually conflicts. We could also print a whole bunch of requirements that didn't _actually_ contribute to the conflict at hand.

Messaging was also super weird when there were `required_ruby_version` conflicts, since we called "ruby" a gem.

### What is your fix for the problem, implemented in this PR?

Improves Bundler version conflict messages in multiple cases. (conflict on `required_ruby_version`, conflict on 2.0 containing redundant platforms, conflict on 2.0 not being reduced to minimal form, showing irrelevant conflicts that dont actually conflict, actually reducing all type of conflicts to the minimal set). 

### Why did you choose this fix out of the possible options?

I chose this fix because...

### CODE REVIEW

**Comment by indirect** [comment]
I am _very_ excited about this, thanks @segiddins!

**Comment by colby-swandale** [comment]
Thanks! @bundlerbot r+

**Comment by colby-swandale** [comment]
(sorry I forgot the note at the top)

**Comment by indirect** [comment]
@bundlerbot r+

**Pull request merged**
