### PR TITLE
[Source::Path] Sort gemspecs by relative depth

### PR DESCRIPTION
**Pull request by segiddins**
Attempts to close https://github.com/bundler/bundler/issues/3286, https://trello.com/c/DQx0OKJl/82-search-for-gemspecs-near-the-root-of-a-git-repo-first

\c @TimMoore

### CODE REVIEW

**Comment by indirect** [comment]
hah, clever. I was going to have two globs, the first only matching the top level. I think this is a better general solution

**Comment by segiddins** [comment]
Let me know if you want specs for this change

-Samuel E. Giddins

On Feb 23, 2015, at 6:25 PM, André Arko <notifications@github.com> wrote:

hah, clever. I was going to have two globs, the first only matching the top level. I think this is a better general solution

**Comment by indirect** [comment]
I think the existing specs probably cover this sufficiently? Of course, I may regret saying that in a few weeks or months, so if you could add a spec that would be great. :+1:

**Comment by segiddins** [comment]
Hm, I can't use the premailer example to make a realworld spec, since only their development dependencies differ.

**Comment by TimMoore** [comment]
:+1: thanks @segiddins!

A spec would be good, if only to make sure nobody breaks it again in the future. It might work to use the `build_lib` helper to build a simple gem with an invalid gemspec (one with just `raise "FAIL"` in it for example) in a subdirectory that sorts before the real one alphabetically. Then the spec can verify that the path gem still works in a `Gemfile`.

**Comment by segiddins** [comment]
@TimMoore would be happy to -- any pointers on how to do that with `build_lib`? It always just seems to be used like `build_lib 'foo'`

**Comment by TimMoore** [comment]
@segiddins it can take a block, and yields a builder object that can be used to write files into the path. See https://github.com/bundler/bundler/blob/master/spec/install/path_spec.rb#L56 for example

```
      build_lib "rack", "1.0.0", :to_system => true do |s|
        s.write "lib/rack.rb", "raise 'FAIL'"
      end
```

**Comment by segiddins** [comment]
@TimMoore updated with a spec + comments :)

Turned out the issue was `Index#<<` overriding the earlier specs -- in other words, the glob pattern was not the actual problem.

**Comment by indirect** [comment]
Yay specs! :)

**Comment by TimMoore** [comment]
LGTM :+1:

**Pull request merged**
