### PR TITLE
Start working on label descriptions

### PR DESCRIPTION
**Pull request by LynnCo**
Will add an explanation of how I use the most common labels.

Refs https://github.com/bundler/bundler/labels, https://github.com/rubygems/rubygems/labels

### CODE REVIEW

**Comment by segiddins** [comment]
I've been very happy with our system at CocoaPods: https://guides.cocoapods.org/contributing/tickets-handling.html

**Comment by LynnCo** [comment]
I'm trying to merge the Bundler and RubyGems issue styles, but they're both a bit messy. Coacoa pods issues are extremely well done though, and I would like to move to a system like that. Just have to figure out how to map the current Bundler and RubyGems issues to it. This braindump incoming...

**Comment by LynnCo** [comment]
`0 - Backlog` and `1 - Working / Ready` are both status indicators, as is `Triage` and `More-Information-Needed`, although the last one should probably be more like `User-Feedback-Required` (like CoacoaPods' `waiting input`). So is `confirmed` but I never use that (will delete). Instead of marking issues as confirmed, I like to give them a type (ie. `bug report` or `feature request`)

**Comment by segiddins** [comment]
Confirmed basically means it's been triaged and is awaiting work, but there's no real detail in how to fix

**Comment by LynnCo** [comment]
Going to use triage for what could be confirmed, triage here meaning "we're still figuring this one out"

**Comment by LynnCo** [comment]
thinking about changing "more information needed" to "user feedback needed" since that's how its used in practice.

**Comment by LynnCo** [comment]
Types:

bug report, feature, documentation, small

Status:

triage, user feedback needed, working / ready, backlog

Area (?):

resolver, platforms, windows, ...

Special case:

GSoC (Google Summer of Code)

---

I really like the `t1` (ie. type 1) syntax that [CocoaPods uses](https://github.com/CocoaPods/CocoaPods/labels), so I'll definitely be adopting that

**Comment by segiddins** [comment]
@LynnCo I'd rather no label mean untriaged, rather than having to specifically apply one

**Comment by LynnCo** [comment]
@segiddins I'm also not a fan of area labels, their implementation in Bundler is definitely spotty.

I have to think about the triage thing. I've been using no label to mean "nobody tried to categorize this" and adding the triage label often reassures users that someone is working on resolving their issue. That is, a user sees someone adding the "triage" label and that is a reasonable stand in for a comment saying "we are working on this". That said, not explicitly labeling things as triage saving quite a lot of clicks. (...) I'm going to keep thinking about this one.

**Comment by LynnCo** [comment]
I'm considering using milestones for "area" instead of labels. Ex: [Better Platform Support (milestone)](https://github.com/bundler/bundler/milestones/1.X%20--%20Better%20Platform%20Support) instead of [Platforms (label)](https://github.com/bundler/bundler/labels/platforms). Milestone's haven't gotten a lot of use in Bundler recently, so we'll see if this ends up being useful.

**Comment by LynnCo** [comment]
So RE `triage`,

In repos where the issues are both for development work and support issues, adding the `triage` label assures users posting about support issues that we are looking into it. I definitely want to keep it, for that reason.

**Comment by indirect** [comment]
I am not strongly opinionated about the existence or use of a `triage` label, but I think it's fine to use it as part of our overall labelling overhaul, especially if it makes life easier for the person doing the majority of the labelling work, who in this case is @LynnCo. 👍 

In my ideal future world, the bot will high-five new PRs, roll up newly posted issues into a digest delivered into Slack for team members to triage and process on a daily-ish schedule, delete +1 comments, and generally help us keep things organized and tidy. An automatic triage label seems like an okay intermediate step in the grand plan, although likely not the final resting state.

**Comment by LynnCo** [comment]
So (luckily) the new issue labels are by and large self explanatory, or at least enough so that added a description of them into ISSUES.md would mainly involve me writing for the sake of writing.

Which is so say that I'm closing this PR

**Pull request closed without merging**
