### PR TITLE
Random spec improvements

### PR DESCRIPTION
**Pull request by segiddins**
Called "sam has a flight and forgot to run `rake spec:deps`"

### CODE REVIEW

**Comment by indirect** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
Ugh I'll have to figure out what here broke the build 😭

**Comment by segiddins** [comment]
Should be fixed now!

**Comment by indirect** [comment]
@segiddins uhh 😬

**Comment by segiddins** [comment]
Actually fixed now!

**Comment by indirect** [comment]
@segiddins third time’s the charm?

**Comment by segiddins** [comment]
just needed to require `net/https` for < 2.0 ¯\_(ツ)_/¯

**Comment by indirect** [comment]
@bundlerbot r+
@bundlerbot r+

**Comment by segiddins** [comment]
@homu r=indirect

**Comment by segiddins** [comment]
@bundlerbot r=indirect

**Comment by segiddins** [comment]
I can't reproduce that failure locally :/

**Comment by olleolleolle** [comment]
@segiddins I wanted to help, so I ran the specs on OS X:

That got me 1 failure with a a `ArgumentError: couldn't find HOME environment -- expanding '~'`. (The Rubocop project worked around it like this: https://github.com/bbatsov/rubocop/issues/2901)

<details>

```
Failures:

  1) compact index api falls back when the user's home directory does not exist or is not writable
     Failure/Error: bundle! :install, :artifice => "compact_index"

     RuntimeError:
       Invoking bundle!(:install, {"no-color"=>true}) failed:
       Your home directory is not set properly:
        * `/` is not writable

       Bundler will use `/var/folders/pj/79cx_w6138gcqrw8l1qxl3f00000gn/T/bundler/home/olle` as your home directory temporarily
       Fetching gem metadata from http://localgemserver.test/.
       Fetching version metadata from http://localgemserver.test/
       Resolving dependencies...
       Using bundler 1.13.6
       ArgumentError: couldn't find HOME environment -- expanding `~'
       An error occurred while installing rack (1.0.0), and Bundler cannot continue.
       Make sure that `gem install rack -v '1.0.0'` succeeds before bundling.

       ArgumentError: couldn't find HOME environment -- expanding `~'
       An error occurred while installing bundler (1.13.6), and Bundler cannot continue.
       Make sure that `gem install bundler -v '1.13.6'` succeeds before bundling.

       Commands:
       $ /Users/olle/.rubies/ruby-2.3.3/bin/ruby -I/opt/src/opensource/ruby/bundler/lib:/opt/src/opensource/ruby/bundler/spec -r/opt/src/opensource/ruby/bundler/spec/support/artifice/compact_index.rb -rsupport/hax /opt/src/opensource/ruby/bundler/exe/bundle install --no-color
       Your home directory is not set properly:
        * `/` is not writable

       Bundler will use `/var/folders/pj/79cx_w6138gcqrw8l1qxl3f00000gn/T/bundler/home/olle` as your home directory temporarily
       Fetching gem metadata from http://localgemserver.test/.
       Fetching version metadata from http://localgemserver.test/
       Resolving dependencies...
       Using bundler 1.13.6
       ArgumentError: couldn't find HOME environment -- expanding `~'
       An error occurred while installing rack (1.0.0), and Bundler cannot continue.
       Make sure that `gem install rack -v '1.0.0'` succeeds before bundling.

       ArgumentError: couldn't find HOME environment -- expanding `~'
       An error occurred while installing bundler (1.13.6), and Bundler cannot continue.
       Make sure that `gem install bundler -v '1.13.6'` succeeds before bundling.
       # $? => 5
     # ./spec/install/gems/compact_index_spec.rb:185:in `block (2 levels) in <top (required)>'

Finished in 43 minutes 49 seconds (files took 1.9 seconds to load)
2135 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/install/gems/compact_index_spec.rb:177 # compact index api falls back when the user's home directory does not exist or is not writable

/Users/olle/.rubies/ruby-2.3.3/bin/ruby -I/Users/olle/.gem/ruby/2.3.3/gems/rspec-support-3.5.0/lib:/Users/olle/.gem/ruby/2.3.3/gems/rspec-core-3.5.4/lib /Users/olle/.gem/ruby/2.3.3/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

</details>

**Comment by indirect** [comment]
@segiddins this looks good to me, so go ahead and r=indirect once the test failure is worked out 👍

**Comment by segiddins** [comment]
@homu r=indirect

**Comment by segiddins** [comment]
@bundlerbot r=indirect

**Pull request merged**
