### PR TITLE
Print a warning when a gem can't be cached due to a missing source

### PR DESCRIPTION
**Pull request by EduardoBautista**
I still need to create a test, but I am not entirely sure where to write it.

### CODE REVIEW

**Comment by segiddins** [comment]
I don't think this is correct, iirc we have a faux rubygems source to contain the local gems?

**Comment by indirect** [comment]
@segiddins we paired on this, and it fixes the problem--built in gems don't have .gem files, and if there's no remote source with a copy, it causes the exception we've seen reported.

**Comment by segiddins** [comment]
@indirect ah ok, cool

**Comment by EduardoBautista** [comment]
So where should the test be written?

**Comment by indirect** [comment]
I copied a cache-builtin spec and removed the source `e872985f4f4988437e3f47efe18842513bd62452`. @EduardoBautista can you cherry-pick that commit into this PR so we can run the tests?

**Comment by EduardoBautista** [comment]
@indirect Done.

**Comment by segiddins** [comment]
@homu r+

**Comment by indirect** [comment]
Merged with fixed whitespace as 69475cb66c86c271494299e595b0ad3f04bbda31. Thanks!

**Pull request merged**
