### PR TITLE
[Travis] Test against Ruby 2.3.0

### PR DESCRIPTION
**Pull request by segiddins**
\c @indirect

### CODE REVIEW

**Comment by indirect** [comment]
Thanks! It seems good to get this working soon.

**Comment by RochesterinNYC** [comment]
So does Travis CI have the official 2.3.0 stable rvm ruby up yet? Or does it only have the release candidates and etc.? 

Ran the test suite with RVM - Ruby 2.3.0 locally and there are a few test failures and a fair amount of deprecation warnings that would be great to work on.

**Comment by segiddins** [comment]
Looks like a bunch of those warnings are from rspec-mocks

**Comment by ddrmanxbxfr** [comment]
@segiddins If you want to trigger a build in travis before 2.3 version works.

Try specifying 2.3.0. I've updated a few projects specifying this version and the test run great on travis :).

**Comment by ddrmanxbxfr** [comment]
@RochesterinNYC Yes 2.3 is up but with alias 2.3.0

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
