### PR TITLE
Fix Style/AccessModifierIndentation

### PR DESCRIPTION
**Pull request by esasse**

### CODE REVIEW

**Comment by segiddins** [comment]
I approve, let's see what andre thinks

**Comment by indirect** [comment]
Noooooooooooooooooooooooo unindent is the One True Way™ :stuck_out_tongue:

**Comment by esasse** [comment]
Then I'll send another PR disabling this rule, ok? 😀

**Comment by indirect** [comment]
Ok :grin:

**Comment by segiddins** [comment]
@esasse there should be an option to enforce @indirect's preferred style

**Comment by indirect** [comment]
I had no idea rubocop had an @indirect option :sweat_smile:

**Comment by segiddins** [comment]
Lol rubocop is incredibly configurable, and we can always add new settings ourselves :P

**Comment by esasse** [comment]
:+1: :smile:

**Pull request closed without merging**
