### PR TITLE
[CLI] Warn when running an outdated bundler version

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler/issues/4683.

The `send`s are super hacky but ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by indirect** [comment]
@bundlerbot r+

**Comment by agorf** [comment]
Isn't it a bit too much to get notifications for pre releases?

**Comment by colby-swandale** [comment]
see #6004

**Comment by agorf** [comment]
@colby-swandale Thanks

**Pull request merged**
