### PR TITLE
Fixed quotes in newgem.gemspec.tt

### PR DESCRIPTION
**Pull request by MOZGIII**
I always end up fixing quotes manually. Should it be like that by default, or is it not convenient?

### CODE REVIEW

**Comment by segiddins** [comment]
What is this fixing, exactly?

**Comment by MOZGIII** [comment]
It fixes unnecessary use of double quotes by replacing them with single quotes in `.gemspec` template.

**Comment by RochesterinNYC** [comment]
The current rubocop configuration enforces double quotes.

**Comment by indirect** [comment]
https://viget.com/extend/just-use-double-quoted-ruby-strings

**Comment by MOZGIII** [comment]
Provide me a way to choose then. Don't decide what I need to use for me.

**Comment by indirect** [comment]
@MOZGIII the Bundler gem generator is designed to be extremely minimal—the only options are for testing (rspec or minitest) and for license and code of conduct. If you want a gem generator with more options, I hear that Ore is pretty good: https://github.com/ruby-ore/ore

**Comment by MOZGIII** [comment]
@indirect I see, probably that would be the way to go for me.
However, `bundler` seems to be a "default" tool to create gems nowadays. I guess we should discuss things at least and try to fix whatever we can, so #4220.

**Pull request closed without merging**
