### PR TITLE
[Pristine] Allow passing a list of gems to pristine

### PR DESCRIPTION
**Pull request by segiddins**
In the process of testing this, I discovered and fixed a bug that had pristine git gems not get added files removed.

### CODE REVIEW

**Comment by segiddins** [comment]
@colby-swandale r?

**Comment by colby-swandale** [comment]
Do we want to print a warning to the user if they're giving a gem not in the Gemfile? Otherwise this LGTM

**Comment by segiddins** [comment]
@colby-swandale done

**Comment by colby-swandale** [comment]
🎉 @bundlerbot r+

**Pull request merged**
