### PR TITLE
Test bad rubygems binstub + locked bundler behavior

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was that we have no specs to demostrate the issue in #6595, nor to prove the fix in https://github.com/rubygems/rubygems/pull/2426.

### What was your diagnosis of the problem?

My diagnosis was that we need those specs.

### What is your fix for the problem, implemented in this PR?

My fix is to write the specs. They don't look very good though... :sweat_smile:.

### Why did you choose this fix out of the possible options?

I chose this fix because I couldn't think of any other ways to write them.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
This fails, as expected, since the fix is not yet on rubygems master...

**Comment by segiddins** [comment]
Should this test go in the rubygems repo?

**Comment by deivid-rodriguez** [comment]
Yeah, most likely...

**Comment by deivid-rodriguez** [comment]
Closing since I managed to write a spec in the rubygems PR that definitely feels more natural than what I'm doing here :+1:.

**Pull request closed without merging**
