### PR TITLE
Update vendored Molinillo to 0.5.0

### LINKED ISSUE #4376: Pathological Gemfile
```ruby
source 'https://rubygems.org'

gem 'middleman', '~> 3.4'
gem 'middleman-rouge'
gem 'rouge', git: 'https://github.com/jneen/rouge', ref: 'd989f18'
gem 'bootstrap-sass', '~> 3.3'
gem 'bh', '~> 1.3'

gem 'link-checker'
```

This takes forever to resolve.

### PR DESCRIPTION
**Pull request by segiddins**
See https://github.com/CocoaPods/Molinillo/releases/0.5.0
Closes #4376.

### CODE REVIEW

**Comment by segiddins** [comment]
@homu r+

**Comment by jrafanie** [comment]
@segiddins It looks like you have only the changed files and not added files.  For example, the dependency_graph directory is new.

https://github.com/CocoaPods/Molinillo/compare/0.4.5...0.5.0

Awesome work, I can't wait to try this out!  Thanks!

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
