### PR TITLE
Remove outdated advice

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I'm pretty sure you're no longer supporting Rails 2.3 users

### CODE REVIEW

**Comment by segiddins** [comment]
@indirect ?

**Comment by indirect** [comment]
We are in fact still supporting Rails 2.3 users. 😕 This seems like a good change for 2.0, though.

**Comment by deivid-rodriguez** [comment]
:open_mouth:

Should I open a PR to `2.0-dev`?

**Comment by indirect** [comment]
Sounds good!

**Pull request closed without merging**
