### PR TITLE
[Fetcher] Chunk API requests to stay under the request limit

### PR DESCRIPTION
**Pull request by segiddins**
\c @TimMoore

### CODE REVIEW

**Comment by segiddins** [comment]
I think all of the failures are due to a change in SSL certs?

**Comment by TimMoore** [comment]
@segiddins were you able to try it against any of the Gemfiles that were reported as not working?

**Comment by segiddins** [comment]
@TimMoore this is the error message `certificate /CN=you/DC=example not valid after 2015-02-05 14:11:06 UTC`

**Comment by TimMoore** [comment]
@segiddins yeah my comment wasn't related to the test failures... André already pushed a fix for those. Just wondering whether you were able to reproduce the original problem and confirm that this change fixes it.

**Comment by segiddins** [comment]
Yes, I can confirm that I can resolved the linked-to Gemfile with these changes.

**Comment by TimMoore** [comment]
Thanks, @segiddins!

**Comment by TimMoore** [comment]
This was included in `1-7-stable` as a35a5bdfce632b38e123bc6626692b91cdbcbf0a and will be merged up to 1.8 and master soon. :smile:

**Pull request closed without merging**
