### PR TITLE
dsl: not platforms

### PR DESCRIPTION
**Pull request by skull-squadron**
Fixes/implements #5183

### CODE REVIEW

**Comment by segiddins** [comment]
@indirect please share your thoughts on this PR / the linked-to issue

**Comment by indirect** [comment]
I would probably be okay with this as long as the option takes the form `all_platforms_except: [:jruby]`, and if you pass both `platforms:` and `all_platforms_except:` it raises an InvalidOption exception. How do you feel about it, @segiddins?

**Comment by segiddins** [comment]
I personally feel like it's DSL bloat, and the sort of thing that can cause bugs in combination with other options, just like how `with`/`without` can get confusing

**Comment by indirect** [comment]
The bugs when used in combination issue is why I'm only okay with this if combining :platform and :except_platform raises an exception. The unfortunate reality of gems that work on any platform except the one makes me think this is probably worth accepting.

**Comment by segiddins** [comment]
@indirect @colby-swandale we should probably come to a decision on this

**Comment by colby-swandale** [comment]
I'm on the fence about this. Is there a particular example that would highlight the need for this feature?

**Comment by colby-swandale** [comment]
Do we want to make a decision on this? @indirect @segiddins

**Pull request closed without merging**
