### PR TITLE
switch reject to select

### LINKED ISSUE #3799: 1.10.x installs dependencies in wrong order
I have a Gemfile that installs fine under 1.9.10 (also 1.7.11), but under 1.10.x it always fails to install the `scrypt` gem due to the `ffi` dependencies of this gem being installed _after_ rather than before. e.g:

```
Installing scrypt 1.2.1 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /opt/rubies/2.2.2/bin/ruby -rubygems /opt/rubies/2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=/opt/rubies/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/scrypt-1.2.1 RUBYLIBDIR=/opt/rubies/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/scrypt-1.2.1
rake aborted!
LoadError: cannot load such file -- ffi-compiler/compile_task

(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /opt/rubies/2.2.2/lib/ruby/gems/2.2.0/gems/scrypt-1.2.1 for inspection.
Results logged to /opt/rubies/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/scrypt-1.2.1/gem_make.out
Installing addressable 2.3.8
Installing activeresource 3.2.22
Installing request_store 1.1.0
Installing ffi-compiler 0.1.3
Installing awesome_nested_set 2.1.6
Using bundler 1.10.5
Installing authlogic 3.4.5
Installing ffi 1.9.10 with native extensions
```

Notice how it complains that the ffi gem is not found, but then installs it later.

Of course once `bundle install` fails the first time the `ffi` dependencies are now installed and a second `bundle install` completes without any problems.

I've posted the result of `bundle env` for both 1.10.5 and 1.9.10 here: https://gist.github.com/mhaylock/e25e5fb89f689432016d. The output is identical (except for the changed bundler version).

### PR DESCRIPTION
**Pull request by pducks32**
Fixes #3799 
Reject is clearly not the right method to use here, now I’m trying to figure out what state of mind I was in when I wrote something that is so obviously wrong.

### CODE REVIEW

**Comment by indirect** [comment]
Sounds like this commit is an excellent candidate for a test 😄

**Comment by pducks32** [comment]
:+1:

**Comment by pducks32** [comment]
Tests fail with old system. With this fix, they pass. :fireworks:

**Comment by segiddins** [comment]
:+1:

**Comment by segiddins** [comment]
(note to self -- cherry pick this back to stable)

**Comment by indirect** [comment]
Cherry-picked onto `1-10-stable`

**Pull request merged**
