### PR TITLE
Small fixes in man pages

### PR DESCRIPTION
**Pull request by sonalkr132**
Sorry about cosmetic PR. I just wanted to contributing something. :smile:

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
Do not skip CI please. (Even if this only involves changes to the man pages).

**Comment by RochesterinNYC** [comment]
Please amend the commit message without 'ci skip'?

**Comment by sonalkr132** [comment]
So, master is passing but this failed.. hmm! Interesting.

Hey, is it worth looking into? All the rest of failing builds have the same failing test:

```
1) bundle exec handles different versions in different bundles
     Failure/Error: expect(out).to eq("0.9.1")
     
       expected: "0.9.1"
            got: "bundler: failed to load command: rackup (/home/travis/build/bundler/bundler/tmp/gems/system/bin/rackup)"
     
       (compared using ==)
     # ./spec/commands/exec_spec.rb:133:in `block (2 levels) in <top (required)>'
```

**Comment by segiddins** [comment]
Yeah, that's an issue on master. Don't worry about it, well merge once master is fixed.

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu retry

**Pull request merged**
