### PR TITLE
[SourceList] Warn when adding a git source using the git procotol

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler/issues/3448.

### CODE REVIEW

**Comment by TimMoore** [comment]
Thanks! :blue_heart: 

Couple of things :smile: 

1. The tests are failing now
2. I was thinking we should say something different for people using the `github` shortcut, since they might not know that it's using a git protocol URL, or that they can redefine the shortcut

So I think the best place to issue the warnings is from `dsl.rb`, but it will take a bit of refactoring to make it possible to issue different warnings for github vs git.

**Comment by segiddins** [comment]
I don't have the time to do that sort of refactor at the moment, but I think I fixed the test failures.

**Comment by indirect** [comment]
Maybe in the meantime we should add a `github_https` option? Basically I would like to deprecate github immediately, but we can't. :(

**Comment by TimMoore** [comment]
I'd like to deprecate all built-in shortcuts. I think the translation logic needs to be explicit in the `Gemfile`, because we can never change it in Bundler without breaking things.

**Comment by indirect** [comment]
I feel like I'm probably okay with `https` shortcuts because they seem very unlikely to change in the future, and work for both public and private repos... but famous last words, maybe. :P 

Github is _such_ a common case that it seems completely valid to have that one built in, but I think we should drop everything else in 2.0, and document the shortcut DSL better.

**Comment by indirect** [comment]
Ready to merge this as soon as the tests pass and there is a conflig flag to disable it (and mention the config flag in the warning).

**Comment by segiddins** [comment]
Done

**Comment by pducks32** [comment]
The flags have to be set as true in settings.rb in order to be returned as true. It's fine for true because everything resolves to true but for false it will return `"false"` which is true.

**Comment by segiddins** [comment]
@indirect it looks like this has been cherry-picked into 1-99-dev already?

**Comment by indirect** [comment]
Yup, thanks!

**Pull request closed without merging**
