### PR TITLE
Warn when upgrading lockfile major version & error when major version is...

### PR DESCRIPTION
**Pull request by segiddins**
... too low

Closes https://trello.com/c/1jnFZSbb/101-ensure-that-bundler-1-x-will-abort-and-request-an-upgrade-if-bundled-with-is-2-0-or-greater.

\c @smlance

### CODE REVIEW

**Comment by indirect** [comment]
testssssssssssssss

**Comment by indirect** [comment]
Actually, can one of the tests include a lockfile with separate source sections as in #3593? I want to make sure that Bundler 1 hitting a Bundler 2 lockfile can still ask for an upgrade.

**Comment by segiddins** [comment]
Updated

**Comment by indirect** [comment]
\o/

**Pull request merged**
