### PR TITLE
[CLI] Print running command

### PR DESCRIPTION
**Pull request by segiddins**
This also has the nice side-effect of printing the bundler version ;)

### CODE REVIEW

**Comment by indirect** [comment]
@segiddins I think we only want to do this post-trampoline? or do you want to do it all the time?

**Comment by segiddins** [comment]
Why not all the time? It makes the output more helpful when running with aliases or bundler from a script

**Comment by indirect** [comment]
The CLI ethos is generally to do the work you asked for and only print information when it's unexpected or unknown. Because of that, I don't think we should echo the command you just ran back to STDOUT unless either 1) trampolining occurred or 2) --verbose mode is enabled.  FWIW, this would would resolve the second half of #4753 nicely.

**Comment by segiddins** [comment]
@indirect done

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
