### PR TITLE
Don't read global settings on a read-only FS with no $HOME

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler/issues/5371
This is an alternative to https://github.com/bundler/bundler/pull/5385

### CODE REVIEW

**Comment by davetron5000** [comment]
@jlambert121 do you want to try this in our system and see if it fixes the problem?

**Comment by jlambert121** [comment]
@segiddins This resolves #5371 for us

**Comment by jlambert121** [comment]
@segiddins Any way this can get merged so it makes it into the next point release of `1.14`?

**Comment by segiddins** [comment]
@jlambert121 it's just awaiting review

**Comment by indirect** [comment]
seems good 👍 @bundlerbot r+

**Pull request merged**
