### PR TITLE
[LazySpecification] Uniq dependencies in lockfile representation

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler/issues/3522, but I'm not convinced this is the right thing to do.

### CODE REVIEW

**Comment by indirect** [comment]
I mean, it's illegal to have multiple dependencies on the same gem now, but we'll still have to handle this one version of treetop for a long time. Not sure if there is a "right thing" beyond deleting the dupes :P

**Comment by indirect** [comment]
Also it's failing on Ruby 1.8, could you take a look?

**Comment by TimMoore** [comment]
It's a problem with the gemspec in an older version of the gem, so there's not really a way to fix it on the server.

**Comment by arthurnn** [comment]
https://rubygems.org/gems/treetop/versions/1.4.10 . We could ask the author to yank that version..

**Comment by segiddins** [comment]
@arthurnn we shouldn't make them yank the version just because the tooling on our end is faulty, especially when it's in our power to correct the  'issue'

**Comment by indirect** [comment]
Yanking that version doesn’t fix the problem. The gem file, and the gemspec inside it, are on thousands of servers and machines all over the world. That version is also locked in thousands of Gemfile.locks. Yanking would just break `bundle install` for all those people, and the problem would still happen every time they run `bundle install` on a machine that already has it installed.

**Comment by segiddins** [comment]
These spec failures on 1.8 are all totally unrelated

**Comment by indirect** [comment]
I fixed the specs! (Also, @segiddins fixed the specs.) Merging.

**Pull request merged**
