### PR TITLE
fixed 'critical' codereview warning about complex conditional

### PR DESCRIPTION
**Pull request by gavrieltal**
I went to codereview.com and made an adjustment to how a conditional statement was written because it was judged too complicated.

### CODE REVIEW

**Comment by colby-swandale** [comment]
Can you please fill in the pull request template with about what the problem is and what this is fixing.

**Comment by segiddins** [comment]
I’m not sure this is correct, you’re no longer checking the changes to the sources?

**Comment by gavrieltal** [comment]
Oops, I've totally jumped the gun on this one! My change is probably simply incorrect. It appears that this portion of the code is simply not covered by tests, which led me to think my submission was fine. I suppose I'll make writing some tests my next task. Thanks!

**Comment by segiddins** [comment]
I usually just run rspec on a single ruby version for specs I suspect cover what I’m changing, or the whole suite if I’m convinced I’ve broken something.

**Comment by colby-swandale** [comment]
This PR can't be merged as this is breaking functionality.

**Pull request closed without merging**
