### PR TITLE
[Lock] Add lock command

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler/issues/3437.

This is obviously missing specs, and I doubt I defined all the stuff correctly in `cli.rb`, but it's a start!

### CODE REVIEW

**Comment by segiddins** [comment]
Added some basic specs. Is there any other documentation that I need to update when adding a new command?

**Comment by indirect** [comment]
If you want to, you could write a man page. :grin:

**Comment by indirect** [comment]
oh, also the --local flag should talk about "downloading gemspecs" or "downloading gem metadata", rather than "downloading gems".

**Comment by cstrahan** [comment]
@indirect: Do you know if there's a rough ETA for when this feature will be released?

**Comment by indirect** [comment]
You can use it today by running "rake install" from a checkout of master, but I'd also like to push a prerelease by the end of the week.

**Comment by cstrahan** [comment]
@indirect: Awesome - thanks!

**Pull request merged**
