### PR TITLE
Fix rubygems 2.2+ compatibility

### PR DESCRIPTION
**Pull request by voxik**
This is follow up of #3237 including the fix to the last test failure on Ruby 1.8.7 and RubyGems 2.2.2.

### CODE REVIEW

**Comment by indirect** [comment]
Maybe I'm slow, but I'm still not sure what this is fixing. Can you explain why this is needed, now that RubyGems correctly loads .rb and .so files again?

**Comment by voxik** [comment]
The original explanation is in #3234:

> RubyGems allows since version 2.2 to reconfigure place, where binary
> extensions are stored. This might allow easier sharing of gems between
> various Ruby interpreters. It can be enabled by redefining
> Gem.default_ext_dir_for method.

And we are using this feature in Fedora [1]. The attached test case simulates this by the ```s.extension_dir = '#{ext_dir}'``` line.

To be precise, it is not about loading, the .rb and .so files are correctly loaded, but the $LOAD_PATH might not be cleaned correctly. This patch set narrows it by using RubyGems facilities.

http://pkgs.fedoraproject.org/cgit/ruby.git/tree/operating_system.rb#n103

**Comment by voxik** [comment]
Just to give you example, you probably assume that this is the directory structure of RubyGems:

~~~
/usr/local/ruby/2.2.1/extensions
/usr/local/ruby/2.2.1/gems
~~~

while it can be

~~~
/usr/lib64/gems/ruby/
/usr/ruby/gems/gems/
~~~

i.e. they don't have common prefix as the current code expects.

**Comment by indirect** [comment]
Got it. I understand now, thank you for explaining. And thank you for the patch!

**Comment by voxik** [comment]
Thanks!

**Pull request merged**
