### PR TITLE
Parallelize test suite (Take 2)

### PR DESCRIPTION
**Pull request by hsbt**
### What was the end-user problem that led to this PR?

This branch reduced test time of bundler.

### What was your diagnosis of the problem?

#7232 has a conflict with the current master branch.

### What is your fix for the problem, implemented in this PR?

I picked a commit for parallelized tests from #7232 

### Why did you choose this fix out of the possible options?

Fixed https://github.com/bundler/bundler/pull/7232

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Thanks for taking this! (I'll close the initial PR)

So, the reason I didn't follow up here and that I think this might cause unstability because our specs `Dir.chdir` back and forth and that's thread-global, so I saw some failures about that. And I don't know a good solution for that... Can you restart this two or three times to see if it reproduces?

**Comment by hsbt** [comment]
> Can you restart this two or three times to see if it reproduces?

Fmm. I never faced these issues on my macOS.

**Comment by hsbt** [comment]
Thanks!

>so I guess we can try this, and revert if it turns out to be problematic?

Agreed! we can revert this easily until the final release of the next version.

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
