### PR TITLE
Bump travis rubies

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was that hacks create confusion, even if they include TODO notes.

### What was your diagnosis of the problem?

My diagnosis was that we can should upgrade to the latest ruby releases to reduce the number of hacks we need to maintain.

### What is your fix for the problem, implemented in this PR?

My fix is to upgrade rubies and remove hacks.

### Why did you choose this fix out of the possible options?

I chose this fix because it's a good change.

### CODE REVIEW

**Comment by colby-swandale** [comment]
Restarted the build. Seems that the tgz for Ruby 2.6.2 wasn't up at the time of opening the PR.

**Comment by deivid-rodriguez** [comment]
I still need to restore some of the hacks. The `gem install --defaul etc:1.0.1` one is still needed :(

**Comment by deivid-rodriguez** [comment]
Hei!

I managed to get this green and removed all hacks. After closer examination, it might be `gem install etc:1.0.1 --default` (in general, `gem install <gem_with_extension> --default`), and not the ruby-core installer that was wrong. So what the hack was doing was "breaking" the installed specification, and thus preventing the default gem from being activated.

This sounds like a better fix. It needs a patch to `fileutils` that I also [proposed upstream](https://github.com/ruby/fileutils).

**Comment by deivid-rodriguez** [comment]
We should wait for the upstream PR, @hsbt could you have a look?

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
@deivid-rodriguez I released https://github.com/ruby/fileutils/releases/tag/v1.2.0 with https://github.com/ruby/fileutils/pull/34

**Comment by deivid-rodriguez** [comment]
Great! I opened https://github.com/bundler/bundler/pull/7068 to vendor that!

**Pull request merged**
