### PR TITLE
Prepare to release v1.16.1

### PR DESCRIPTION
**Pull request by hsbt**
I picked merge commits targeted v1.16.1 from https://github.com/bundler/bundler/milestone/56 .

### CODE REVIEW

**Comment by hsbt** [comment]
@indirect I skipped double check example at https://github.com/bundler/bundler/pull/6212/commits/cd57761237b105893e632ebb5d729e6c9c21285d

Because `rack-2.x` requires Ruby >= 2.2.

**Comment by indirect** [comment]
I approve of these changes 👍 @segiddins can you help us figure out how to generate a changelog for this?

**Comment by segiddins** [comment]
Changelog is generated by https://github.com/bundler/bundler-changelog

**Comment by hsbt** [comment]
@indirect @segiddins Thanks. I try to generate changelog on 1-16-stable branch. After that, I'm going to ping @indirect .

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
For future reference, manually cherry-picking to the stable branch is unnecessary. The patch release task will cherry pick all PRs tagged with the appropriate milestone

**Comment by hsbt** [comment]
@segiddins I see. In the next time, I try it.

**Pull request merged**
