### PR TITLE
Removed self-hosted YAML Serializer and PsychedYAML

### PR DESCRIPTION
**Pull request by hsbt**
### What was the end-user problem that led to this PR?

 It is not compatible with YAML spec of the standard library of Ruby.

I did revert a feature in last year: https://github.com/ruby/psych/pull/336

### What was your diagnosis of the problem?

`YAMLSerializer` was introduced from https://github.com/bundler/bundler/commit/bfd4be3756fa6bb43c263e303df2995ab0e7ace9

I'm not sure why that was required.

### What is your fix for the problem, implemented in this PR?

Removed `YAMLSerializer`. and use `YAML` provided by `pyched_yaml`.

### CODE REVIEW

**Comment by segiddins** [comment]
It is required since YAML is in a gem, and we load the list of plugins & settings before Bundler.setup, so using the Psych gem will mean no Bundler users can choose what version of pysch they use

**Comment by hsbt** [comment]
I know the problem that psych activation problem. But Bundler already uses psych directly. Users couldn't specify its version.

**Comment by deivid-rodriguez** [comment]
I thinking, what @segiddins said makes sense. But what @hsbt says makes sense too. Even though we have our own YAML implementation in order to not interfere with `yaml` / `psych` loading, we were actually activating `psych`. Shouldn't we use our custom implementation everywhere instead of using the default gem?

**Comment by hsbt** [comment]
FYI: https://bugs.ruby-lang.org/issues/13847

**Pull request closed without merging**
