### PR TITLE
Fix outdated regression from cc355865

### LINKED ISSUE #4979: bundle outdated (1.13.0) not listing all outdated gems
I've arrived in a new project and something weird was happening. I install Ruby (a little outdated, version 2.0.0) and I installed the latest version of Bundler (1.13.0), but the list of all outdated gems is really small compare with other college (he has installed Bundler 1.12.5).

Here is my output when I run bundle 1.13.0:

```
$ bundle -v
Bundler version 1.13.0

$ bundle outdated
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...............................................................................................

Outdated gems included in the bundle:
  * rspec-activemodel-mocks (newest 1.0.3, installed 1.0.1) in groups "test, development, ci"
  * hashery (newest 2.1.2, installed 2.1.1)
  * pdf-reader (newest 1.4.0, installed 1.3.3)
  * ttfunk (newest 1.2.2, installed 1.2.0)
```

And the output after I installed bundle 1.12.5:

```
$ bundle -v
Bundler version 1.12.5

$ bundle outdated
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...............................................................................................

Outdated gems included in the bundle:
  * actionpack-xml_parser (newest 2.0.0, installed 1.0.1) in group "default"
  * activerecord-session_store (newest 1.0.0, installed 0.1.0) in group "default"
  * aws-sdk (newest 2.5.11, installed 2.2.37, requested ~> 2.2) in group "default"
  * aws-sdk-v1 (newest 1.66.0, installed 1.64.0, requested < 2.0) in group "default"
  * bootstrap-sass (newest 3.3.7, installed 2.3.2.2, requested ~> 2.3.2) in group "default"
  * cancancan (newest 1.15.0, installed 1.8.4, requested ~> 1.8) in group "default"
  * capistrano (newest 3.6.1, installed 3.4.0, requested ~> 3.2) in group "development"
  ...
  ...
  ...
```

Any ideas? I expect to have the same behaviour between both versions.

### PR DESCRIPTION
**Pull request by chrismo**
Refactoring of @lucasmazza fix w/ specs. 

The only existing spec coverage was essentially integration level and
there was no way either @lucasmazza or myself could find a way to
simulate the bug context.

I extracted some of the code out of outdated into Definition and
SpecSet and added unit specs to those extracted bits.

Fixes #4979

### CODE REVIEW

**Comment by chrismo** [comment]
@lucasmazza your feedback is welcome ... I think this gets us the test coverage we need.

**Comment by lucasmazza** [comment]
@chrismo this looks great, and thanks a ton for taking this over :)

**Comment by chrismo** [comment]
@indirect can haz @homu?

**Comment by indirect** [comment]
@chrismo hey so good news! I finally finished putting up our own Homu at @bundlerbot, and he knows to listen to you! try it out by saying `r+` at the bot. 😁  You can also see the bot UI and instructions at http://bundlerbot-homu.herokuapp.com.

:tada:

**Comment by indirect** [comment]
(omg I put the bot name and r+ in the same comment :joy: sorry, next time though!)

**Comment by indirect** [comment]
Oh man, even weirder. I accidentally activated `try` mode, which we never normally even use. Go ahead and r+ yourself, @chrismo. :)

**Comment by chrismo** [comment]
@bundlerbot r+

**Comment by chrismo** [comment]
there's an outstanding homu check that I think is gumming up the works. Going to close and make a separate PR.

**Comment by chrismo** [comment]
See #5176

**Pull request closed without merging**
