### PR TITLE
[2.0] [Resolver] Use the GVP for major updates in 2.0

### PR DESCRIPTION
**Pull request by segiddins**
Thanks so much for the contribution!
To make reviewing this PR a bit easier, please fill out answers to the following questions.

### What was the end-user problem that led to this PR?

The problem was @chrismo wants to start delegating all sorting to the GVP.

### What was your diagnosis of the problem?

My diagnosis was to start doing that in 2.0.

Closes https://github.com/bundler/bundler/issues/5993

### What is your fix for the problem, implemented in this PR?

My fix adds a feature flag.

### CODE REVIEW

**Comment by segiddins** [comment]
This seems to break `bundler/inline` and I'm not quite sure why yet

**Comment by segiddins** [comment]
This ought to pass now!

r?

**Comment by indirect** [comment]
@bundlerbot r+

**Comment by chrismo** [comment]
thx a bunch @segiddins

**Pull request merged**
