### PR TITLE
Merge 2-0-stable into master and get specs passing

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem is that master is still running specs against older rubies even if 2-0-stable is not. That means quite a lot of PRs are blocked because they don't pass tests on old rubies.

### What was your diagnosis of the problem?

My diagnosis is that we need to officially start bundler 3 development.

### What is your fix for the problem, implemented in this PR?

My fix is to merge the 2-0-stable branch into master, bump the version to 3.0.0.dev in `version.rb`, stop testing against old rubies and get specs passing.

### Why did you choose this fix out of the possible options?

I chose this fix because it gets master green while including everything currently in the 2-0-stable branches.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I got specs passing locally against 2.6, let's see what TravisCI says for other rubies.

Also, we have delayed deprecations to bundler 3 but I see no reason to not release the pending major deprecations on a future 2.x release. But we can discuss this separately, make a PR to 2-0-stable if we decide to do it, and then forwardport it to master.

**Comment by colby-swandale** [comment]
Let me sort out the deprecation issue, which should make the merge into master a lot easier.

**Comment by deivid-rodriguez** [comment]
Sure!

**Comment by hsbt** [comment]
@deivid-rodriguez How about the status of this branch? I'm okay to merge this into master branch.

**Comment by deivid-rodriguez** [comment]
I'll try to get this ready to merge today! :+1:

**Comment by deivid-rodriguez** [comment]
I created #6933 to 2-0-stable to sort out deprecations. Then I can forward port those changes here and rebase this PR.

**Comment by deivid-rodriguez** [comment]
Closing in favor of #6957, @colby-swandale will manually cherry-pick any commits he needs from here.

**Pull request closed without merging**
