### PR TITLE
Track changes from ruby core master

### PR DESCRIPTION
**Pull request by hsbt**
### What was the end-user problem that led to this PR?

I'm going to merge https://github.com/bundler/bundler/pull/7274. But the ruby-core source has some of the changes for bundler source.

### What is your fix for the problem, implemented in this PR?

ruby core team fixed them:

* Removed circular require warning at `shared_helper.rb`
* Support test at GitHub Actions, It helps that bundler will migrate Actions from Azure Pipelines too.
* Fixed broken examples at ruby core repository

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Thank you @hsbt, go ahead and merge when CI is green :+1:.

**Comment by deivid-rodriguez** [comment]
Rubocop is failing because the double negation style (`!!`) is not used in the bundler repo.

**Comment by hsbt** [comment]
I will fix them later.

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
