### PR TITLE
[Downloader] Print underlying error in HTTPError

### LINKED ISSUE #5577: Useless error messages when bundler can't connect
```
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
```

This error is not useful in any way. It should at least specify whether connection was closed, refused, timed out or had HTTP error code

### PR DESCRIPTION
**Pull request by segiddins**
Closes #5577

### CODE REVIEW

**Comment by segiddins** [comment]
Will update tests and fix spacing if this looks good

**Comment by colby-swandale** [comment]
👍

**Comment by segiddins** [comment]
@colby-swandale r?

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Pull request merged**
