### PR TITLE
Unset UI when yielding to other programs

### LINKED ISSUE #3710: Gem listing broken in Bundler 1.10.x
Previously `bundle exec gem list` worked as expected:

```
[jenkins@ip-10-194-8-243 omnibus]$ bundle --version
Bundler version 1.9.9
[jenkins@ip-10-194-8-243 omnibus]$ bundle exec gem list

*** LOCAL GEMS ***

bundler (1.8.3)
chef-sugar (3.1.0)
cleanroom (1.0.0)
ffi (1.9.8)
ffi-yajl (1.4.0)
ipaddress (0.8.0)
libyajl2 (1.2.0)
mime-types (1.25.1)
mixlib-cli (1.5.0)
mixlib-config (2.2.1)
mixlib-log (1.6.0)
mixlib-shellout (1.6.1)
mixlib-versioning (1.0.0)
ohai (7.4.1)
omnibus (4.0.0)
omnibus-software (4.0.0)
rake (10.4.2)
ruby-progressbar (1.7.5)
systemu (2.6.5)
thor (0.19.1)
uber-s3 (0.2.4)
wmi-lite (1.0.0)
```

Now running the same command in any version of Bundler in the 1.10.x series returns nothing:

```
[jenkins@ip-10-194-8-243 omnibus]$ bundle --version
Bundler version 1.10.2
[jenkins@ip-10-194-8-243 omnibus]$ bundle exec gem list
[jenkins@ip-10-194-8-243 omnibus]$
```

### PR DESCRIPTION
**Pull request by segiddins**
closes a few issues

closes #3710.

\c @indirect

### CODE REVIEW

**Comment by indirect** [comment]
It worries me a bit that we now have to know to explicitly unset UI anytime we're about to lose control of execution—this is just begging for future bugs to be written by me when I've forgotten about this, or future pull requesters who don't know that this is a requirement.

Is there any way that we can automate this so that it doesn't have to be done explicitly?

**Comment by segiddins** [comment]
@indirect not really...

**Comment by indirect** [comment]
:( I cry tears for the future bugs that this will cause :'(

**Comment by e2** [comment]
@indirect - it's not that bad. I'm more worried about using Gem::SilentUI as a base for the proxy (the way SilentUI silences stderr is a sin), instead of subclassing Gem::StreamUI and letting the errors go through (for the sake of debugging issues). 

It also seems Bundler.rubygems.ui and Bundler.ui have more of a relationship then they should (Bundler.ui doesn't need to be ever cleared, but Bundler.rubygems.ui should - because it's used by RubyGems).

Just my 2 cents.

I wanted to add a few tests, but I couldn't work out how to do them well without too much potential breakage.

Anyway, fantastic job guys keeping Bundler working so well, despite the insane amount of edge cases of constantly changing codebases and environments!

**Pull request merged**
