### PR TITLE
Backport `GemHelper` changes for #7108

### PR DESCRIPTION
**Pull request by colby-swandale**
I'm working on getting https://github.com/bundler/bundler/pull/7108 into the v2.0.2 release but that code has not been kept up to date over time (i'm not sure why i haven't been doing this). Trying to cherry-pick the changes to `GemHelper` is proving to be not super fun to deal with. Instead, i'm just going to copy/paste the current file & specs into `2-0-stable`

There doesn't seem to be any breaking changes, so this should be ok to perform.

### CODE REVIEW

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
Maybe this times out because there's no bors configuration on this branch?

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot retry

**Comment by colby-swandale** [comment]
I don't really have time to worry about Bors, i'm just going to merge this with Github.

**Pull request merged**
