### PR TITLE
maybe we can install missing system gems?

### PR DESCRIPTION
**Pull request by indirect**
(this seems to be the current leading reason for CI job failures)

### CODE REVIEW

**Comment by segiddins** [comment]
I don't see how this will help things? Also, it failed on CI.

**Comment by indirect** [comment]
It passed except for Rubocop, which failed it on `Metrics/ModuleLength: Module has too many lines. [368/363]`. I thought we disabled that?

**Comment by indirect** [comment]
To elaborate: the current most common reason for CI jobs to fail is the error message `you need to rm -rf tmp`. That error message is only printed when Bundler is unable to find rake inside the test system gems. I'm adding logic to delete the test system gems and try to install them again, one time, and then fail if that doesn't work. Since the code in question only needs to successfully run once at the beginning of the test suite, it seems like this will reduce or eliminate our current occasional CI failures.

**Comment by segiddins** [comment]
Please do disable that rule -- then feel free to 👍🏻

**Comment by indirect** [comment]
@homu r=segiddins

**Comment by indirect** [comment]
(this is why r= is useful!)

**Pull request merged**
