### PR TITLE
Raise permission error when config file isn't readable

### LINKED ISSUE #3858: Permission denied @ rb_sysopen - /home/git/gitlab/.bundle/config
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/settings.rb:210:in `initialize'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/settings.rb:210:in `open'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/settings.rb:210:in `set_key'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/settings.rb:31:in `[]='
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/cli/install.rb:92:in `run'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/cli.rb:162:in `install'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/cli.rb:10:in `start'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/bin/bundle:20:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/bin/bundle:18:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.5
    Rubygems  2.2.3
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [i686-linux]
    Git       1.9.1

Bundler settings

    frozen
      Set for your local app (/home/git/gitlab/.bundle/config): "1"
    path
      Set for your local app (/home/git/gitlab/.bundle/config): "vendor/bundle"
    without
      Set for your local app (/home/git/gitlab/.bundle/config): "development:test:mysql:aws:kerberos"
    disable_shared_gems
      Set for your local app (/home/git/gitlab/.bundle/config): "1"
    jobs
      Set for your local app (/home/git/gitlab/.bundle/config): 4

### PR DESCRIPTION
**Pull request by segiddins**
Closes #3858

### CODE REVIEW

**Comment by indirect** [comment]
I'm surprised the aligned case statement passes RuboCop :P

@homu r+

**Comment by segiddins** [comment]
@homu r-

**Comment by indirect** [comment]
lol good catch

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
