### PR TITLE
Warn if RUBYGEMS_GEMDEPS env. variable is set

### LINKED ISSUE #3656: Warn if RUBYGEMS_GEMDEPS is set
Should we do this so there's less confusion when rubygems and bundler clash?

### PR DESCRIPTION
**Pull request by agis-**
Closes #3656.

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻

**Comment by indirect** [comment]
I'd like the message to use Bundler.ui.warn to say something like "The RUBYGEMS_GEMDEPS environment variable is set. This enables RubyGems' experimental Gemfile mode, which may conflict with Bundler and cause unexpected errors. To remove this warning, unset RUBYGEMS_GEMDEPS."

**Comment by agis-** [comment]
@indirect Much better indeed! Updated.

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
