### PR TITLE
Bundler repo was merged in RubyGems repo

### PR DESCRIPTION
**Pull request by hsbt**
https://github.com/rubygems/rubygems/pull/3166#issuecomment-597583663

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
This seems like a good clear enough approach to me :+1:.

Only thing I would add is maybe to list the new `CONTRIBUTING.md` for `bundler` inside the `README.md` file so people that were used to reporting issues and submitting PRs to the old repo can learn how to do that against the new repo.

**Comment by colby-swandale** [comment]
Do we need to delete the entire codebase? Could we just archive the repository in Github and update the README to point to rubygems instead?

**Comment by indirect** [comment]
Yes, I think archive is better. That way we can keep a README with a link, but block new issues or PRs.

**Comment by hsbt** [comment]
I'm okay to use archive feature. And I will put `Bundler is now maintained in the [rubygems/rubygems](https://github.com/rubygems/rubygems) repository.` to the top of README.md.

**Review by colby-swandale — APPROVED** [review]

**Comment by colby-swandale** [comment]
Sounds good, thank you @hsbt !

**Comment by deivid-rodriguez** [comment]
I would do both: delete the whole code base _and_ archive the repo. But I'm good with just archiving if you prefer so :+1:.

**Pull request merged**
