### PR TITLE
[Travis] Run specs against an installed RubyGems

### PR DESCRIPTION
**Pull request by segiddins**
Given the "install bundler with rg" shenanigans that are on RG master, I want to make sure they wont break the bundler specs.

### CODE REVIEW

**Comment by olleolleolle** [comment]
@segiddins Can we "retry" this build?

**Comment by segiddins** [comment]
@olleolleolle the failures look legit though

**Comment by segiddins** [comment]
Only failures now are 2 things in the clean env spec, and the trampoline specs on RGV=master

**Comment by segiddins** [comment]
Spent an hour trying to get the trampoline specs to pass and I'm utterly stumped

**Comment by segiddins** [comment]
This should become possible once https://github.com/bundler/bundler/pull/5804 is merged

**Comment by segiddins** [comment]
This should 🍏 now. Please review.

**Comment by hsbt** [comment]
We dropped to use Travis now on https://github.com/rubygems/rubygems/. I will close this.

**Pull request closed without merging**
