### PR TITLE
Setup RuboCop

### PR DESCRIPTION
**Pull request by segiddins**
I will continue to make progress on enabling more rules as time passes, but I think this should be a good start, and lays a strong foundation.

\c @bundler/core

### CODE REVIEW

**Comment by indirect** [comment]
I'm okay with this

**Comment by segiddins** [comment]
no clue why the specs didn't run...

**Comment by indirect** [comment]
I think they’re waiting for workers that are on other commits right now?

**Comment by segiddins** [comment]
@indirect no I meant the failures, but I think I just accidentally reset a file

**Comment by andremedeiros** [comment]
@indirect that totally looks nothing like you.

**Comment by andremedeiros** [comment]
:+1:

**Comment by segiddins** [comment]
:ship: :ship: :fireworks:

**Pull request merged**
