### PR TITLE
[Path] Store lockfile paths relative to the root, not the gemfile path

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler/issues/4966, but i'm wondering if this will break anything else?

### CODE REVIEW

**Comment by the-teacher** [comment]
Thanks for a fast reaction. I hope it will solve the problem.

**Comment by indirect** [comment]
@segiddins I feel like we go back and forth on this every teary or two, but if all the tests pass I guess we’re slowly approaching something that actually works?

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu retry

**Comment by segiddins** [comment]
@homu retry

**Pull request merged**
