### PR TITLE
Add a setting for forcing only the ruby platform

### PR DESCRIPTION
**Pull request by segiddins**
See https://github.com/bundler/bundler/pull/4895.

Closes https://github.com/bundler/bundler/issues/4813.

### CODE REVIEW

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
@indirect shouldn't there be docs for the new setting?

**Comment by indirect** [comment]
@segiddins there are separate checkboxes for docs in the 1.14 ticket, so it didn't seem like a blocker for this PR ¯\_(ツ)_/¯

**Comment by lynnco** [comment]
Made it explicit https://github.com/bundler/bundler/issues/4853#issuecomment-251206284

**Pull request merged**
