### PR TITLE
Always check that subcommands succeeded

### PR DESCRIPTION
**Pull request by segiddins**
@indirect @smlance I need help finishing this up

### CODE REVIEW

**Comment by indirect** [comment]
What are we doing here? Just testing the exit codes for subcommands?

**Comment by segiddins** [comment]
@indirect yeah. Generally, the idea is to make the tests more robust by forcing us to explicitly call out the subprocesses that are expected to fail, just like we would have to for normal method invocations

**Comment by segiddins** [comment]
If I finish this up, you good with it @indirect ?

**Comment by indirect** [comment]
yeah, I'm good with this.

**Pull request closed without merging**
