### PR TITLE
Ci against latest versions

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

My local tests don't match Travis environment, since I use ruby 2.5.1 but travis doesn't.

### What was your diagnosis of the problem?

My diagnosis was that we should be testing against the latest patch level releases.

### What is your fix for the problem, implemented in this PR?

My fix is to update versions.

### Why did you choose this fix out of the possible options?

I chose this fix because I can't think of another fix.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
A couple of entries failed. Not sure if they're surfacing a problem in the code or the tests, but looks like there's something going on.

**Comment by deivid-rodriguez** [comment]
I removed the commits breaking the build. I'll open issues for them but this one is ready!

**Comment by hsbt** [comment]
@deivid-rodriguez Great! Thanks for your work.

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
