### PR TITLE
Remove `package --all` for Bundler 2.0

### LINKED ISSUE #4501: Remove `package --all` for Bundler 2.0

### PR DESCRIPTION
**Pull request by bronzdoc**
closes #4501
@segiddins @indirect @LynnCo

### CODE REVIEW

**Comment by LynnCo** [comment]
Looks like this PR is both bringing 2.0-dev up to date with master -- and the `package --all` changes?

**Comment by LynnCo** [comment]
Bringing 2.0-dev up to date is likely the part that's causing the merge conflicts, and given that there's a 1000 (!) commit difference between the branches, I doubt it will be simple to resolve :/

**Comment by LynnCo** [comment]
Here that is -> https://github.com/bundler/bundler/pull/4564

**Comment by segiddins** [comment]
@bronzdoc you should be able to cherry-pick your changes atop the current 2-0-dev now

**Comment by bronzdoc** [comment]
Will do thanks!

**Comment by bronzdoc** [comment]
I don't think this is relevant anymore, package.rb don't exist in 2-0-dev

**Pull request closed without merging**
