### PR TITLE
Refactors.

### PR DESCRIPTION
**Pull request by ryanfox1985**
What was the end-user problem that led to this PR?
no problem

What was your diagnosis of the problem?
My diagnosis was the possibility to reduce useless code and make the ruby code more readable following the Rubocop style guide.

What is your fix for the problem, implemented in this PR?
My fix it's just refactors.

### CODE REVIEW

**Comment by ryanfox1985** [comment]
22 lines less.

**Comment by colby-swandale** [comment]
Can you please fill-out the PR template https://github.com/bundler/bundler/blob/master/.github/PULL_REQUEST_TEMPLATE.md. It really helps us try to understand the intent to your change. You might also want to rework your commit messages a bit better to communicate what they're fixing/changing.

**Comment by ryanfox1985** [comment]
@colby-swandale ok, I rewrote the PR subject.

**Comment by deivid-rodriguez** [comment]
Hei @ryanfox1985! Thanks for contributing! :heart:

As @colby-swandale points out, it's hard to understand the intention of your changes at the moment, even with the new PR description. It seems that you are driven by the number of lines this PR removes, but that's not really a justification for changing anything. Short code is not necessarily better than long code...

Right now this PR is a mixture of style changes and instance variable extractions put together in a single commit. What do you think about getting started with the style changes you want applied, and opening separate PRs enabling the corresponding rubocop rule(s) globally?

**Comment by ryanfox1985** [comment]
ok I understand, I will submit new PRs applying separated changes.

**Pull request closed without merging**
