### PR TITLE
Remove unnecessary executable bit from gem template.

### PR DESCRIPTION
**Pull request by voxik**
This file is not executable at all, since the shebang line contains just placeholder for template expansion.

### CODE REVIEW

**Comment by olleolleolle** [comment]
@voxik Oh, you need to inform RuboCop about this being a good life choice:

```
Offenses:
lib/bundler/templates/Executable:1:1: W: Lint/ScriptPermission: Script file Executable doesn't have execute permission.
#!/usr/bin/env <%= Bundler.settings[:shebang] || RbConfig::CONFIG["ruby_install_name"] %>
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^```

**Comment by olleolleolle** [comment]
In `.rubocop.yml`, add a section of this:

```yaml
Lint/ScriptPermission:
  Exclude:
    - 'lib/bundler/templates/Executable'
```

**Comment by voxik** [comment]
Heh, good one :) going to update my PR.

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Pull request merged**
