### PR TITLE
Document changelog handling for releases

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was that I'm not sure how to release bundler.

### What was your diagnosis of the problem?

My diagnosis was that the part about how to handle the changelog is the most unclear step.

### What is your fix for the problem, implemented in this PR?

My fix is to _guess_ how we are currently managing that, and document that.

### Why did you choose this fix out of the possible options?

I chose this fix because it improves our docs, while starting a PR at the same time where I can incorporate feedback if this is not the right way.

While I read the release scripts, I also added a couple of improvements to the `rake release:open_unreleased_prs` task.

### CODE REVIEW

**Comment by indirect** [comment]
Nice! I haven’t released a minor since we started doing this, so @segiddins and @colby-swandale are probably the right reviewers 🙂 r+ from me!

**Comment by deivid-rodriguez** [comment]
Thanks @indirect, I'll wait for feedback from the latest releasers :)

**Comment by deivid-rodriguez** [comment]
I'll wait for feedback a few more days. If I don't get any feedback I'll merge this PR and start working on the release assuming this is the right way :)

**Comment by deivid-rodriguez** [comment]
I started working on the changelog for the next version :)

**Comment by deivid-rodriguez** [comment]
It sound like there's no reviews, so I guess I'll just go ahead with this way?

**Comment by indirect** [comment]
👍🏻

**Comment by indirect** [comment]
@bundlerbot r+

**Pull request merged**
