### PR TITLE
Parallelize test suite

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was that tests are slow.

### What was your diagnosis of the problem?

My diagnosis was that an easy improvement would be to run them in parallel.

### What is your fix for the problem, implemented in this PR?

My fix is to add the `parallel_tests` gem, and use that to run specs.

### Why did you choose this fix out of the possible options?

I chose this fix because it requires virtually no changes and it speeds up tests around 30%. Further work could be done to equally balance test processes by runtime, to make it faster.

### CODE REVIEW

**Comment by hsbt** [comment]
I prefer this solution. How about the improvement of time duration for test execution?

**Comment by deivid-rodriguez** [comment]
Hi @hsbt!

Balancing test times would involve using the `RuntimeLogger` formatter and managing the `tmp/parallel_runtime_rspec.log` through TravisCI cache. See https://github.com/grosser/parallel_tests#even-test-group-run-times.

Do you prefer that I work on that before merging this PR, or as a further improvement on a separate PR?

**Comment by hsbt** [comment]
I'm okay to merge this. Let's try to work for further improvement after that.

**Comment by deivid-rodriguez** [comment]
Ok, thank you!

@bundlerbot r=hsbt

**Comment by deivid-rodriguez** [comment]
There's one randomly failing spec that's most likely caused by this PR. I'll investigate it.

**Comment by deivid-rodriguez** [comment]
Closed in favor of #7317.

**Pull request closed without merging**
