### PR TITLE
[RubyGemsIntegration] Use .stubs_for when available

### PR DESCRIPTION
**Pull request by segiddins**
Depends on https://github.com/rubygems/rubygems/pull/1239.

### CODE REVIEW

**Comment by segiddins** [comment]
This won't work because `stubs_for` will bypass the array of specs we pass in to `all=` because `@@stubs_by_name[name]` will return `nil` and then RubyGems will use it's own search paths, instead of restricting itself to bundler's approved gems.

**Comment by indirect** [comment]
Restarting the build for the latest RubyGems master...

**Comment by segiddins** [comment]
I don't know why travis is showing this as having error?

**Comment by segiddins** [comment]
This is now green. Let's :shipit: ?

**Comment by indirect** [comment]
Yay! 🚢

**Pull request merged**
