### PR TITLE
Doc: Add a note on how to dive into the code with Pry

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Follow up of https://github.com/bundler/bundler/pull/4919#issuecomment-242706463.

[Preview DEVELOPMENT.md](https://github.com/JuanitoFatas/bundler/blob/6667a9d9a1fd7f83b4d262ff00b933f8574a974f/DEVELOPMENT.md#development-setup)

### CODE REVIEW

**Comment by indirect** [comment]
@homu r+

**Comment by indirect** [comment]
@homu retry

**Comment by segiddins** [comment]
We can't merge stuff with `[ci skip]` in the title

**Comment by segiddins** [comment]
@homu retry

**Comment by segiddins** [comment]
@homu retry

**Pull request merged**
