### PR TITLE
[CompactIndex] Disable when openssl is in fips mode

### LINKED ISSUE #4989: FIPS compatibility
bundler will fail when run in FIPS mode because it uses MD5:

```
$ bundle
md5_dgst.c(80): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!
Aborted
```

Two changes are needed to fix this (mostly in the vendor code):
- It must be possible to use an alternative to `Digest::MD5.hexdigest` using a cipher that is permitted by FIPS-140-2 (e.g., `Digest::SHA256.hexdigest`).  
  - This will affect the files:
    - `lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb`
    - `lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb`
    - `lib/bundler/vendor/thor/lib/thor/runner.rb`
    - `lib/bundler/source/rubygems/remote.rb`
- `require "digest/md5"'`  should not be required by default, since that will also fail on a system with FIPS mode enabled.
  - This affects the files:
    - `lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb`
    - `lib/bundler/vendor/thor/lib/thor/runner.rb`

### PR DESCRIPTION
**Pull request by segiddins**
Should close #4989

### CODE REVIEW

**Comment by segiddins** [comment]
Of course, Ruby < 2 doesn't have that constant

**Comment by trevor-vaughan** [comment]
@segiddins Validated that this change works properly on a system with FIPS enabled.

As stated in #4989, it is a LOT slower when resolving dependencies but it does work correctly which should meet the requirements of anyone in a FIPS restricted environment.

**Comment by breisig** [comment]
@segiddins Any update of getting this merged?

**Comment by segiddins** [comment]
@indirect r?

**Comment by indirect** [comment]
@bundlerbot r+

**Pull request merged**
