### PR TITLE
[2.0] Add a feature flag to prefer gems.rb to Gemfile

### PR DESCRIPTION
**Pull request by segiddins**
With `prefer_gems_rb` set (by default on 2.0), Bundler will prefer a `gems.rb` that is in the same directory as a `Gemfile`

### CODE REVIEW

**Comment by indirect** [comment]
I am r+, but this needs a rebase.

**Comment by segiddins** [comment]
No it doesn't? It merges cleanly

**Comment by indirect** [comment]
oh noooo I was tricked by bundlerbot. @bundlerbot r+

**Comment by segiddins** [comment]
Rebased. @bundlerbot r=indirect

**Pull request merged**
