### PR TITLE
Handle quotes in PATH

### LINKED ISSUE #4323: bundle install not detecting git
On Windows 10, 64bit. When trying to install a gem via git I get the error documented below. git is installed and in path.

Part of gemfile:
`gem 'activeadmin', github: 'activeadmin'`

console output:
```

   C:\Users\user\rails_project>path
   PATH=C:\Entwicklung\Ruby22\bin;"C:\Entwicklung\PortableGit\cmd";

   C:\Users\user\rails_project>git version
   git version 2.7.2.windows.1

   C:\Users\user\rails_project>bundle install
   ...
   Errno::ENOENT No such file or directory - git clone ...
   Environment

    Bundler   1.11.2
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]
    GEM_HOME  C:/Entwicklung/Ruby22/lib/ruby/gems/2.2.0
    GEM_PATH  C:/Entwicklung/Ruby22/lib/ruby/gems/2.2.0;C:/Users/user/.gem/ruby/2.2.0
    Git       not installed

```

### PR DESCRIPTION
**Pull request by segiddins**
Fixes #4323 and adds tests

### CODE REVIEW

**Comment by indirect** [comment]
If I'm understanding this correctly, this change does not handle entries that use quotes around the path separator, which is the specific case that quotes are required for. For example, `PATH=C:\ruby\bin;"C:\stuff;other stuff\bin"`.

**Comment by segiddins** [comment]
@indirect correct, but it fixes the issue that was reported ;)

**Comment by indirect** [comment]
@segiddins so now we're just knowingly waiting for the first person who has a path containing `File::PATH_SEPARATOR`, because it will be completely broken for them. :joy: :sob:

**Comment by segiddins** [comment]
@indirect but no more broken than it is now. this is an improvement without regression. feel free to add a disabled test for the other scenario or hold up this PR until someone contributes that other half

**Comment by indirect** [comment]
@segiddins yeah, yeah. I'm :+1: on this once the tests pass.

**Comment by segiddins** [comment]
Ought to pass now

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
