### PR TITLE
Use newer list interface

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was that our specs emit a lot of deprecations about the list command.

### What was your diagnosis of the problem?

My diagnosis was that we are using the deprecated interface to the list command everywhere.

### What is your fix for the problem, implemented in this PR?

My fix is to start using the new interface. If we don't use it ourselves, how could we be in a position to tell our users to start using it?

### Why did you choose this fix out of the possible options?

I chose this fix because we should do this, at same point, and doing it now simplifies enabling deprecations.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I still need to update the documentation of list to document the preferred interface, but given the amount of changes this required I'd like to make sure we are in the same page about this deprecation. The new interface is superior and way more clear, but I feel some of the old shortcuts could stay, such as `bundle config` as a shortcut to `bundle list`, or `bundle config <key> <value>` as a shortcut to `bundle config set <key> <value>`?

**Comment by deivid-rodriguez** [comment]
@janpio The azure build seems to be hanging? It sounds like a problem with Azure not being able to pickup the latest code after a force-push... maybe?

This is ready for a review, by the way. I updated the `bundle config` docs to document the new interface to the config command, and alos fixed an error message where the recommended command was not clear and would not work as specified. See https://github.com/bundler/bundler/pull/6974/commits/4bf058b56c8d9ab37f22dbd4a0c70b11a1950d2d.

**Comment by deivid-rodriguez** [comment]
> @janpio The azure build seems to be hanging? It sounds like a problem with Azure not being able to pickup the latest code after a force-push... maybe?

Actually disregard this, looks like it was still running. Now it finalized properly :+1:.

**Comment by janpio** [comment]
Hm, Azure Pipelines taking longer than Travis is of course not good, I will try to get a few PRs in fixing test failures on Windows which should hopefully speed up the build.

**Comment by indirect** [comment]
Awesome, thanks!

@bundlerbot r+

**Pull request merged**
