### PR TITLE
More rubocop_todo cleanup

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by simi** [comment]
I see no benefit and git mess only. :(

**Comment by indirect** [comment]
@simi Bundler was written for years and years without any consistent code style, and now it is very hard for contributors to know if their pull requests will be accepted or rejected based on style. By making RuboCop enforce style, contributors can easily know in advance if their style matches the project style. It's a big improvement.

**Comment by indirect** [comment]
@homu r+

**Comment by simi** [comment]
Sure I understand. I just prefer "increment style" of those changes = change style while you're changing the code to keep history. It will be worth it to notice the bundler ruby style in https://github.com/bundler/bundler/blob/master/DEVELOPMENT.md at least.

**Comment by segiddins** [comment]
@simi we already do, since running `rake spec` will also run rubocop.

**Pull request merged**
