### PR TITLE
Allow conflicts for gems resolved via `gemspec`

### PR DESCRIPTION
**Pull request by segiddins**
Needs to be cleaned up, but this demonstrates the general idea

### CODE REVIEW

**Comment by segiddins** [comment]
@indirect thoughts on this?

**Comment by indirect** [comment]
I like refactoring out Source::Gemspec! If I am understanding the feature, I think I'm okay with it. Can you add brief documentation for what this change allows, with at least one example?

**Comment by segiddins** [comment]
Where would documentation for this behavior go? In the Gemfile docs?

**Comment by indirect** [comment]
wherever we document `gemspec` seems reasonable, so Gemfile(5)?

**Comment by segiddins** [comment]
@indirect added docs

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
