### PR TITLE
disable_shared_gems independent from current path setting

### PR DESCRIPTION
**Pull request by bobishh**
Hi there, in this PR i tried to fix some strange behaviour. - Bundler doesn't respect global config for disable_shared_gems setting. Feel free to point me things you might want to change! <3 <3 <3

### CODE REVIEW

**Comment by indirect** [comment]
Thanks for the patch! Can you explain how you are using Bundler that led you to notice this, and why the way it works now is confusing?

**Comment by bobishh** [comment]
Sure, the reason for PR is such behaviour - http://showterm.io/40f712b4af501b91ca2e2, if global config is intended to be default why can't I combine 2 global config values? It seems like "disable_shared_gems" variable is dependent on "path" variable which seems unintuitive. @brainopia mentioned this at first

**Comment by indirect** [comment]
Well, `disable_shared_gems` is an internal config, and Bundler officially does not support enabling shared gems with path. So you're trying to do something we don't support, and don't have tests for. :)

**Comment by bobishh** [comment]
What about adding support for that then? I wrote few specs that emulate behaviour shown in term session above, and they pass, nothing seem to be broken with it. And it simply omits setting disable_shared_path based on path if it is already present in global config. It might be the rare case but someone might want it, at least few of my friends do.

**Comment by indirect** [comment]
We used to support this mode (in Bundler 0.9) and found that it created hard to understand and hard to debug situations. We decided against allowing it on purpose to avoid those problems, and so we do not support or recommend the configuration that you are describing here.




Bundler 2, coming sometime in the future, will share .gem files across all bundles on the system, even with --path.

**Comment by bobishh** [comment]
Ok. Closing the PR then.

**Pull request closed without merging**
