### PR TITLE
Ensure that manpages are always built when running specs

### LINKED ISSUE #5657: bundle exec command specs breaking on local dev environment
Gist: https://gist.github.com/colby-swandale/6173b0221ad91a2168ef27b5c08dd089

Whenever i run the `spec/commands/exec_spec.rb` tests either it be the individual file or the entire suite, some of the specs will not pass for me.

\cc @segiddins

### PR DESCRIPTION
**Pull request by segiddins**
Fixes #5657 by ensuring manpages are always built, much like how `Spec::Rubygems.setup` ensures gem dependencies are always installed

\c @colby-swandale

### CODE REVIEW

**Comment by colby-swandale** [comment]
thanks for fixing this!

**Comment by segiddins** [comment]
r?

**Comment by indirect** [comment]
looks good! @colby-swandale, you can do the r+ honors, since you beat me to reviewing this :)

**Comment by colby-swandale** [comment]
🎉 @bundlerbot  r+

**Pull request merged**
