### PR TITLE
[Resolver] Consider locked dependencies first

### LINKED ISSUE #5095: `bundle update foo` can not find compatible versions
I may be missing something, but my understanding is that if `bundle install` works fine, then a subsequent `bundle update foo` should never fail  (assuming no changes to the `Gemfile`). At worst it should resolve `foo` to whatever version is already in the `Gemfile.lock`, no?

I've attached my `Gemfile` & `Gemfile.lock`. To reproduce my issue, `bundle && bundle update ember-rails`. For some reason it's trying to upgrade Rails to v5 and (rightfully) failing:

```
$ bundle -v
Bundler version 1.13.5
$ bundle
[...]
Bundle complete! 193 Gemfile dependencies, 389 gems now installed [...]
$ bundle update ember-rails
[...]Resolving dependencies.............................................................
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    active_model_serializers (~> 0.8.0) was resolved to 0.8.3, which depends on
      activemodel (>= 3.0) was resolved to 5.0.0.1, which depends on
        activesupport (= 5.0.0.1)

    jquery-rails was resolved to 1.0.1, which depends on
      railties (~> 3.0) was resolved to 3.0.0, which depends on
        activesupport (= 3.0.0)
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rack (~> 1.6)

    jquery-rails was resolved to 4.0.1, which depends on
      railties (>= 4.2.0.beta) was resolved to 5.0.0.1, which depends on
        actionpack (= 5.0.0.1) was resolved to 5.0.0.1, which depends on
          rack (~> 2.0)
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 4.2.7)

  In Gemfile:
    rails (~> 4.2.7)

    jquery-rails was resolved to 0.1.1, which depends on
      rails (~> 3.0.0.rc)
```

[Gemfile_with_lock.zip](https://github.com/bundler/bundler/files/533835/Gemfile_with_lock.zip)

PS: I've made no attempt to minimize my `Gemfile` to get that effect, let me know if I should.

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler/issues/5031
Closes #5095 

\c @marcandre @indirect

### CODE REVIEW

**Comment by indirect** [comment]
This seems reasonable, is there an easy way to test this out?

**Comment by segiddins** [comment]
@indirect I used the bundle in the linked issue. I also should probably run this against the benchmarks

**Comment by indirect** [comment]
My past experience has been that any change to the resolver will regress unless there is a test for it... worst case, put that gemfile into the realworld specs, but we need something for sure.

**Comment by segiddins** [comment]
I don't know for sure how to test this, other than coming up with a reasonable reproduction case

**Comment by segiddins** [comment]
Realworld spec added

**Comment by indirect** [comment]
@bundlerbot r+

**Pull request merged**
