### PR TITLE
Extract kernel require, so we can extend it

### PR DESCRIPTION
**Pull request by arthurnn**
I find myself wanting to instrument this require calls, however to patch this code in bundler
is not super easy as Bundler.require is a big method. We can extract the Kernel.require to a method
and make it easier to extend it.

review @indirect 
Thoughts? Maybe you might have a better idea to accomplish what I need. let me know

thanks

### CODE REVIEW

**Comment by segiddins** [comment]
Why not just instrument `Kernel.require` directly?

**Comment by indirect** [comment]
Instrumenting just this usage of Kernel.require gives you an instant gem-level overview of how long requiring takes, so I can understand wanting it. I remember a long ago PR to add a `bundle profile` that printed timing info for every gem in your bundle. @arthurnn, are you gong to release your work as `bundle-profile` so everyone can use it? :D

**Comment by arthurnn** [comment]
bundle-profile,that sounds like a good idea.. i am definitely interested . i am working in some optimizations on rubygems.org, so i patched this locally, but i will see what else i could push to a profile command. that would be awesome.

**Comment by indirect** [comment]
@arthurnn I'll accept this if it extracts all of [lines 66-98](https://github.com/arthurnn/bundler/blob/arthurnn/extract_require/lib/bundler/runtime.rb#L66-L98) into a method named `require_dependency` or something like that... then it's both a genuine improvement to the code and lets you instrument each gem getting required. :)

**Comment by segiddins** [comment]
@arthurnn can we close this until you've addressed @indirect's comments?

**Pull request closed without merging**
