### PR TITLE
Use Molinillo for Dependency Resolution

### PR DESCRIPTION
**Pull request by segiddins**
This PR moves bundler's dependency resolution to [Molinillo](https://github.com/CocoaPods/Molinillo), a library that I've been developing for [CocoaPods](http://cocoapods.org) over the past few months thanks to Stripe's support.

\c @indirect @alloy @Who828

### CODE REVIEW

**Comment by alloy** [comment]
Just a quick update, I have been using this branch as my main bundler installation for past month and it seems to work so flawless that I completely forgot until @segiddins just mentioned it to me again. So it appears to work well for me :+1:

**Comment by indirect** [comment]
That's great to hear! I'm hoping to have this merged and released as a pre gem this weekend. :)

**Comment by sferik** [comment]
:fireworks:

**Comment by voxik** [comment]
Just wondering, have you considered to use [libsolv](https://github.com/openSUSE/libsolv)? Not that I am expert on dependency resolution, but at least, it has the longest history in solving dependency issues.

**Pull request merged**
