### PR TITLE
Make SSL Verify Mode a number setting

### PR DESCRIPTION
**Pull request by goughy000**
Needed to turn off SSL verify mode, most the code seemed to be there but the setting was being cast to a string which caused it to fail. Added it to NUMBER_KEYS and it's ok now

### CODE REVIEW

**Comment by indirect** [comment]
Thanks! Could you add a test for this?

**Comment by agis-** [comment]
LGTM

**Comment by goughy000** [comment]
Thanks :)

**Comment by indirect** [comment]
Thank you!

**Pull request merged**
