### PR TITLE
use rubocop --parallel option

### PR DESCRIPTION
**Pull request by walf443**
### What was the end-user problem that led to this PR?
No

### What is your fix for the problem, implemented in this PR?

My fix enable rubocop's parallel option.
This may improve rubocop's test time.

### CODE REVIEW

**Comment by walf443** [comment]
I researched rubocop time between [After](https://travis-ci.org/bundler/bundler/builds/279138403?utm_source=github_status&utm_medium=notification) and [Before](https://travis-ci.org/bundler/bundler/builds/279124385?utm_source=github_status&utm_medium=notification)

This changes about avg 6.3960 sec improvement.

| ID | after | before | diff |
| -- | ------ | ----- | ---- |
| 1  | 26.827866 | 32.300205 | 5.4723 |
| 2  | 29.034466 | 32.220597 | 3.1861 |
| 3  | 27.435544 | 32.264259 | 4.8287 |
| 4  | 26.395648 | 34.645119 | 8.2495 |
| 5  | 29.448851 | 33.711343 | 4.2625 |
| 6  | 25.464041 | 37.840813 | 12.3768 |

**Comment by colby-swandale** [comment]
Thanks! @bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot retry

**Pull request merged**
