### PR TITLE
[Resolver] Properly calculating amount constrained when the dep is lo…

### PR DESCRIPTION
**Pull request by segiddins**
…cked

Closes https://github.com/bundler/bundler/issues/3687.

\c @indirect @Who828

### CODE REVIEW

**Comment by segiddins** [comment]
(We really really need to have a suite of performance tests for the resolver...)

**Comment by indirect** [comment]
How can you tell this fixes it? Running against the Gemfile from #3687?

**Comment by segiddins** [comment]
Yup. (Removing the one private git gem)

**Comment by indirect** [comment]
Oh hey, this actually broke a spec that tests the resolver: https://travis-ci.org/bundler/bundler/jobs/64611631#L2104

**Comment by segiddins** [comment]
Heh, the new behavior is actually more correct!

**Comment by indirect** [comment]
Hah. Excellent. :)

**Comment by segiddins** [comment]
Spec failures are unrelated. Merging.

**Pull request merged**
