### PR TITLE
[CLI::Gem] Store the VERSION in a separate file

### PR DESCRIPTION
**Pull request by segiddins**
### What was the end-user problem that led to this PR?

The problem was the `bundle gem` template generates a `gemspec` file that manipulates `$LOAD_PATH`, which can lead to unexpected behavior.

### What was your diagnosis of the problem?

My diagnosis was we should continue storing the version in a single place, but one that is not a ruby file.

### What is your fix for the problem, implemented in this PR?

My fix puts the version in a `VERSION` file in the top level of the generated repo. That file is then read by both the gemspec and `version.rb`.

### Why did you choose this fix out of the possible options?

I chose this fix because the alternatives seemed like string parsing `version.rb`, and string parsing is best avoided.

This will also make tooling around version management easier, as it's easier to manipulate a plain text file that contains only the version than an entire ruby file.

### CODE REVIEW

**Comment by colby-swandale** [comment]
Do you have any examples of this unexpected behavior?

**Comment by indirect** [comment]
@colby-swandale in my experience, it has been any code that evaluates gemspecs (especially from path gems) and then does not actually activate that gem after examining the gemspec. At that point, it's too late, and the gem's `lib` is already on the load path because of having evaluated the gemspec.

**Comment by hsbt** [comment]
What's advantage to use `require_relative` instead of this?

**Comment by deivid-rodriguez** [comment]
I was beaten by `LOAD_PATH` causing unexpected behaviour in https://github.com/bundler/bundler/issues/6058 (although my surprise was not the `LOAD_PATH` being modified, but the gemspec being read at all), so I'm happy to try these solutions!

**Comment by segiddins** [comment]
@indirect r?

**Comment by indirect** [comment]
No more load path seems great, but won't `require_relative` give us the same advantage? Is the separate file to make it easier to programatically increment, or something?

**Comment by segiddins** [comment]
> Is the separate file to make it easier to programatically increment, or something?

Exactly that. No having to write regular expressions to update the gem version

**Comment by segiddins** [comment]
Any feedback on this?

**Comment by deivid-rodriguez** [comment]
I would personally fix the problem by using `require_relative` and separately discuss the best way for new gems to specify their version going forward.

Maybe a separate file aligns us with the standard ".ruby-version" file version managers use, so we could call it `.gem-version` or something like that. But I feel this is part of a separate discussion from the "avoid $LOAD_PATH manipulation in gemspecs" issue.

**Pull request closed without merging**
