### PR TITLE
[Definition] Fail when installing in frozen mode & gemspec deps have changed

### LINKED ISSUE #5264: bundler: failed to load command: pod after running bundle install for CocoaPods repo
Hi! We recently started running into this issue shown in full in this travis log, and we can't seem to pin it to a change local to CP configuration:

https://travis-ci.org/CocoaPods/CocoaPods/jobs/184771287

You can reproduce it locally by doing the following (using mac system ruby, which is 2.0.0p648):
1. Clone the CocoaPods repo
2. Checkout master (currently e379f7f45ece67bf6fc4feff3f396808b11f0e8a)
3. Run `bundle install --path=vendor/bundle`
4. Run `bundle exec pod env`

The last command results in the following error:
```
/Users/basher/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb:336:in `block (2 levels) in replace_gem': cocoapods is not part of the bundle. Add it to Gemfile. (Gem::LoadError
```

Thanks for your help!

### PR DESCRIPTION
**Pull request by segiddins**
Closes #5264 

- [x] Specs

### CODE REVIEW

**Comment by olleolleolle** [comment]
I got interested in [this test failure](https://github.com/bundler/bundler/blob/master/spec/install/parallel/spec_installation_spec.rb#L50).

Can this be it?

`Bundler::ParallelInstaller::SpecInstallation` now needs to forward `#full_name` to its `@spec`'s `#full_name`:

```ruby
def full_name
  @spec.full_name
end
```

---

Here's a Specification with `#full_name`: https://github.com/bundler/bundler/blob/master/lib/bundler/remote_specification.rb

**Comment by segiddins** [comment]
Rebased and added a spec, but this is still breaking something existing in the deploy spec

**Comment by segiddins** [comment]
Wahoo, this should finally work! Please carefully review the changes to Path -- they're the only thing I'm scared of here, @indirect .

**Comment by indirect** [comment]
These changes look pretty reasonable to me. With passing tests, I'm r+ on this.

**Comment by segiddins** [comment]
@bundlerbot r=indirect

**Pull request merged**
