### PR TITLE
Fix multi source unlocking

### PR DESCRIPTION
**Pull request by TimMoore**
Sometimes, it's disappointing to compare the amount of time it took to track down a problem with the amount of code it took to fix it :smile:

### CODE REVIEW

**Comment by indirect** [comment]
The build passes and this appears to resolve the issue, so I'm going to merge it.

**Comment by tamird** [comment]
@indirect could you cut a release containing this fix?

**Comment by indirect** [comment]
@tamird does this fix your issue? You can check by cloning this repo, running `git checkout 1-8-stable`, and then `rake install`, which will build and install Bundler from source.

**Comment by indirect** [comment]
Released 1.8.3 with this fix.

**Pull request merged**
