### PR TITLE
Get 2-0-dev green again

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler/issues/4719
\c @indirect

### CODE REVIEW

**Comment by indirect** [comment]
@homu r+

**Comment by indirect** [comment]
Issue title still aspirational, it seems 😝

**Comment by segiddins** [comment]
Only because Travis uses RVM and I don't  :P
@homu r=indirect

**Comment by segiddins** [comment]
Welp, https://github.com/bundler/bundler/pull/4915/commits/91d9637c33987868df1c02b59d394fe990ac9a80 only took me like an hour to figure out 😭 
@homu r=indirect

**Pull request merged**
