### PR TITLE
[Exec] Allow executables to exit non-zero via at_exit

### PR DESCRIPTION
**Pull request by segiddins**
@indirect this is a pretty bad bug :(

### CODE REVIEW

**Comment by indirect** [comment]
ooooh shit, yes it is. did we push this 1.11, or is it only in the 1.12 pres so far?

**Comment by indirect** [comment]
also, pls backport to 1-12-stable thx

**Comment by segiddins** [comment]
Only 1.12 I think. Please r?

**Comment by indirect** [comment]
is Travis broken? it's still pending :/

@homu r+

**Comment by segiddins** [comment]
@indirect its not broken -- I made another PR, and then fixed up a rubocop offense on this one after

**Comment by segiddins** [comment]
I'll back port and release an rc.2 once https://github.com/bundler/bundler/pull/4441 is merged

**Pull request merged**
