### PR TITLE
[Runtime] Fix the ordering of the load path when there are dependencies

### LINKED ISSUE #4482: uninitialized constant Sass::Script after upgrading to 1.12.0
With our rails application, I noticed an error after I upgraded to 1.12.0 (accidentally I must say):

```
bundle exec rails c
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:91:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'sass-rails'.
Gem Load Error is: uninitialized constant Sass::Script
Did you mean?  ScriptError
Backtrace for gem load error is:
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/helpers.rb:12:in `<top (required)>'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails.rb:8:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails.rb:8:in `<top (required)>'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass-rails.rb:1:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass-rails.rb:1:in `<top (required)>'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:88:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:88:in `block (2 levels) in require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:83:in `each'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:83:in `block in require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:72:in `each'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:72:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler.rb:102:in `require'
/home/siebert/code/platform/config/application.rb:6:in `<top (required)>'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:82:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:82:in `preload'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:143:in `serve'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
Bundler Error Backtrace:
 (Bundler::GemRequireError)
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:87:in `block (2 levels) in require'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:83:in `each'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:83:in `block in require'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:72:in `each'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:72:in `require'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler.rb:102:in `require'
        from /home/siebert/code/platform/config/application.rb:6:in `<top (required)>'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:82:in `require'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:82:in `preload'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:143:in `serve'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

My bundle env is at https://gist.github.com/siebertm/7a13e63b2b16527fa282eabe3b95a7ad

The same Gemfile(.lock) works on 1.11.2 without any problems. Also, downgrading to 1.12.2 makes everything work again. Reproduced on 2 machines, so my feeling is that it's got to to with 1.12.0

Any ideas what I might do to help figure out whats going on?

### PR DESCRIPTION
**Pull request by segiddins**
It was previously getting reversed

closes #4482

### CODE REVIEW

**Comment by segiddins** [comment]
Ugh this is failing since the rubygems lib is in there on CI but not locally. I'll try and update the spec

**Comment by segiddins** [comment]
@indirect @RochesterinNYC please review, I'd like to ship this in 1.12.1 tonight

**Comment by indirect** [comment]
@homu r+

**Comment by indirect** [comment]
@segiddins looks like this is building red right now

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r+

**Comment by vipulnsward** [comment]
Looks like we are seeing this here- https://travis-ci.org/rails/rails/builds/126817069
Would love to see a new release. Thanks for the fix!

**Comment by segiddins** [comment]
Already had released 1.12.1 ;)

**Comment by vipulnsward** [comment]
Hmm, I still see the issue. Here's how Gemfile.lock changes from 1.11.2 to 1.12.1
https://gist.github.com/vipulnsward/c54ea4b376d1c30434fa329b51557986
Went through https://github.com/bundler/bundler/blob/master/CHANGELOG.md can't find anything apart from https://github.com/bundler/bundler/issues/4482 that could cause this.

**Comment by segiddins** [comment]
@vipulnsward please open a new issue

**Pull request merged**
