### PR TITLE
[Inline] Add bundler/inline to allow using Bundler without a Gemfile

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler-features/issues/47.

Enables scripts such as the following to work on their own, as long as bundler is installed:

```ruby
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'json'
  gem 'nap', require: 'rest'
  gem 'cocoapods', '> 0.pre'
end

puts Pod::VERSION
```

### CODE REVIEW

**Comment by segiddins** [comment]
Those 2 spec failures look like API timeouts to me.

**Comment by TimMoore** [comment]
I restarted the failing jobs.

**Comment by indirect** [comment]
Er, just to double-check, in the example script, you would still have to `require 'cocoapods'`, right?

**Comment by segiddins** [comment]
@indirect right now, using `bundler/inline`'s `gemfile`  method will also call `require` on the environment, just as if you'd somehow done a `require 'bundler/require'` afterwards.

**Comment by indirect** [comment]
There is no `bundler/require`, though. :) There's a `bundler/setup`, but that means you still need to explicitly call `require`.

**Comment by segiddins** [comment]
Ah my bad. It'd be like calling `require 'bundler/setup'; Bundler.require`

**Comment by indirect** [comment]
In order to encourage reasonable growth of a script into a multi-file app, can we leave out the `Bundler.require` part? Requiring the world up front is an anti-pattern that I wish Rails didn't encourage. :'(

**Comment by segiddins** [comment]
André and I just agreed that not auto-requiring in this circumstance would make users do a redundant `gem 'foo'` && `require 'foo'` for every gem that they include in the inline gemfile, which is probably worse than (slightly) encouraging en-mass requiring.

**Comment by indirect** [comment]
Can you document this somewhere, preferably with examples? :D (Maybe even on the Bundler website?!)

**Comment by andremedeiros** [comment]
This is really nice! :+1:

**Comment by cstrahan** [comment]
@segiddins Excellent! This new feature should greatly simplify the way we do Ruby packaging in NixOS. Thanks!

**Comment by schneems** [comment]
> Requiring the world up front is an anti-pattern

Do you have more thoughts on this written down somewhere? I would think we want to preload to take advantage of CoW with forking webservers.

**Comment by cstrahan** [comment]
@schneems I believe the anti-pattern that @indirect is referring to is the fact that - assuming you don't require what you use - your tests (as just one example) can't be run without requiring everything up front. So while the act of requiring everything up front is great (with respect to CoW), you should still require what you need where you need it.

**Comment by segiddins** [comment]
This is not really a relevant discussion for this particular feature, which is targeted at single-file scripts.

**Comment by schneems** [comment]
Thank you @cstrahan, makes sense. Thanks for the feature @segiddins i cede this thread back to you.

**Pull request merged**
