### PR TITLE
Adding graphs explaining binstubs

### PR DESCRIPTION
**Pull request by rubymorillo**
Added a paragraph that explains what binstubs is and how it works, per feedback from @arbonap.

Thanks so much for the contribution!
To make reviewing this PR a bit easier, please fill out answers to the following questions.

### What was the end-user problem that led to this PR?

The problem was...without an explanation of what binstubs is and what it does, it's difficult for 
users to understand where to apply the binstubs command. Shout out to @arbonap for calling this out!

### What was your diagnosis of the problem?

My diagnosis was...to take a wonderful explanation given by @indirect about what binstubs are and turn it into a paragraph! 😄 

### What is your fix for the problem, implemented in this PR?

My fix...is two intro paragraphs in the "DESCRIPTION" section, before going into what the command does.

### Why did you choose this fix out of the possible options?

I chose this fix because...explanations help users 👍

### CODE REVIEW

**Comment by indirect** [comment]
@rubymorillo one tiny tweak:

> with the additional benefit of linking the binstub inside of an application to the exact version of the gem

Using bundle exec or binstubs are two different ways to get the same result of the exact version, so maybe instead "offering a file that can be run directly that will always run the correct version of the gem used by the application", or something like that?

**Comment by segiddins** [comment]
Test failures: https://travis-ci.org/bundler/bundler/jobs/255783590#L719

**Comment by rubymorillo** [comment]
@segiddins @indirect made the recommended changes on the file; I'm a newb at this PR stuff so let me know if there's any lingering issues!

**Comment by indirect** [comment]
Looks great. Thanks, @rubymorillo!

@bundlerbot r+

**Pull request merged**
