### PR TITLE
[Gemfile] Add a post_install hook

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler-features/issues/83.

This time, I wrote specs!

### CODE REVIEW

**Comment by TimMoore** [comment]
amaze :sparkle: 

(just waiting for specs to pass before merging)

**Comment by segiddins** [comment]
Let's wait to merge this until we're sure we want it.

**Comment by rzane** [comment]
Hi @segiddins, this looks really good. You're a speed deamon. I was working on this myself, pushed, and realized you also took a stab. I like that you passed some useful info to the block.

My version is a little different, so maybe we can work together and take the best aspects from both. Here's what I did differently:
1. It adds pre and post install hooks (before_install / after_install)
2. You can add as many hooks as you want.
3. When passed a string, it'll execute it as a shell command, which is what NPM does.

See https://github.com/rzane/bundler/tree/hooks.

**Comment by maclover7** [comment]
@segiddins Nice PR! For the other hooks we are going to be creating, do you suggest we follow a similar process?

**Comment by indirect** [comment]
This PR spurred some discussion, and we decided to implement hooks in a slightly different way. We're working on it!

**Comment by RochesterinNYC** [comment]
@indirect where is the discussion regarding this PR or the context on how hooks were implemented in a slightly different way? Thanks.

**Pull request closed without merging**
