### PR TITLE
[Vendor] Dont change the load path to require vendored gems

### LINKED ISSUE #3492: require gem_tasks results in uninitialized constant error
Prior to 1.9 one could add a `require 'bundler/gem_tasks'` to their Rakefile to load a set of bundler related Rake tasks. Starting with 1.9.0 this results in the following error:

```
rake aborted!
NameError: uninitialized constant Bundler
/home/yorickpeterse/.gem/ruby/2.2.0/gems/bundler-1.9.0/lib/bundler/vendor/thor-0.19.1/lib/thor/command.rb:1:in `<top (required)>'
/home/yorickpeterse/.gem/ruby/2.2.0/gems/bundler-1.9.0/lib/bundler/vendor/thor-0.19.1/lib/thor/base.rb:1:in `<top (required)>'
/home/yorickpeterse/.gem/ruby/2.2.0/gems/bundler-1.9.0/lib/bundler/vendor/thor-0.19.1/lib/thor.rb:2:in `<top (required)>'
/home/yorickpeterse/.gem/ruby/2.2.0/gems/bundler-1.9.0/lib/bundler/vendored_thor.rb:4:in `<top (required)>'
/home/yorickpeterse/.gem/ruby/2.2.0/gems/bundler-1.9.0/lib/bundler/gem_helper.rb:1:in `<top (required)>'
/home/yorickpeterse/.gem/ruby/2.2.0/gems/bundler-1.9.0/lib/bundler/gem_tasks.rb:1:in `<top (required)>'
/tmp/test/Rakefile:1:in `<top (required)>'
LoadError: cannot load such file -- bundler/gem_tasks
/tmp/test/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
```

To reproduce, create a directory and add the following files to it:

```
# Rakefile
require 'bundler/gem_tasks'
```

```
# Gemfile
source 'https://rubygems.org'

gemspec
```

```
# test.gemspec
Gem::Specification.new do |gem|
  gem.name = 'test'
end
```

This should give the following structure:

```
$ ls
Gemfile  Rakefile  test.gemspec
````

Running `rake -T` will now produce the above error.

### PR DESCRIPTION
**Pull request by segiddins**
Properly fixes us uses of autoload in thor

Closes #3492

\c @andremedeiros

### CODE REVIEW

**Comment by TimMoore** [comment]
Travis CI doesn't seem to have picked this up for some reason.

**Comment by TimMoore** [comment]
Looks like we haven't added `1-9-stable` to the list of branches to include... I'll fix.

**Comment by segiddins** [comment]
Ah I think I mentioned that omission a few nights ago... I can just add it to the `.travis.yml` in this PR? This fix might warrant cutting `1.9.1`?

**Comment by TimMoore** [comment]
I'm not sure if it would read it from the PR, but in any case already done!

**Comment by TimMoore** [comment]
Might need to toggle this closed & open again to trigger it.

**Comment by TimMoore** [comment]
OK, it's building now.

**Comment by TimMoore** [comment]
The changes look good in any case, so if the build passes as expected then I'm happy to merge.

**Pull request merged**
