### PR TITLE
Remove psyched_yaml

### LINKED ISSUE #4825: Remove bundler/psyched_yaml in Bundler 2

### PR DESCRIPTION
**Pull request by segiddins**
Closes #4825 
See https://github.com/bundler/bundler/issues/4856

### CODE REVIEW

**Comment by indirect** [comment]
is that the only place we ever required the file? do we still need to require psych, or are we completely independent of it now for Bundler itself?

**Comment by segiddins** [comment]
RubyGems will handle loading psych internally in these places

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
Blocked on https://github.com/bundler/bundler/pull/4928

**Comment by segiddins** [comment]
@homu retry

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu retry

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
I can't seem to get that one failure to reproduce locally

**Comment by segiddins** [comment]
Got it to reproduce, leading me to question how any other Ruby was passing at all. `¯\_(ツ)_/¯`

**Comment by indirect** [comment]
I love the fix for Rails versions :joy:

@homu r+

**Pull request merged**
