### PR TITLE
[Resolver] Allow mis-matches in bundler requirements, and warn

### PR DESCRIPTION
**Pull request by segiddins**
\c @smlance @indirect

### CODE REVIEW

**Comment by indirect** [comment]
Can we avoid an extra loop over all the deps by warning around line 164?

**Comment by segiddins** [comment]
Not really, since we won't know if we've actually activated said spec at that point.

**Comment by indirect** [comment]
Alright then, @homu r+

**Comment by segiddins** [comment]
Failing spec fixed

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu retry

**Pull request merged**
