### PR TITLE
Fix DepProxy == method

### PR DESCRIPTION
**Pull request by ChrisBr**
### What was the end-user problem that led to this PR?
After implementing a new hash table strategy in JRuby, bundle is broken for JRuby. The problem is caused that the ``==`` method in bundler does not check the class of the ``other`` object. This causes problems now when calling ``==`` on object other than DepProxy or nil.

 jruby/jruby#5280 travis-ci/travis-ci#9994

### What was your diagnosis of the problem?
The code crashes for anything other than DepProxy class or nil.

### What is your fix for the problem, implemented in this PR?
Checking now also that other class is the same as self.

### CODE REVIEW

**Comment by colby-swandale** [comment]
Forgive the ignorance but i don't understand how this is a Bundler issue. If JRuby is incorrectly returning objects it shouldn't, patching the application code to go around that bad behavior seems backwards to me. Shouldn't the change in JRuby that is causing this be reverted or patched instead?

**Comment by ChrisBr** [comment]
> Forgive the ignorance but i don't understand how this is a Bundler issue. If JRuby is incorrectly returning objects it shouldn't, patching the application code to go around that bad behavior seems backwards to me. Shouldn't the change in JRuby that is causing this be reverted or patched instead?

Hey @colby-swandale, thanks for your response. JRuby is not incorrectly returning objects, it was just hidden before because of checking hash AND object equality, so it never checked object equality when hash is different. We will change JRuby to the old behavior but I think the code in bundler is just wrong. E.g. this will crash and not return false as it is expected:

```
proxy = Bundler::DepProy.new('foobar', 'java')
proxy == "string"
```

**Comment by colby-swandale** [comment]
Thanks for clearing that up, i don't know where i got the idea of an incorrect object being returned from. 😞

**Comment by ChrisBr** [comment]
> Thanks for clearing that up, i don't know where i got the idea of an incorrect object being returned from.

No worries! Should I add tests for this? Altough I didn't find specs for dep_proxy so far ...

**Comment by segiddins** [comment]
Yes, please do add a test for the bug this is trying to fix

**Comment by ChrisBr** [comment]
@segiddins @colby-swandale added tests, please have a look again!

**Comment by segiddins** [comment]
Thanks for this!

Just a note that the prior definition of `hash` was technically acceptable. `eql?` implies `hash` equality, but its OK (though undesirable) for `!eql?` objects to have the same `hash` value.

@bundlerbot r+

**Pull request merged**
