### PR TITLE
Add gem_analystics_reporter

### PR DESCRIPTION
**Pull request by Speculate7**
This PR refers to [#1335](https://github.com/rubygems/rubygems.org/issues/1335).

#### Summary
The purpose of this gem is to capture information about which gems are being used and who is using it. This gem also captures the version and system information of the user during the bundler install process (before the download request goes to the Fastly server) and sends that data to the ruby gems server to be represented with [Librato](https://github.com/librato).

#### Options for development
 - This gem builds on the `fetcher.rb` gem. A call to the `gem_analytics_reporter` may likely be implemented there or vice versa.
- Creating an `opt-out` option in `bundler install` commands
- Creating `gem_analytics_reporter.gemspec` and `rspec` test.
- Posting results to ruby gems server

### CODE REVIEW

**Comment by colby-swandale** [comment]
Hi @Speculate7, sorry that no one has replied this this PR request. Can you explain what this change is trying to improve or solve?

**Comment by colby-swandale** [comment]
ping @Speculate7

**Comment by mikegee** [comment]
@Speculate7 is this still relevant?

**Comment by esasse** [comment]
No response from author.

**Pull request closed without merging**
