### PR TITLE
Rename `-rubygerms` option.

### PR DESCRIPTION
**Pull request by hsbt**
Followup #6080 for 1-16-stable branch.

### CODE REVIEW

**Comment by indirect** [comment]
👍 @bundlerbot r+

**Comment by colby-swandale** [comment]
#6118 should fix the merge issue

**Comment by walf443** [comment]
retry?

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
ah, I don't have commit bit of this repository. I mistook this as rubygems repo.

**Comment by colby-swandale** [comment]
@bundlerbot retry

**Comment by colby-swandale** [comment]
@bundlerbot retry

**Comment by colby-swandale** [comment]
@hsbt can you please rebase from `1-16-stable`

**Comment by hsbt** [comment]
done!

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
